// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val agenticDesignSystem = AnduraDesignSystem(
    id = "agentic",
    name = "Agentic",
    category = "Themed & Unique",
    description = "Bundled Open Design package for Agentic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF0B1020u,
    surface = 0xFF131B2Fu,
    surfaceWarm = 0xFF182343u,
    foreground = 0xFFF8FAFCu,
    foregroundSecondary = 0xFFCBD5E1u,
    muted = 0xFF8EA0B8u,
    border = 0xFF293653u,
    accent = 0xFF60A5FAu,
    accentOn = 0xFF06111Fu,
    success = 0xFF22C55Eu,
    warning = 0xFFFBBF24u,
    danger = 0xFFFB7185u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 15.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 20.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 130,
    motionBaseMs = 220,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
