// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val airbnbDesignSystem = AnduraDesignSystem(
    id = "airbnb",
    name = "Airbnb",
    category = "E-Commerce & Retail",
    description = "Bundled Open Design package for Airbnb, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFF7F7F7u,
    foreground = 0xFF222222u,
    foregroundSecondary = 0xFF3F3F3Fu,
    muted = 0xFF6A6A6Au,
    border = 0xFFDDDDDDu,
    accent = 0xFFFF385Cu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF008A05u,
    warning = 0xFFC47700u,
    danger = 0xFFC13515u,
    fontDisplay = "Airbnb Cereal VF",
    fontBody = "Airbnb Cereal VF",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 14.0f,
    radiusLg = 20.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 67,
)
