// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val airtableDesignSystem = AnduraDesignSystem(
    id = "airtable",
    name = "Airtable",
    category = "Design & Creative",
    description = "Bundled Open Design package for Airtable, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFFFFFu,
    foreground = 0xFF181D26u,
    foregroundSecondary = 0xFF333333u,
    muted = 0xB0040E20u,
    border = 0xFFE0E2E6u,
    accent = 0xFF1B61C9u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF006400u,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Haas Groot Disp",
    fontBody = "Haas",
    textBase = 16.0f,
    radiusSm = 12.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 35,
)
