// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val anduraDesignSystemsChunk01 = listOf(
    AnduraDesignSystem(
        id = "agentic", name = "Agentic", category = "Themed & Unique", description = "Bundled Open Design package for Agentic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF0B1020u, surface = 0xFF131B2Fu, surfaceWarm = 0xFF182343u, foreground = 0xFFF8FAFCu, foregroundSecondary = 0xFFCBD5E1u, muted = 0xFF8EA0B8u, border = 0xFF293653u,
        accent = 0xFF60A5FAu, accentOn = 0xFF06111Fu, success = 0xFF22C55Eu, warning = 0xFFFBBF24u, danger = 0xFFFB7185u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 15.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 20.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 130, motionBaseMs = 220, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "airbnb", name = "Airbnb", category = "E-Commerce & Retail", description = "Bundled Open Design package for Airbnb, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFF7F7F7u, foreground = 0xFF222222u, foregroundSecondary = 0xFF3F3F3Fu, muted = 0xFF6A6A6Au, border = 0xFFDDDDDDu,
        accent = 0xFFFF385Cu, accentOn = 0xFFFFFFFFu, success = 0xFF008A05u, warning = 0xFFC47700u, danger = 0xFFC13515u,
        fontDisplay = "Airbnb Cereal VF", fontBody = "Airbnb Cereal VF", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 14.0f, radiusLg = 20.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 67,
    ),
    AnduraDesignSystem(
        id = "airtable", name = "Airtable", category = "Design & Creative", description = "Bundled Open Design package for Airtable, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFFFFFu, foreground = 0xFF181D26u, foregroundSecondary = 0xFF333333u, muted = 0xB0040E20u, border = 0xFFE0E2E6u,
        accent = 0xFF1B61C9u, accentOn = 0xFFFFFFFFu, success = 0xFF006400u, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Haas Groot Disp", fontBody = "Haas", textBase = 16.0f, radiusSm = 12.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 35,
    ),
    AnduraDesignSystem(
        id = "ant", name = "Ant", category = "Professional & Corporate", description = "Bundled Open Design package for Ant, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF7F8FAu, surfaceWarm = 0xFFFFF1F0u, foreground = 0xFF1F1F1Fu, foregroundSecondary = 0xFF4B5563u, muted = 0xFF697386u, border = 0xFFD9DCE3u,
        accent = 0xFFD32029u, accentOn = 0xFFFFFFFFu, success = 0xFF22A06Bu, warning = 0xFFFAAD14u, danger = 0xFFCF1322u,
        fontDisplay = "Ant Sans", fontBody = "Ant Sans", textBase = 16.0f, radiusSm = 6.0f, radiusMd = 10.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 140, motionBaseMs = 220, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "apple", name = "Apple", category = "Media & Consumer", description = "Bundled Open Design package for Apple, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF5F5F7u, surfaceWarm = 0xFFFBFBFDu, foreground = 0xFF1D1D1Fu, foregroundSecondary = 0xFF424245u, muted = 0xFF6E6E73u, border = 0xFFD2D2D7u,
        accent = 0xFF0071E3u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "SF Pro Display", fontBody = "SF Pro Text", textBase = 17.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 18.0f, radiusPill = 980.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 220, containerMax = 1024.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 35,
    ),
    AnduraDesignSystem(
        id = "application", name = "Application", category = "Professional & Corporate", description = "Bundled Open Design package for Application, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF6F7F9u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEEF4FFu, foreground = 0xFF172033u, foregroundSecondary = 0xFF3B4658u, muted = 0xFF6B7689u, border = 0xFFD8DEE8u,
        accent = 0xFF2563EBu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFF59E0Bu, danger = 0xFFDC2626u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 18.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 140, motionBaseMs = 220, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "arc", name = "Arc Browser", category = "Productivity & SaaS", description = "Bundled Open Design package for Arc Browser, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFDF3ECu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFF4EAu, foreground = 0xFF1A1A1Fu, foregroundSecondary = 0xFF54545Au, muted = 0xFF8C8C93u, border = 0xFFECE5DBu,
        accent = 0xFFFF5F5Fu, accentOn = 0xFFFFFFFFu, success = 0xFF48BB78u, warning = 0xFFF6AD55u, danger = 0xFFF56565u,
        fontDisplay = "Argent CF", fontBody = "Inter", textBase = 15.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 200, motionBaseMs = 320, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 27,
    ),
    AnduraDesignSystem(
        id = "artistic", name = "Artistic", category = "Creative & Artistic", description = "Bundled Open Design package for Artistic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFBF6EEu, surface = 0xFFFFFDF8u, surfaceWarm = 0xFFF1E3CFu, foreground = 0xFF201914u, foregroundSecondary = 0xFF4C4037u, muted = 0xFF7A6D63u, border = 0xFFDED2C3u,
        accent = 0xFF9B5B32u, accentOn = 0xFFFFFFFFu, success = 0xFF4F8A4Fu, warning = 0xFFC9822Fu, danger = 0xFFB33A3Au,
        fontDisplay = "Georgia", fontBody = "Inter", textBase = 17.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "atelier-zero", name = "Atelier Zero", category = "Editorial · Studio", description = "Bundled Open Design package for Atelier Zero, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF7F7F7u, surfaceWarm = 0xFFEEEEEEu, foreground = 0xFF111111u, foregroundSecondary = 0xFF3A3A3Au, muted = 0xFF707070u, border = 0xFFD9D9D9u,
        accent = 0xFF111111u, accentOn = 0xFFFFFFFFu, success = 0xFF168A46u, warning = 0xFFB7791Fu, danger = 0xFFC53030u,
        fontDisplay = "Helvetica Neue", fontBody = "Helvetica Neue", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "bento", name = "Bento", category = "Layout & Structure", description = "Bundled Open Design package for Bento, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF5F8FFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEAF1FFu, foreground = 0xFF101828u, foregroundSecondary = 0xFF344054u, muted = 0xFF667085u, border = 0xFFD7E0EFu,
        accent = 0xFF2563EBu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "binance", name = "Binance.US", category = "Fintech & Crypto", description = "Bundled Open Design package for Binance.US, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFF5F5F5u, foreground = 0xFF1E2026u, foregroundSecondary = 0xFF32313Au, muted = 0xFF848E9Cu, border = 0xFFE6E8EAu,
        accent = 0xFFF0B90Bu, accentOn = 0xFF1E2026u, success = 0xFF0ECB81u, warning = 0xFFEAB308u, danger = 0xFFF6465Du,
        fontDisplay = "BinancePlex", fontBody = "BinancePlex", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 46,
    ),
    AnduraDesignSystem(
        id = "bmw", name = "BMW", category = "Automotive", description = "Bundled Open Design package for BMW, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF5F5F5u, surfaceWarm = 0xFFF5F5F5u, foreground = 0xFF262626u, foregroundSecondary = 0xFF262626u, muted = 0xFF757575u, border = 0xFFE0E0E0u,
        accent = 0xFF1C69D4u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "BMWTypeNextLatin Light", fontBody = "BMWTypeNextLatin", textBase = 16.0f, radiusSm = 0.0f, radiusMd = 0.0f, radiusLg = 0.0f, radiusPill = 0.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1440.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"), sourceClassCount = 28,
    ),
    AnduraDesignSystem(
        id = "bmw-m", name = "BMW M", category = "Automotive", description = "Bundled Open Design package for BMW M, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF7F8FAu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEEF3F8u, foreground = 0xFF111827u, foregroundSecondary = 0xFF334155u, muted = 0xFF64748Bu, border = 0xFFD7DEE8u,
        accent = 0xFF0066B1u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFF59E0Bu, danger = 0xFFE4002Bu,
        fontDisplay = "BMWTypeNext", fontBody = "BMWTypeNext", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 14.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 130, motionBaseMs = 220, containerMax = 1220.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "bold", name = "Bold", category = "Bold & Expressive", description = "Bundled Open Design package for Bold, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF7F7F7u, surfaceWarm = 0xFFEEEEEEu, foreground = 0xFF111111u, foregroundSecondary = 0xFF3A3A3Au, muted = 0xFF707070u, border = 0xFFD9D9D9u,
        accent = 0xFF111111u, accentOn = 0xFFFFFFFFu, success = 0xFF168A46u, warning = 0xFFB7791Fu, danger = 0xFFC53030u,
        fontDisplay = "Arial Black", fontBody = "Inter", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "brutalism", name = "Brutalism", category = "Bold & Expressive", description = "Bundled Open Design package for Brutalism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF5F1E8u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFEF5Au, foreground = 0xFF000000u, foregroundSecondary = 0xFF222222u, muted = 0xFF555555u, border = 0xFF000000u,
        accent = 0xFFFFEF5Au, accentOn = 0xFF000000u, success = 0xFF00B050u, warning = 0xFFFF8C00u, danger = 0xFFFF2B2Bu,
        fontDisplay = "Arial Black", fontBody = "Arial", textBase = 17.0f, radiusSm = 0.0f, radiusMd = 0.0f, radiusLg = 0.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 90, motionBaseMs = 140, containerMax = 1160.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "bugatti", name = "Bugatti", category = "Automotive", description = "Bundled Open Design package for Bugatti, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF07111Fu, surface = 0xFF101D2Fu, surfaceWarm = 0xFF16283Fu, foreground = 0xFFF7FBFFu, foregroundSecondary = 0xFFD6E0EEu, muted = 0xFF8FA1B7u, border = 0xFF2C405Cu,
        accent = 0xFF1B4D8Fu, accentOn = 0xFFFFFFFFu, success = 0xFF2FBF71u, warning = 0xFFD9B45Fu, danger = 0xFFC1121Fu,
        fontDisplay = "Bugatti Display", fontBody = "Avenir Next", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 14.0f, radiusLg = 22.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 170, motionBaseMs = 280, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "cafe", name = "Cafe", category = "Creative & Artistic", description = "Bundled Open Design package for Cafe, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFBF6EEu, surface = 0xFFFFFDF8u, surfaceWarm = 0xFFF1E3CFu, foreground = 0xFF201914u, foregroundSecondary = 0xFF4C4037u, muted = 0xFF7A6D63u, border = 0xFFDED2C3u,
        accent = 0xFF9B5B32u, accentOn = 0xFFFFFFFFu, success = 0xFF4F8A4Fu, warning = 0xFFC9822Fu, danger = 0xFFB33A3Au,
        fontDisplay = "Georgia", fontBody = "Inter", textBase = 17.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "cal", name = "Cal.com", category = "Productivity & SaaS", description = "Bundled Open Design package for Cal.com, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFFFFFu, foreground = 0xFF242424u, foregroundSecondary = 0xFF111111u, muted = 0xFF898989u, border = 0x14222A35u,
        accent = 0xFF0099FFu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Cal Sans", fontBody = "Inter", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "canva", name = "Canva", category = "Design & Creative", description = "Bundled Open Design package for Canva, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF4F5F7u, surfaceWarm = 0xFFF4F5F7u, foreground = 0xFF0E1318u, foregroundSecondary = 0xFF3C4043u, muted = 0xFF5F6368u, border = 0xFFE1E3E6u,
        accent = 0xFF7D2AE8u, accentOn = 0xFFFFFFFFu, success = 0xFF00B894u, warning = 0xFFFFB020u, danger = 0xFFFF5757u,
        fontDisplay = "Canva Sans", fontBody = "Canva Sans", textBase = 14.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 180, motionBaseMs = 280, containerMax = 1320.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 32,
    ),
    AnduraDesignSystem(
        id = "cisco", name = "Cisco", category = "Backend & Data", description = "Bundled Open Design package for Cisco, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF0F1720u, surface = 0xFF1B2530u, surfaceWarm = 0xFF243447u, foreground = 0xFFFFFFFFu, foregroundSecondary = 0xFFE8EBF1u, muted = 0xFF9E9EA2u, border = 0xFF58585Bu,
        accent = 0xFF049FD9u, accentOn = 0xFF001923u, success = 0xFF6CC04Au, warning = 0xFFFFCC00u, danger = 0xFFCF2030u,
        fontDisplay = "CiscoSansTT", fontBody = "CiscoSansTT", textBase = 16.0f, radiusSm = 12.0f, radiusMd = 20.0f, radiusLg = 28.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 160, motionBaseMs = 240, containerMax = 1240.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
)
