// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val anduraDesignSystemsChunk05 = listOf(
    AnduraDesignSystem(
        id = "mistral-ai", name = "Mistral AI", category = "AI & LLM", description = "Bundled Open Design package for Mistral AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFAEBu, surface = 0xFFFFF0C2u, surfaceWarm = 0xFFFFF0C2u, foreground = 0xFF1F1F1Fu, foregroundSecondary = 0xFF1F1F1Fu, muted = 0xFF3D3D3Du, border = 0xFFF0E8C8u,
        accent = 0xFFFA520Fu, accentOn = 0xFFFFFFFFu, success = 0xFF17A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Arial", fontBody = "Arial", textBase = 16.0f, radiusSm = 2.0f, radiusMd = 2.0f, radiusLg = 4.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 25,
    ),
    AnduraDesignSystem(
        id = "modern", name = "Modern", category = "Modern & Minimal", description = "Bundled Open Design package for Modern, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF7F8FCu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEEF1FFu, foreground = 0xFF111827u, foregroundSecondary = 0xFF374151u, muted = 0xFF6B7280u, border = 0xFFDFE3EDu,
        accent = 0xFF4F46E5u, accentOn = 0xFFFFFFFFu, success = 0xFF10B981u, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "mongodb", name = "MongoDB", category = "Backend & Data", description = "Bundled Open Design package for MongoDB, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF001E2Bu, surface = 0xFF1C2D38u, surfaceWarm = 0xFF1C2D38u, foreground = 0xFFFFFFFFu, foregroundSecondary = 0xFFE8EDEBu, muted = 0xFFB8C4C2u, border = 0xFF3D4F58u,
        accent = 0xFF00ED64u, accentOn = 0xFF001E2Bu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "MongoDB Value Serif", fontBody = "Euclid Circular A", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "mono", name = "Mono", category = "Modern & Minimal", description = "Bundled Open Design package for Mono, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF7F7F7u, surfaceWarm = 0xFFEEEEEEu, foreground = 0xFF111111u, foregroundSecondary = 0xFF3A3A3Au, muted = 0xFF707070u, border = 0xFFD9D9D9u,
        accent = 0xFF111111u, accentOn = 0xFFFFFFFFu, success = 0xFF168A46u, warning = 0xFFB7791Fu, danger = 0xFFC53030u,
        fontDisplay = "IBM Plex Mono", fontBody = "IBM Plex Mono", textBase = 14.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 100, motionBaseMs = 180, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "neobrutalism", name = "Neobrutalism", category = "Bold & Expressive", description = "Bundled Open Design package for Neobrutalism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF4CFu, surface = 0xFFFFFAF0u, surfaceWarm = 0xFFFFDCA8u, foreground = 0xFF2A1810u, foregroundSecondary = 0xFF593625u, muted = 0xFF8A6652u, border = 0xFFD9AA7Au,
        accent = 0xFFD24B1Fu, accentOn = 0xFFFFFFFFu, success = 0xFF3D8F4Fu, warning = 0xFFF2A93Bu, danger = 0xFFB83A2Fu,
        fontDisplay = "Arial Black", fontBody = "Inter", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "neon", name = "Neon", category = "Morphism & Effects", description = "Bundled Open Design package for Neon, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF070711u, surface = 0xFF111126u, surfaceWarm = 0xFF1E1540u, foreground = 0xFFF8F7FFu, foregroundSecondary = 0xFFD6CCFFu, muted = 0xFF9D8AD4u, border = 0xFF34265Eu,
        accent = 0xFFC084FCu, accentOn = 0xFF13051Fu, success = 0xFF39FF88u, warning = 0xFFFFF34Du, danger = 0xFFFF4D8Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "neumorphism", name = "Neumorphism", category = "Morphism & Effects", description = "Bundled Open Design package for Neumorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF7EEE6u, surface = 0xFFFFF8F1u, surfaceWarm = 0xFFEAD6C7u, foreground = 0xFF2B211Cu, foregroundSecondary = 0xFF5A4B43u, muted = 0xFF8A7A70u, border = 0xFFDAC8B9u,
        accent = 0xFFB46A46u, accentOn = 0xFFFFFFFFu, success = 0xFF4D8F5Au, warning = 0xFFC88735u, danger = 0xFFB84C4Cu,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 14.0f, radiusMd = 22.0f, radiusLg = 34.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "nike", name = "Nike", category = "E-Commerce & Retail", description = "Bundled Open Design package for Nike, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF5F5F5u, surfaceWarm = 0xFFFAFAFAu, foreground = 0xFF111111u, foregroundSecondary = 0xFF111111u, muted = 0xFF707072u, border = 0xFFCACACBu,
        accent = 0xFF111111u, accentOn = 0xFFFFFFFFu, success = 0xFF007D48u, warning = 0xFFFCA600u, danger = 0xFFD30005u,
        fontDisplay = "Nike Futura ND", fontBody = "Helvetica Now Text Medium", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 20.0f, radiusLg = 24.0f, radiusPill = 30.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1440.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 29,
    ),
    AnduraDesignSystem(
        id = "notion", name = "Notion", category = "Productivity & SaaS", description = "Bundled Open Design package for Notion, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF6F5F4u, surfaceWarm = 0xFFF6F5F4u, foreground = 0xF2000000u, foregroundSecondary = 0xFF31302Eu, muted = 0xFF615D59u, border = 0x1A000000u,
        accent = 0xFF0075DEu, accentOn = 0xFFFFFFFFu, success = 0xFF1AAE39u, warning = 0xFFDD5B00u, danger = 0xFFDC2626u,
        fontDisplay = "NotionInter", fontBody = "NotionInter", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"), sourceClassCount = 22,
    ),
    AnduraDesignSystem(
        id = "nvidia", name = "NVIDIA", category = "Media & Consumer", description = "Bundled Open Design package for NVIDIA, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF000000u, surface = 0xFF1A1A1Au, surfaceWarm = 0xFF1A1A1Au, foreground = 0xFFFFFFFFu, foregroundSecondary = 0xFFA7A7A7u, muted = 0xFF757575u, border = 0xFF5E5E5Eu,
        accent = 0xFF76B900u, accentOn = 0xFF000000u, success = 0xFF3F8500u, warning = 0xFFEF9100u, danger = 0xFFE52020u,
        fontDisplay = "NVIDIA-EMEA", fontBody = "NVIDIA-EMEA", textBase = 16.0f, radiusSm = 2.0f, radiusMd = 2.0f, radiusLg = 4.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"), sourceClassCount = 31,
    ),
    AnduraDesignSystem(
        id = "ollama", name = "Ollama", category = "AI & LLM", description = "Bundled Open Design package for Ollama, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFAFAFAu, surfaceWarm = 0xFFFAFAFAu, foreground = 0xFF000000u, foregroundSecondary = 0xFF262626u, muted = 0xFF737373u, border = 0xFFE5E5E5u,
        accent = 0xFF000000u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "SF Pro Rounded", fontBody = "ui-sans-serif", textBase = 16.0f, radiusSm = 9999.0f, radiusMd = 12.0f, radiusLg = 9999.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 100, motionBaseMs = 140, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"), sourceClassCount = 34,
    ),
    AnduraDesignSystem(
        id = "openai", name = "OpenAI", category = "AI & LLM", description = "Bundled Open Design package for OpenAI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF5F5F5u, surfaceWarm = 0xFFFAFAFAu, foreground = 0xFF0D0D0Du, foregroundSecondary = 0xFF1A1A1Au, muted = 0xFF6E6E6Eu, border = 0xFFE5E5E5u,
        accent = 0xFF10A37Fu, accentOn = 0xFFFFFFFFu, success = 0xFF10A37Fu, warning = 0xFFF5A623u, danger = 0xFFEF4146u,
        fontDisplay = "Signifier", fontBody = "Söhne", textBase = 16.0f, radiusSm = 12.0f, radiusMd = 16.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 220, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"), sourceClassCount = 18,
    ),
    AnduraDesignSystem(
        id = "opencode-ai", name = "OpenCode", category = "AI & LLM", description = "Bundled Open Design package for OpenCode, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF201D1Du, surface = 0xFF302C2Cu, surfaceWarm = 0xFF302C2Cu, foreground = 0xFFFDFCFCu, foregroundSecondary = 0xFFC8C6C4u, muted = 0xFF9A9898u, border = 0xFF464343u,
        accent = 0xFF007AFFu, accentOn = 0xFFFFFFFFu, success = 0xFF30D158u, warning = 0xFFFF9F0Au, danger = 0xFFFF3B30u,
        fontDisplay = "Berkeley Mono", fontBody = "Berkeley Mono", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 6.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 100, motionBaseMs = 150, containerMax = 880.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "pacman", name = "Pacman", category = "Themed & Unique", description = "Bundled Open Design package for Pacman, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF050505u, surface = 0xFF101014u, surfaceWarm = 0xFF1F1B08u, foreground = 0xFFFFF7D6u, foregroundSecondary = 0xFFF6E79Cu, muted = 0xFFB9A85Du, border = 0xFF2338FFu,
        accent = 0xFFFFCC00u, accentOn = 0xFF050505u, success = 0xFF00FF66u, warning = 0xFFFF9900u, danger = 0xFFFF3B3Bu,
        fontDisplay = "Press Start 2P", fontBody = "Inter", textBase = 14.0f, radiusSm = 10.0f, radiusMd = 18.0f, radiusLg = 9999.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 90, motionBaseMs = 160, containerMax = 1080.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "paper", name = "Paper", category = "Retro & Nostalgic", description = "Bundled Open Design package for Paper, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFAF3DFu, surface = 0xFFFFFAF0u, surfaceWarm = 0xFFEFE0BDu, foreground = 0xFF211B12u, foregroundSecondary = 0xFF504737u, muted = 0xFF7C7160u, border = 0xFFDDD0B4u,
        accent = 0xFF8F5D24u, accentOn = 0xFFFFFFFFu, success = 0xFF5B8D42u, warning = 0xFFC27B22u, danger = 0xFFA64036u,
        fontDisplay = "Georgia", fontBody = "Inter", textBase = 17.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "perplexity", name = "Perplexity AI", category = "AI & LLM", description = "Bundled Open Design package for Perplexity AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF0F0F10u, surface = 0xFF19191Au, surfaceWarm = 0xFF19191Au, foreground = 0xFFF0F0F0u, foregroundSecondary = 0xFFF0F0F0u, muted = 0xFF9B9B9Bu, border = 0xFF2E2E30u,
        accent = 0xFFA855F7u, accentOn = 0xFFFFFFFFu, success = 0xFF22C55Eu, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 15.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 120, motionBaseMs = 200, containerMax = 1100.0f, componentGroups = listOf("buttons", "inputs", "cards", "links", "icons", "typography", "layout"), sourceClassCount = 23,
    ),
    AnduraDesignSystem(
        id = "perspective", name = "Perspective", category = "Layout & Structure", description = "Bundled Open Design package for Perspective, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF5F8FFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEAF1FFu, foreground = 0xFF101828u, foregroundSecondary = 0xFF344054u, muted = 0xFF667085u, border = 0xFFD7E0EFu,
        accent = 0xFF2563EBu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "pinterest", name = "Pinterest", category = "Media & Consumer", description = "Bundled Open Design package for Pinterest, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF6F6F3u, surfaceWarm = 0xFFE5E5E0u, foreground = 0xFF211922u, foregroundSecondary = 0xFF000000u, muted = 0xFF62625Bu, border = 0xFFC8C8C1u,
        accent = 0xFFE60023u, accentOn = 0xFF000000u, success = 0xFF103C25u, warning = 0xFFC47700u, danger = 0xFF9E0A0Au,
        fontDisplay = "Pin Sans", fontBody = "Pin Sans", textBase = 16.0f, radiusSm = 12.0f, radiusMd = 16.0f, radiusLg = 28.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 43,
    ),
    AnduraDesignSystem(
        id = "playstation", name = "PlayStation", category = "Media & Consumer", description = "Bundled Open Design package for PlayStation, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF000000u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFF5F7FAu, foreground = 0xFFFFFFFFu, foregroundSecondary = 0xFFFFFFFFu, muted = 0xFFCCCCCCu, border = 0xFFCCCCCCu,
        accent = 0xFF0070CCu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFC81B3Au,
        fontDisplay = "SST", fontBody = "SST", textBase = 18.0f, radiusSm = 6.0f, radiusMd = 12.0f, radiusLg = 24.0f, radiusPill = 999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 180, motionBaseMs = 200, containerMax = 1600.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 28,
    ),
    AnduraDesignSystem(
        id = "posthog", name = "PostHog", category = "Backend & Data", description = "Bundled Open Design package for PostHog, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFDFDF8u, surface = 0xFFEEEFE9u, surfaceWarm = 0xFFE5E7E0u, foreground = 0xFF4D4F46u, foregroundSecondary = 0xFF23251Du, muted = 0xFF65675Eu, border = 0xFFBFC1B7u,
        accent = 0xFFF54E00u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFF7A501u, danger = 0xFFDC2626u,
        fontDisplay = "IBM Plex Sans Variable", fontBody = "IBM Plex Sans Variable", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 6.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 42,
    ),
)
