// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val anduraDesignSystemsChunk03 = listOf(
    AnduraDesignSystem(
        id = "duolingo", name = "Duolingo", category = "Productivity & SaaS", description = "Bundled Open Design package for Duolingo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF7F7F7u, surfaceWarm = 0xFFF7F7F7u, foreground = 0xFF3C3C3Cu, foregroundSecondary = 0xFF3C3C3Cu, muted = 0xFF777777u, border = 0xFFE5E5E5u,
        accent = 0xFF58CC02u, accentOn = 0xFFFFFFFFu, success = 0xFF58CC02u, warning = 0xFFFFC800u, danger = 0xFFFF4B4Bu,
        fontDisplay = "Feather Bold", fontBody = "Mona Sans", textBase = 15.0f, radiusSm = 12.0f, radiusMd = 16.0f, radiusLg = 20.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 180, motionBaseMs = 320, containerMax = 1080.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 36,
    ),
    AnduraDesignSystem(
        id = "editorial", name = "Editorial", category = "Creative & Artistic", description = "Bundled Open Design package for Editorial, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFBF7F0u, surface = 0xFFFFFDF8u, surfaceWarm = 0xFFF1E6D6u, foreground = 0xFF1F1A16u, foregroundSecondary = 0xFF4B4038u, muted = 0xFF7D7168u, border = 0xFFDED3C5u,
        accent = 0xFF9A5A2Fu, accentOn = 0xFFFFFFFFu, success = 0xFF4F8A4Fu, warning = 0xFFC9822Fu, danger = 0xFFB33A3Au,
        fontDisplay = "Georgia", fontBody = "Source Serif Pro", textBase = 18.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 180, motionBaseMs = 280, containerMax = 1120.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "elegant", name = "Elegant", category = "Professional & Corporate", description = "Bundled Open Design package for Elegant, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFBF6EEu, surface = 0xFFFFFDF8u, surfaceWarm = 0xFFF1E3CFu, foreground = 0xFF201914u, foregroundSecondary = 0xFF4C4037u, muted = 0xFF7A6D63u, border = 0xFFDED2C3u,
        accent = 0xFF9B5B32u, accentOn = 0xFFFFFFFFu, success = 0xFF4F8A4Fu, warning = 0xFFC9822Fu, danger = 0xFFB33A3Au,
        fontDisplay = "Georgia", fontBody = "Inter", textBase = 17.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "elevenlabs", name = "ElevenLabs", category = "AI & LLM", description = "Bundled Open Design package for ElevenLabs, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF5F5F5u, surfaceWarm = 0xFFF5F2EFu, foreground = 0xFF000000u, foregroundSecondary = 0xFF4E4E4Eu, muted = 0xFF777169u, border = 0xFFE5E5E5u,
        accent = 0xFF000000u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Waldenburg", fontBody = "Inter", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 24,
    ),
    AnduraDesignSystem(
        id = "energetic", name = "Energetic", category = "Bold & Expressive", description = "Bundled Open Design package for Energetic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF8D7u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFEF9Fu, foreground = 0xFF1D1836u, foregroundSecondary = 0xFF4C426Cu, muted = 0xFF796F91u, border = 0xFFEADFBAu,
        accent = 0xFFFF6B00u, accentOn = 0xFFFFFFFFu, success = 0xFF2E9D57u, warning = 0xFFFFB020u, danger = 0xFFE5484Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "enterprise", name = "Enterprise", category = "Professional & Corporate", description = "Bundled Open Design package for Enterprise, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF8FAFCu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEEF2F7u, foreground = 0xFF0F172Au, foregroundSecondary = 0xFF334155u, muted = 0xFF64748Bu, border = 0xFFD8DEE8u,
        accent = 0xFF1D4ED8u, accentOn = 0xFFFFFFFFu, success = 0xFF15803Du, warning = 0xFFB45309u, danger = 0xFFB91C1Cu,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 6.0f, radiusMd = 10.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 230, containerMax = 1240.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "expo", name = "Expo", category = "Developer Tools", description = "Bundled Open Design package for Expo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF6F7F9u, surfaceWarm = 0xFFEEF2FFu, foreground = 0xFF0B0D12u, foregroundSecondary = 0xFF353945u, muted = 0xFF6B7280u, border = 0xFFDFE3EAu,
        accent = 0xFF000020u, accentOn = 0xFFFFFFFFu, success = 0xFF00A36Cu, warning = 0xFFF59E0Bu, danger = 0xFFE5484Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 14.0f, radiusLg = 22.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 140, motionBaseMs = 220, containerMax = 1160.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "expressive", name = "Expressive", category = "Bold & Expressive", description = "Bundled Open Design package for Expressive, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFBF8FFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEFE8FFu, foreground = 0xFF1F1730u, foregroundSecondary = 0xFF4D425Fu, muted = 0xFF776B88u, border = 0xFFDED4EEu,
        accent = 0xFF7C3AEDu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "fantasy", name = "Fantasy", category = "Creative & Artistic", description = "Bundled Open Design package for Fantasy, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF070711u, surface = 0xFF111126u, surfaceWarm = 0xFF1E1540u, foreground = 0xFFF8F7FFu, foregroundSecondary = 0xFFD6CCFFu, muted = 0xFF9D8AD4u, border = 0xFF34265Eu,
        accent = 0xFFC084FCu, accentOn = 0xFF13051Fu, success = 0xFF39FF88u, warning = 0xFFFFF34Du, danger = 0xFFFF4D8Du,
        fontDisplay = "Georgia", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "ferrari", name = "Ferrari", category = "Automotive", description = "Bundled Open Design package for Ferrari, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF0B0B0Bu, surface = 0xFF171717u, surfaceWarm = 0xFF23130Fu, foreground = 0xFFFFFAF0u, foregroundSecondary = 0xFFE8DCC8u, muted = 0xFFA89F91u, border = 0xFF342A24u,
        accent = 0xFFDC0000u, accentOn = 0xFFFFFFFFu, success = 0xFF0F9D58u, warning = 0xFFFFD200u, danger = 0xFFFF3B30u,
        fontDisplay = "Ferrari Sans", fontBody = "Ferrari Sans", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 14.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 130, motionBaseMs = 220, containerMax = 1240.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "figma", name = "Figma", category = "Design & Creative", description = "Bundled Open Design package for Figma, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFFFFFu, foreground = 0xFF000000u, foregroundSecondary = 0xFF000000u, muted = 0x8C000000u, border = 0x1F000000u,
        accent = 0xFF000000u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "figmaSans", fontBody = "figmaSans", textBase = 16.0f, radiusSm = 50.0f, radiusMd = 8.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1920.0f, componentGroups = listOf("buttons", "inputs", "cards", "links", "icons", "typography", "layout"), sourceClassCount = 17,
    ),
    AnduraDesignSystem(
        id = "flat", name = "Flat", category = "Modern & Minimal", description = "Bundled Open Design package for Flat, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF5F8FFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEAF1FFu, foreground = 0xFF101828u, foregroundSecondary = 0xFF344054u, muted = 0xFF667085u, border = 0xFFD7E0EFu,
        accent = 0xFF2563EBu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "framer", name = "Framer", category = "Design & Creative", description = "Bundled Open Design package for Framer, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF000000u, surface = 0xFF090909u, surfaceWarm = 0xFF090909u, foreground = 0xFFFFFFFFu, foregroundSecondary = 0xFFA6A6A6u, muted = 0x99FFFFFFu, border = 0x260099FFu,
        accent = 0xFF0099FFu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "GT Walsheim Framer Medium", fontBody = "Inter Variable", textBase = 15.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 20.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 32,
    ),
    AnduraDesignSystem(
        id = "friendly", name = "Friendly", category = "Creative & Artistic", description = "Bundled Open Design package for Friendly, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF8D7u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFEF9Fu, foreground = 0xFF1D1836u, foregroundSecondary = 0xFF4C426Cu, muted = 0xFF796F91u, border = 0xFFEADFBAu,
        accent = 0xFFFF6B00u, accentOn = 0xFFFFFFFFu, success = 0xFF2E9D57u, warning = 0xFFFFB020u, danger = 0xFFE5484Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "futuristic", name = "Futuristic", category = "Themed & Unique", description = "Bundled Open Design package for Futuristic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF090B12u, surface = 0xFF121722u, surfaceWarm = 0xFF1B2233u, foreground = 0xFFF8FAFCu, foregroundSecondary = 0xFFCBD5E1u, muted = 0xFF94A3B8u, border = 0xFF2A3447u,
        accent = 0xFF60A5FAu, accentOn = 0xFF06101Du, success = 0xFF22C55Eu, warning = 0xFFFBBF24u, danger = 0xFFFB7185u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "github", name = "GitHub", category = "Developer Tools", description = "Bundled Open Design package for GitHub, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF6F8FAu, surfaceWarm = 0xFFF6F8FAu, foreground = 0xFF1F2328u, foregroundSecondary = 0xFF1F2328u, muted = 0xFF656D76u, border = 0xFFD0D7DEu,
        accent = 0xFF0969DAu, accentOn = 0xFFFFFFFFu, success = 0xFF1A7F37u, warning = 0xFF9A6700u, danger = 0xFFCF222Eu,
        fontDisplay = "-apple-system", fontBody = "-apple-system", textBase = 14.0f, radiusSm = 6.0f, radiusMd = 6.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 80, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "badges", "links", "icons", "typography", "layout"), sourceClassCount = 21,
    ),
    AnduraDesignSystem(
        id = "glassmorphism", name = "Glassmorphism", category = "Morphism & Effects", description = "Bundled Open Design package for Glassmorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFEEF6FFu, surface = 0xBDFFFFFFu, surfaceWarm = 0xB8EEF6FFu, foreground = 0xFF102033u, foregroundSecondary = 0xFF34465Fu, muted = 0xFF60708Au, border = 0xA3FFFFFFu,
        accent = 0xFF4F8CFFu, accentOn = 0xFFFFFFFFu, success = 0xFF22C55Eu, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 16.0f, radiusMd = 24.0f, radiusLg = 36.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 180, motionBaseMs = 280, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "gradient", name = "Gradient", category = "Morphism & Effects", description = "Bundled Open Design package for Gradient, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF7F3FFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEFE7FFu, foreground = 0xFF191225u, foregroundSecondary = 0xFF443856u, muted = 0xFF746985u, border = 0xFFDDD2F2u,
        accent = 0xFF7C3AEDu, accentOn = 0xFFFFFFFFu, success = 0xFF10B981u, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 12.0f, radiusMd = 20.0f, radiusLg = 32.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 160, motionBaseMs = 260, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "hashicorp", name = "HashiCorp", category = "Backend & Data", description = "Bundled Open Design package for HashiCorp, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF15181Eu, surface = 0xFF0D0E12u, surfaceWarm = 0xFF0D0E12u, foreground = 0xFFEFEFF1u, foregroundSecondary = 0xFFD5D7DBu, muted = 0xFFB2B6BDu, border = 0x66B2B6BDu,
        accent = 0xFF1060FFu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFBB5A00u, danger = 0xFFDC2626u,
        fontDisplay = "HashiCorp Sans", fontBody = "Poppins", textBase = 16.0f, radiusSm = 5.0f, radiusMd = 8.0f, radiusLg = 8.0f, radiusPill = 5.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1150.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 27,
    ),
    AnduraDesignSystem(
        id = "hud", name = "HUD Design System", category = "Themed & Unique", description = "Bundled Open Design package for HUD Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF090B12u, surface = 0xFF121722u, surfaceWarm = 0xFF1B2233u, foreground = 0xFFF8FAFCu, foregroundSecondary = 0xFFCBD5E1u, muted = 0xFF94A3B8u, border = 0xFF2A3447u,
        accent = 0xFF60A5FAu, accentOn = 0xFF06101Du, success = 0xFF22C55Eu, warning = 0xFFFBBF24u, danger = 0xFFFB7185u,
        fontDisplay = "IBM Plex Mono", fontBody = "IBM Plex Mono", textBase = 14.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 100, motionBaseMs = 180, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
)
