// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val anduraDesignSystemsChunk04 = listOf(
    AnduraDesignSystem(
        id = "huggingface", name = "Hugging Face", category = "AI & LLM", description = "Bundled Open Design package for Hugging Face, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFAFAFAu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFF4CCu, foreground = 0xFF0D1117u, foregroundSecondary = 0xFF374151u, muted = 0xFF6B7280u, border = 0xFFE5E7EBu,
        accent = 0xFFFFD21Eu, accentOn = 0xFF0D1117u, success = 0xFF16A34Au, warning = 0xFFF59E0Bu, danger = 0xFFDC2626u,
        fontDisplay = "IBM Plex Mono", fontBody = "Source Sans Pro", textBase = 15.0f, radiusSm = 4.0f, radiusMd = 6.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 120, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "ibm", name = "IBM", category = "Media & Consumer", description = "Bundled Open Design package for IBM, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF4F4F4u, surfaceWarm = 0xFFEDF5FFu, foreground = 0xFF161616u, foregroundSecondary = 0xFF525252u, muted = 0xFF6F6F6Fu, border = 0xFFC6C6C6u,
        accent = 0xFF0F62FEu, accentOn = 0xFFFFFFFFu, success = 0xFF24A148u, warning = 0xFFF1C21Bu, danger = 0xFFDA1E28u,
        fontDisplay = "IBM Plex Sans", fontBody = "IBM Plex Sans", textBase = 16.0f, radiusSm = 0.0f, radiusMd = 0.0f, radiusLg = 0.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 110, motionBaseMs = 180, containerMax = 1312.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "intercom", name = "Intercom", category = "Productivity & SaaS", description = "Bundled Open Design package for Intercom, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFAF9F6u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFAF9F6u, foreground = 0xFF111111u, foregroundSecondary = 0xFF111111u, muted = 0xFF7B7B78u, border = 0xFFDEDBD6u,
        accent = 0xFFFF5600u, accentOn = 0xFFFFFFFFu, success = 0xFF00DA00u, warning = 0xFFEAB308u, danger = 0xFFC41C1Cu,
        fontDisplay = "Saans", fontBody = "Saans", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 6.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 37,
    ),
    AnduraDesignSystem(
        id = "kami", name = "kami (紙 / 纸)", category = "Editorial & Print", description = "Bundled Open Design package for kami (紙 / 纸), derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF5F4EDu, surface = 0xFFFAF9F5u, surfaceWarm = 0xFFE8E6DCu, foreground = 0xFF141413u, foregroundSecondary = 0xFF3D3D3Au, muted = 0xFF504E49u, border = 0xFFE8E6DCu,
        accent = 0xFF1B365Du, accentOn = 0xFFFAF9F5u, success = 0xFF4A6B3Au, warning = 0xFF8A6B1Fu, danger = 0xFF8A3A30u,
        fontDisplay = "Charter", fontBody = "Charter", textBase = 14.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1120.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "kraken", name = "Kraken", category = "Fintech & Crypto", description = "Bundled Open Design package for Kraken, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF0B1020u, surface = 0xFF121A33u, surfaceWarm = 0xFF1B2450u, foreground = 0xFFF8FAFCu, foregroundSecondary = 0xFFCBD5E1u, muted = 0xFF8B95AAu, border = 0xFF26314Fu,
        accent = 0xFF7132F5u, accentOn = 0xFFFFFFFFu, success = 0xFF00C853u, warning = 0xFFFFB020u, danger = 0xFFFF4D6Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 15.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 18.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 120, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "lamborghini", name = "Lamborghini", category = "Automotive", description = "Bundled Open Design package for Lamborghini, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF050505u, surface = 0xFF141414u, surfaceWarm = 0xFF211B0Bu, foreground = 0xFFF8F4E6u, foregroundSecondary = 0xFFD8CEB0u, muted = 0xFF9B927Du, border = 0xFF3A321Du,
        accent = 0xFFD4AF37u, accentOn = 0xFF050505u, success = 0xFF39A852u, warning = 0xFFF7C948u, danger = 0xFFE63946u,
        fontDisplay = "Lamborghini", fontBody = "Inter", textBase = 16.0f, radiusSm = 2.0f, radiusMd = 6.0f, radiusLg = 10.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 120, motionBaseMs = 210, containerMax = 1240.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "levels", name = "Levels", category = "Layout & Structure", description = "Bundled Open Design package for Levels, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFBF7EFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEEF7EDu, foreground = 0xFF1F2A24u, foregroundSecondary = 0xFF435147u, muted = 0xFF788276u, border = 0xFFDBE3D7u,
        accent = 0xFF2F8F46u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFD97706u, danger = 0xFFDC2626u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 12.0f, radiusMd = 18.0f, radiusLg = 28.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 160, motionBaseMs = 240, containerMax = 1160.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "linear-app", name = "Linear", category = "Productivity & SaaS", description = "Bundled Open Design package for Linear, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF08090Au, surface = 0xFF191A1Bu, surfaceWarm = 0xFF191A1Bu, foreground = 0xFFF7F8F8u, foregroundSecondary = 0xFFD0D6E0u, muted = 0xFF8A8F98u, border = 0x14FFFFFFu,
        accent = 0xFF5E6AD2u, accentOn = 0xFFFFFFFFu, success = 0xFF27A644u, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Inter Variable", fontBody = "Inter Variable", textBase = 16.0f, radiusSm = 6.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"), sourceClassCount = 15,
    ),
    AnduraDesignSystem(
        id = "lingo", name = "Lingo", category = "Creative & Artistic", description = "Bundled Open Design package for Lingo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFBF9FFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFF1ECFFu, foreground = 0xFF1D1B2Au, foregroundSecondary = 0xFF4F4863u, muted = 0xFF786F8Fu, border = 0xFFDED7F0u,
        accent = 0xFF6D4AFFu, accentOn = 0xFFFFFFFFu, success = 0xFF22A06Bu, warning = 0xFFE6A700u, danger = 0xFFE5484Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 230, containerMax = 1160.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "loom", name = "Loom Design System", category = "Themed & Unique", description = "Bundled Open Design package for Loom Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF7F7F8u, surfaceWarm = 0xFFF7F7F8u, foreground = 0xFF1F1F23u, foregroundSecondary = 0xFF1F1F23u, muted = 0xFF6B6D76u, border = 0xFFE4E4E7u,
        accent = 0xFF625DF5u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFD64770u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 14.0f, radiusSm = 4.0f, radiusMd = 6.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 100, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 31,
    ),
    AnduraDesignSystem(
        id = "lovable", name = "Lovable", category = "Developer Tools", description = "Bundled Open Design package for Lovable, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF7F4EDu, surface = 0xFFF7F4EDu, surfaceWarm = 0xFFF7F4EDu, foreground = 0xFF1C1C1Cu, foregroundSecondary = 0xD41C1C1Cu, muted = 0xFF5F5F5Du, border = 0xFFECEAE4u,
        accent = 0xFFFF4D8Du, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Camera Plain Variable", fontBody = "Camera Plain Variable", textBase = 16.0f, radiusSm = 6.0f, radiusMd = 12.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 24,
    ),
    AnduraDesignSystem(
        id = "luxury", name = "Luxury", category = "Professional & Corporate", description = "Bundled Open Design package for Luxury, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF080706u, surface = 0xFF151310u, surfaceWarm = 0xFF241E14u, foreground = 0xFFFFF8EAu, foregroundSecondary = 0xFFD8CDB7u, muted = 0xFF9F927Cu, border = 0xFF3A3020u,
        accent = 0xFFC6A15Bu, accentOn = 0xFF080706u, success = 0xFF5FA36Au, warning = 0xFFD8A94Fu, danger = 0xFFD85A52u,
        fontDisplay = "Didot", fontBody = "Avenir Next", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 14.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 180, motionBaseMs = 300, containerMax = 1160.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "mastercard", name = "Mastercard", category = "Fintech & Crypto", description = "Bundled Open Design package for Mastercard, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF3F0EEu, surface = 0xFFFCFBFAu, surfaceWarm = 0xFFF7E8DEu, foreground = 0xFF141413u, foregroundSecondary = 0xFF262627u, muted = 0xFF696969u, border = 0xFFD1CDC7u,
        accent = 0xFFCF4500u, accentOn = 0xFFFFFFFFu, success = 0xFF2E7D32u, warning = 0xFFF79E1Bu, danger = 0xFFEB001Bu,
        fontDisplay = "MarkForMC", fontBody = "MarkForMC", textBase = 16.0f, radiusSm = 20.0f, radiusMd = 40.0f, radiusLg = 64.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 180, motionBaseMs = 260, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "material", name = "Material", category = "Professional & Corporate", description = "Bundled Open Design package for Material, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF8FAFDu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFE8F0FEu, foreground = 0xFF202124u, foregroundSecondary = 0xFF3C4043u, muted = 0xFF5F6368u, border = 0xFFDADCE0u,
        accent = 0xFF1A73E8u, accentOn = 0xFFFFFFFFu, success = 0xFF188038u, warning = 0xFFF9AB00u, danger = 0xFFD93025u,
        fontDisplay = "Google Sans", fontBody = "Roboto", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 12.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 250, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "meta", name = "Meta (Store)", category = "E-Commerce & Retail", description = "Bundled Open Design package for Meta (Store), derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF7F8FAu, surfaceWarm = 0xFFF2F0E6u, foreground = 0xFF1C2B33u, foregroundSecondary = 0xFF5D6C7Bu, muted = 0xFF65676Bu, border = 0xFFCED0D4u,
        accent = 0xFF0064E0u, accentOn = 0xFFFFFFFFu, success = 0xFF31A24Cu, warning = 0xFFF7B928u, danger = 0xFFE41E3Fu,
        fontDisplay = "Optimistic VF", fontBody = "Optimistic VF", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 20.0f, radiusLg = 24.0f, radiusPill = 100.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1440.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 31,
    ),
    AnduraDesignSystem(
        id = "minimal", name = "Minimal", category = "Modern & Minimal", description = "Bundled Open Design package for Minimal, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFAFAFAu, surfaceWarm = 0xFFF5F5F5u, foreground = 0xFF111111u, foregroundSecondary = 0xFF3A3A3Au, muted = 0xFF777777u, border = 0xFFE2E2E2u,
        accent = 0xFF111111u, accentOn = 0xFFFFFFFFu, success = 0xFF168A46u, warning = 0xFFB7791Fu, danger = 0xFFC53030u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 2.0f, radiusMd = 4.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 140, motionBaseMs = 220, containerMax = 1120.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "minimax", name = "MiniMax", category = "AI & LLM", description = "Bundled Open Design package for MiniMax, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFAFAFAu, surfaceWarm = 0xFFF0F0F0u, foreground = 0xFF222222u, foregroundSecondary = 0xFF18181Bu, muted = 0xFF45515Eu, border = 0xFFE5E7EBu,
        accent = 0xFF1456F0u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Outfit", fontBody = "DM Sans", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 13.0f, radiusLg = 20.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 33,
    ),
    AnduraDesignSystem(
        id = "mintlify", name = "Mintlify", category = "Productivity & SaaS", description = "Bundled Open Design package for Mintlify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFAFAFAu, foreground = 0xFF0D0D0Du, foregroundSecondary = 0xFF333333u, muted = 0xFF666666u, border = 0x0D000000u,
        accent = 0xFF18E299u, accentOn = 0xFF0D0D0Du, success = 0xFF16A34Au, warning = 0xFFC37D0Du, danger = 0xFFD45656u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 34,
    ),
    AnduraDesignSystem(
        id = "miro", name = "Miro", category = "Design & Creative", description = "Bundled Open Design package for Miro, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF7C2u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFF3A3u, foreground = 0xFF050038u, foregroundSecondary = 0xFF322B6Bu, muted = 0xFF605A8Au, border = 0xFFDED9FFu,
        accent = 0xFFFFD02Fu, accentOn = 0xFF050038u, success = 0xFF1A7F37u, warning = 0xFFFF9F1Cu, danger = 0xFFD92D20u,
        fontDisplay = "Formular", fontBody = "Formular", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 18.0f, radiusLg = 28.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 230, containerMax = 1220.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "mission-control", name = "Mission Control Design System", category = "Developer Tools", description = "Bundled Open Design package for Mission Control Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF090B12u, surface = 0xFF121722u, surfaceWarm = 0xFF1B2233u, foreground = 0xFFF8FAFCu, foregroundSecondary = 0xFFCBD5E1u, muted = 0xFF94A3B8u, border = 0xFF2A3447u,
        accent = 0xFF60A5FAu, accentOn = 0xFF06101Du, success = 0xFF26DE81u, warning = 0xFFFBBF24u, danger = 0xFFFF4757u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 14.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 100, motionBaseMs = 180, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
)
