// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val anduraDesignSystemsChunk08 = listOf(
    AnduraDesignSystem(
        id = "voltagent", name = "VoltAgent", category = "AI & LLM", description = "Bundled Open Design package for VoltAgent, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF07110Cu, surface = 0xFF101C16u, surfaceWarm = 0xFF14281Eu, foreground = 0xFFF4FFF8u, foregroundSecondary = 0xFFC8DFD0u, muted = 0xFF8BA493u, border = 0xFF254132u,
        accent = 0xFF7CFF6Bu, accentOn = 0xFF07110Cu, success = 0xFF52E875u, warning = 0xFFFACC15u, danger = 0xFFFB7185u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 15.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 18.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 120, motionBaseMs = 210, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "warm-editorial", name = "Warm Editorial", category = "Starter", description = "Bundled Open Design package for Warm Editorial, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFBF6EEu, surface = 0xFFFFFDF8u, surfaceWarm = 0xFFF1E3CFu, foreground = 0xFF201914u, foregroundSecondary = 0xFF4C4037u, muted = 0xFF7A6D63u, border = 0xFFDED2C3u,
        accent = 0xFF9B5B32u, accentOn = 0xFFFFFFFFu, success = 0xFF4F8A4Fu, warning = 0xFFC9822Fu, danger = 0xFFB33A3Au,
        fontDisplay = "Georgia", fontBody = "Inter", textBase = 17.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "warp", name = "Warp", category = "Developer Tools", description = "Bundled Open Design package for Warp, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF161412u, surface = 0xFF1F1D1Bu, surfaceWarm = 0xFF1F1D1Bu, foreground = 0xFFFAF9F6u, foregroundSecondary = 0xFFAFAEACu, muted = 0xFF868584u, border = 0x59E2E2E2u,
        accent = 0xFF353534u, accentOn = 0xFFAFAEACu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Matter Regular", fontBody = "Matter Regular", textBase = 18.0f, radiusSm = 6.0f, radiusMd = 12.0f, radiusLg = 14.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1500.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 28,
    ),
    AnduraDesignSystem(
        id = "webex", name = "Webex", category = "Productivity & SaaS", description = "Bundled Open Design package for Webex, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF6F8FBu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEEF8F6u, foreground = 0xFF0F172Au, foregroundSecondary = 0xFF334155u, muted = 0xFF64748Bu, border = 0xFFDBE4EEu,
        accent = 0xFF00A3A6u, accentOn = 0xFFFFFFFFu, success = 0xFF22C55Eu, warning = 0xFFF59E0Bu, danger = 0xFFE11D48u,
        fontDisplay = "CiscoSansTT", fontBody = "CiscoSansTT", textBase = 16.0f, radiusSm = 12.0f, radiusMd = 18.0f, radiusLg = 28.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 160, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "webflow", name = "Webflow", category = "Design & Creative", description = "Bundled Open Design package for Webflow, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFFFFFu, foreground = 0xFF080808u, foregroundSecondary = 0xFF363636u, muted = 0xFF5A5A5Au, border = 0xFFD8D8D8u,
        accent = 0xFF146EF5u, accentOn = 0xFFFFFFFFu, success = 0xFF00D722u, warning = 0xFFFFAE13u, danger = 0xFFEE1D36u,
        fontDisplay = "WF Visual Sans Variable", fontBody = "WF Visual Sans Variable", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 4.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 28,
    ),
    AnduraDesignSystem(
        id = "wechat", name = "WeChat Design System", category = "Social & Messaging", description = "Bundled Open Design package for WeChat Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFEDEDEDu, surface = 0xFFF7F7F7u, surfaceWarm = 0xFFF7F7F7u, foreground = 0xFF1A1A1Au, foregroundSecondary = 0xFF1A1A1Au, muted = 0xFF888888u, border = 0xFFE0E0E0u,
        accent = 0xFF07C160u, accentOn = 0xFFFFFFFFu, success = 0xFF07C160u, warning = 0xFFFAB702u, danger = 0xFFFA5151u,
        fontDisplay = "-apple-system", fontBody = "-apple-system", textBase = 15.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 100, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 34,
    ),
    AnduraDesignSystem(
        id = "wired", name = "WIRED", category = "Media & Consumer", description = "Bundled Open Design package for WIRED, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF2F2F2u, surfaceWarm = 0xFFFFF0F0u, foreground = 0xFF000000u, foregroundSecondary = 0xFF333333u, muted = 0xFF666666u, border = 0xFFD0D0D0u,
        accent = 0xFFE10600u, accentOn = 0xFFFFFFFFu, success = 0xFF0F8A3Bu, warning = 0xFFF5A400u, danger = 0xFFC40000u,
        fontDisplay = "Druk Wide", fontBody = "Exchange", textBase = 17.0f, radiusSm = 0.0f, radiusMd = 0.0f, radiusLg = 0.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 120, motionBaseMs = 200, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "wise", name = "Wise", category = "Fintech & Crypto", description = "Bundled Open Design package for Wise, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFE8EBE6u, surfaceWarm = 0xFFE8EBE6u, foreground = 0xFF0E0F0Cu, foregroundSecondary = 0xFF0E0F0Cu, muted = 0xFF868685u, border = 0x1F0E0F0Cu,
        accent = 0xFF9FE870u, accentOn = 0xFF163300u, success = 0xFF054D28u, warning = 0xFFFFD11Au, danger = 0xFFD03238u,
        fontDisplay = "Wise Sans", fontBody = "Inter", textBase = 18.0f, radiusSm = 16.0f, radiusMd = 30.0f, radiusLg = 40.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 28,
    ),
    AnduraDesignSystem(
        id = "x-ai", name = "xAI", category = "AI & LLM", description = "Bundled Open Design package for xAI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF1F2228u, surface = 0x08FFFFFFu, surfaceWarm = 0x0DFFFFFFu, foreground = 0xFFFFFFFFu, foregroundSecondary = 0xB2FFFFFFu, muted = 0x80FFFFFFu, border = 0x1AFFFFFFu,
        accent = 0xFFFFFFFFu, accentOn = 0xFF1F2228u, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "GeistMono", fontBody = "universalSans", textBase = 16.0f, radiusSm = 0.0f, radiusMd = 0.0f, radiusLg = 4.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 23,
    ),
    AnduraDesignSystem(
        id = "xiaohongshu", name = "Xiaohongshu", category = "Media & Consumer", description = "Bundled Open Design package for Xiaohongshu, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF5F5F5u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFAFAFAu, foreground = 0xCC000000u, foregroundSecondary = 0x9E000000u, muted = 0x73000000u, border = 0x14000000u,
        accent = 0xFFFF2442u, accentOn = 0xFFFFFFFFu, success = 0xFF02B940u, warning = 0xFFFF7D03u, danger = 0xFFFF2442u,
        fontDisplay = "PingFang SC", fontBody = "PingFang SC", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 49,
    ),
    AnduraDesignSystem(
        id = "zapier", name = "Zapier", category = "Productivity & SaaS", description = "Bundled Open Design package for Zapier, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF7EDu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFEDD5u, foreground = 0xFF2D2A26u, foregroundSecondary = 0xFF574F45u, muted = 0xFF7C6F64u, border = 0xFFEADFD3u,
        accent = 0xFFFF4F00u, accentOn = 0xFFFFFFFFu, success = 0xFF15803Du, warning = 0xFFD97706u, danger = 0xFFDC2626u,
        fontDisplay = "Degular", fontBody = "Inter", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 20.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 140, motionBaseMs = 220, containerMax = 1160.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
)
