// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val anduraDesignSystemsChunk07 = listOf(
    AnduraDesignSystem(
        id = "spacious", name = "Spacious", category = "Layout & Structure", description = "Bundled Open Design package for Spacious, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFAF3DFu, surface = 0xFFFFFAF0u, surfaceWarm = 0xFFEFE0BDu, foreground = 0xFF211B12u, foregroundSecondary = 0xFF504737u, muted = 0xFF7C7160u, border = 0xFFDDD0B4u,
        accent = 0xFF8F5D24u, accentOn = 0xFFFFFFFFu, success = 0xFF5B8D42u, warning = 0xFFC27B22u, danger = 0xFFA64036u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 17.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "spotify", name = "Spotify", category = "Media & Consumer", description = "Bundled Open Design package for Spotify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF121212u, surface = 0xFF181818u, surfaceWarm = 0xFF1F1F1Fu, foreground = 0xFFFFFFFFu, foregroundSecondary = 0xFFFDFDFDu, muted = 0xFFB3B3B3u, border = 0xFF4D4D4Du,
        accent = 0xFF1ED760u, accentOn = 0xFF000000u, success = 0xFF1ED760u, warning = 0xFFFFA42Bu, danger = 0xFFF3727Fu,
        fontDisplay = "SpotifyMixUITitle", fontBody = "SpotifyMixUI", textBase = 16.0f, radiusSm = 9999.0f, radiusMd = 6.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "cards", "links", "icons", "typography", "layout"), sourceClassCount = 20,
    ),
    AnduraDesignSystem(
        id = "starbucks", name = "Starbucks", category = "E-Commerce & Retail", description = "Bundled Open Design package for Starbucks, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF2F0EBu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEDEBE9u, foreground = 0xDE000000u, foregroundSecondary = 0xFF33433Du, muted = 0x94000000u, border = 0xFFD6DBDEu,
        accent = 0xFF00754Au, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFFBBC05u, danger = 0xFFC82014u,
        fontDisplay = "SoDoSans", fontBody = "SoDoSans", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 12.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1440.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 30,
    ),
    AnduraDesignSystem(
        id = "storytelling", name = "Storytelling", category = "Creative & Artistic", description = "Bundled Open Design package for Storytelling, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFBF6EEu, surface = 0xFFFFFDF8u, surfaceWarm = 0xFFF1E3CFu, foreground = 0xFF201914u, foregroundSecondary = 0xFF4C4037u, muted = 0xFF7A6D63u, border = 0xFFDED2C3u,
        accent = 0xFF9B5B32u, accentOn = 0xFFFFFFFFu, success = 0xFF4F8A4Fu, warning = 0xFFC9822Fu, danger = 0xFFB33A3Au,
        fontDisplay = "Georgia", fontBody = "Inter", textBase = 17.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "stripe", name = "Stripe", category = "Fintech & Crypto", description = "Bundled Open Design package for Stripe, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFF6F9FCu, foreground = 0xFF061B31u, foregroundSecondary = 0xFF273951u, muted = 0xFF64748Du, border = 0xFFE5EDF5u,
        accent = 0xFF533AFDu, accentOn = 0xFFFFFFFFu, success = 0xFF15BE53u, warning = 0xFF9B6829u, danger = 0xFFEA2261u,
        fontDisplay = "sohne-var", fontBody = "sohne-var", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 6.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1080.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 45,
    ),
    AnduraDesignSystem(
        id = "supabase", name = "Supabase", category = "Backend & Data", description = "Bundled Open Design package for Supabase, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF171717u, surface = 0xFF1C1C1Cu, surfaceWarm = 0xFF1C1C1Cu, foreground = 0xFFFAFAFAu, foregroundSecondary = 0xFFB4B4B4u, muted = 0xFF898989u, border = 0xFF2E2E2Eu,
        accent = 0xFF3ECF8Eu, accentOn = 0xFF0F0F0Fu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Circular", fontBody = "Circular", textBase = 16.0f, radiusSm = 6.0f, radiusMd = 8.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 30,
    ),
    AnduraDesignSystem(
        id = "superhuman", name = "Superhuman", category = "Developer Tools", description = "Bundled Open Design package for Superhuman, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFE9E5DDu, foreground = 0xFF292827u, foregroundSecondary = 0xFF292827u, muted = 0xFF6F6C69u, border = 0xFFDCD7D3u,
        accent = 0xFFCBB7FBu, accentOn = 0xFF292827u, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Super Sans VF", fontBody = "Super Sans VF", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 8.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 31,
    ),
    AnduraDesignSystem(
        id = "tesla", name = "Tesla", category = "Automotive", description = "Bundled Open Design package for Tesla, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF4F4F4u, surfaceWarm = 0xFFF4F4F4u, foreground = 0xFF171A20u, foregroundSecondary = 0xFF393C41u, muted = 0xFF5C5E62u, border = 0xFFD0D1D2u,
        accent = 0xFF3E6AE1u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Universal Sans Display", fontBody = "Universal Sans Text", textBase = 14.0f, radiusSm = 4.0f, radiusMd = 12.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 250, motionBaseMs = 330, containerMax = 1383.0f, componentGroups = listOf("buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 37,
    ),
    AnduraDesignSystem(
        id = "tetris", name = "Tetris", category = "Themed & Unique", description = "Bundled Open Design package for Tetris, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF050816u, surface = 0xFF10162Au, surfaceWarm = 0xFF17203Au, foreground = 0xFFF8FAFCu, foregroundSecondary = 0xFFCBD5E1u, muted = 0xFF94A3B8u, border = 0xFF26324Fu,
        accent = 0xFF00F0F0u, accentOn = 0xFF061018u, success = 0xFF00F000u, warning = 0xFFF0F000u, danger = 0xFFF00000u,
        fontDisplay = "Press Start 2P", fontBody = "Inter", textBase = 14.0f, radiusSm = 0.0f, radiusMd = 0.0f, radiusLg = 4.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 80, motionBaseMs = 140, containerMax = 1100.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "theverge", name = "The Verge", category = "Media & Consumer", description = "Bundled Open Design package for The Verge, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF050505u, surface = 0xFF111111u, surfaceWarm = 0xFF211022u, foreground = 0xFFFFFFFFu, foregroundSecondary = 0xFFE5E7EBu, muted = 0xFF9CA3AFu, border = 0xFF2B2B2Bu,
        accent = 0xFFFF00A8u, accentOn = 0xFFFFFFFFu, success = 0xFF22C55Eu, warning = 0xFFFACC15u, danger = 0xFFEF4444u,
        fontDisplay = "PolySans", fontBody = "Inter", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 120, motionBaseMs = 200, containerMax = 1240.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "together-ai", name = "Together AI", category = "AI & LLM", description = "Bundled Open Design package for Together AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFFFFFu, foreground = 0xFF000000u, foregroundSecondary = 0x99000000u, muted = 0xFF666666u, border = 0xFFEBEBEBu,
        accent = 0xFF010120u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "The Future", fontBody = "The Future", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"), sourceClassCount = 25,
    ),
    AnduraDesignSystem(
        id = "tom-modern", name = "Tom Modern Design", category = "Starter", description = "Editorial-technical design system. Neutral canvas, single vermillion accent, sharp corners, Geist typography, hard shadows, structured composition.", nativeDark = false,
        background = 0xFFFAFAFAu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFFFFFu, foreground = 0xFF27272Au, foregroundSecondary = 0xFF52525Bu, muted = 0xFF71717Au, border = 0xFF969696u,
        accent = 0xFFFF5A00u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Geist Sans", fontBody = "Geist Sans", textBase = 15.0f, radiusSm = 0.0f, radiusMd = 0.0f, radiusLg = 0.0f, radiusPill = 0.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1240.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 0,
    ),
    AnduraDesignSystem(
        id = "totality-festival", name = "Totality Festival", category = "Themed & Unique", description = "Bundled Open Design package for Totality Festival, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF070711u, surface = 0xFF111126u, surfaceWarm = 0xFF1E1540u, foreground = 0xFFF8F7FFu, foregroundSecondary = 0xFFD6CCFFu, muted = 0xFF9D8AD4u, border = 0xFF34265Eu,
        accent = 0xFFC084FCu, accentOn = 0xFF13051Fu, success = 0xFF39FF88u, warning = 0xFFFFF34Du, danger = 0xFFFF4D8Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "trading-terminal", name = "Trading Terminal Design System", category = "Themed & Unique", description = "Bundled Open Design package for Trading Terminal Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF070B12u, surface = 0xFF101826u, surfaceWarm = 0xFF162238u, foreground = 0xFFF8FAFCu, foregroundSecondary = 0xFFCBD5E1u, muted = 0xFF8492A6u, border = 0xFF263246u,
        accent = 0xFF38BDF8u, accentOn = 0xFF03111Au, success = 0xFF22C55Eu, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 14.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 90, motionBaseMs = 160, containerMax = 1320.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "uber", name = "Uber", category = "Media & Consumer", description = "Bundled Open Design package for Uber, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFF8F8F8u, foreground = 0xFF000000u, foregroundSecondary = 0xFF000000u, muted = 0xFF4B4B4Bu, border = 0xFF000000u,
        accent = 0xFF000000u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "UberMove", fontBody = "UberMoveText", textBase = 16.0f, radiusSm = 999.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1136.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"), sourceClassCount = 19,
    ),
    AnduraDesignSystem(
        id = "urdu", name = "Urdu Modern (Indus Script System)", category = "Editorial / Personal / Publication", description = "Bundled Open Design package for Urdu Modern (Indus Script System), derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF3FAF4u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFE5F5E7u, foreground = 0xFF15261Au, foregroundSecondary = 0xFF38513Eu, muted = 0xFF6B7D70u, border = 0xFFD4E3D7u,
        accent = 0xFF1F8F46u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFD97706u, danger = 0xFFDC2626u,
        fontDisplay = "Georgia", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "vercel", name = "Vercel", category = "Developer Tools", description = "Bundled Open Design package for Vercel, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFFFFFu, foreground = 0xFF171717u, foregroundSecondary = 0xFF4D4D4Du, muted = 0xFF666666u, border = 0x14000000u,
        accent = 0xFF0070F3u, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Geist", fontBody = "Geist", textBase = 16.0f, radiusSm = 6.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 38,
    ),
    AnduraDesignSystem(
        id = "vibrant", name = "Vibrant", category = "Bold & Expressive", description = "Bundled Open Design package for Vibrant, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF8D7u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFEF9Fu, foreground = 0xFF1D1836u, foregroundSecondary = 0xFF4C426Cu, muted = 0xFF796F91u, border = 0xFFEADFBAu,
        accent = 0xFFFF6B00u, accentOn = 0xFFFFFFFFu, success = 0xFF2E9D57u, warning = 0xFFFFB020u, danger = 0xFFE5484Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "vintage", name = "Vintage", category = "Retro & Nostalgic", description = "Bundled Open Design package for Vintage, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFAF3DFu, surface = 0xFFFFFAF0u, surfaceWarm = 0xFFEFE0BDu, foreground = 0xFF211B12u, foregroundSecondary = 0xFF504737u, muted = 0xFF7C7160u, border = 0xFFDDD0B4u,
        accent = 0xFF8F5D24u, accentOn = 0xFFFFFFFFu, success = 0xFF5B8D42u, warning = 0xFFC27B22u, danger = 0xFFA64036u,
        fontDisplay = "Georgia", fontBody = "Inter", textBase = 17.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "vodafone", name = "Vodafone", category = "Media & Consumer", description = "Bundled Open Design package for Vodafone, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF4F4F4u, surfaceWarm = 0xFFFFF1F1u, foreground = 0xFF1F1F1Fu, foregroundSecondary = 0xFF4A4D4Eu, muted = 0xFF6F7375u, border = 0xFFD8D8D8u,
        accent = 0xFFE60000u, accentOn = 0xFFFFFFFFu, success = 0xFF008A00u, warning = 0xFFF5B400u, danger = 0xFFBD0000u,
        fontDisplay = "Vodafone", fontBody = "Vodafone", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 220, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
)
