// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val anduraDesignSystemsChunk02 = listOf(
    AnduraDesignSystem(
        id = "claude", name = "Claude (Anthropic)", category = "AI & LLM", description = "Bundled Open Design package for Claude (Anthropic), derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF5F4EDu, surface = 0xFFFAF9F5u, surfaceWarm = 0xFFE8E6DCu, foreground = 0xFF141413u, foregroundSecondary = 0xFF3D3D3Au, muted = 0xFF5E5D59u, border = 0xFFF0EEE6u,
        accent = 0xFFC96442u, accentOn = 0xFFFAF9F5u, success = 0xFF17A34Au, warning = 0xFFEAB308u, danger = 0xFFB53333u,
        fontDisplay = "Anthropic Serif", fontBody = "Anthropic Sans", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 25,
    ),
    AnduraDesignSystem(
        id = "clay", name = "Clay", category = "Design & Creative", description = "Bundled Open Design package for Clay, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF7EEE6u, surface = 0xFFFFF8F1u, surfaceWarm = 0xFFEAD6C7u, foreground = 0xFF2B211Cu, foregroundSecondary = 0xFF5A4B43u, muted = 0xFF8A7A70u, border = 0xFFDAC8B9u,
        accent = 0xFFB46A46u, accentOn = 0xFFFFFFFFu, success = 0xFF4D8F5Au, warning = 0xFFC88735u, danger = 0xFFB84C4Cu,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 14.0f, radiusMd = 22.0f, radiusLg = 34.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "claymorphism", name = "Claymorphism", category = "Morphism & Effects", description = "Bundled Open Design package for Claymorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF7EEE6u, surface = 0xFFFFF8F1u, surfaceWarm = 0xFFEAD6C7u, foreground = 0xFF2B211Cu, foregroundSecondary = 0xFF5A4B43u, muted = 0xFF8A7A70u, border = 0xFFDAC8B9u,
        accent = 0xFFB46A46u, accentOn = 0xFFFFFFFFu, success = 0xFF4D8F5Au, warning = 0xFFC88735u, danger = 0xFFB84C4Cu,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 14.0f, radiusMd = 22.0f, radiusLg = 34.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "clean", name = "Clean", category = "Modern & Minimal", description = "Bundled Open Design package for Clean, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFF7F7F7u, surfaceWarm = 0xFFEEEEEEu, foreground = 0xFF111111u, foregroundSecondary = 0xFF3A3A3Au, muted = 0xFF707070u, border = 0xFFD9D9D9u,
        accent = 0xFF111111u, accentOn = 0xFFFFFFFFu, success = 0xFF168A46u, warning = 0xFFB7791Fu, danger = 0xFFC53030u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "clickhouse", name = "ClickHouse", category = "Backend & Data", description = "Bundled Open Design package for ClickHouse, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF000000u, surface = 0xFF141414u, surfaceWarm = 0xFF141414u, foreground = 0xFFFFFFFFu, foregroundSecondary = 0xFFA0A0A0u, muted = 0xFFA0A0A0u, border = 0xCC414141u,
        accent = 0xFFFAFF69u, accentOn = 0xFF151515u, success = 0xFF166534u, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 8.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 38,
    ),
    AnduraDesignSystem(
        id = "cohere", name = "Cohere", category = "AI & LLM", description = "Bundled Open Design package for Cohere, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFFAFAFAu, surfaceWarm = 0xFFFAFAFAu, foreground = 0xFF000000u, foregroundSecondary = 0xFF212121u, muted = 0xFF93939Fu, border = 0xFFD9D9DDu,
        accent = 0xFF1863DCu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFEF4444u,
        fontDisplay = "CohereText", fontBody = "Unica77 Cohere Web", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 22.0f, radiusLg = 22.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1440.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 25,
    ),
    AnduraDesignSystem(
        id = "coinbase", name = "Coinbase", category = "Fintech & Crypto", description = "Bundled Open Design package for Coinbase, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFFFFFu, surface = 0xFFEEF0F3u, surfaceWarm = 0xFFEEF0F3u, foreground = 0xFF0A0B0Du, foregroundSecondary = 0xFF0A0B0Du, muted = 0xFF5B616Eu, border = 0x335B616Eu,
        accent = 0xFF0052FFu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "CoinbaseDisplay", fontBody = "CoinbaseText", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 16.0f, radiusLg = 32.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 40,
    ),
    AnduraDesignSystem(
        id = "colorful", name = "Colorful", category = "Bold & Expressive", description = "Bundled Open Design package for Colorful, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF8D7u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFEF9Fu, foreground = 0xFF1D1836u, foregroundSecondary = 0xFF4C426Cu, muted = 0xFF796F91u, border = 0xFFEADFBAu,
        accent = 0xFFFF6B00u, accentOn = 0xFFFFFFFFu, success = 0xFF2E9D57u, warning = 0xFFFFB020u, danger = 0xFFE5484Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "composio", name = "Composio", category = "Backend & Data", description = "Bundled Open Design package for Composio, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF090B14u, surface = 0xFF121626u, surfaceWarm = 0xFF1B2140u, foreground = 0xFFF8FAFCu, foregroundSecondary = 0xFFCBD5E1u, muted = 0xFF94A3B8u, border = 0xFF27324Au,
        accent = 0xFF6D5DFCu, accentOn = 0xFFFFFFFFu, success = 0xFF22C55Eu, warning = 0xFFFBBF24u, danger = 0xFFFB7185u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 15.0f, radiusSm = 10.0f, radiusMd = 14.0f, radiusLg = 22.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 140, motionBaseMs = 220, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "contemporary", name = "Contemporary", category = "Modern & Minimal", description = "Bundled Open Design package for Contemporary, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF5F8FFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEAF1FFu, foreground = 0xFF101828u, foregroundSecondary = 0xFF344054u, muted = 0xFF667085u, border = 0xFFD7E0EFu,
        accent = 0xFF2563EBu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "corporate", name = "Corporate", category = "Professional & Corporate", description = "Bundled Open Design package for Corporate, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF5F8FFu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEAF1FFu, foreground = 0xFF101828u, foregroundSecondary = 0xFF344054u, muted = 0xFF667085u, border = 0xFFD7E0EFu,
        accent = 0xFF2563EBu, accentOn = 0xFFFFFFFFu, success = 0xFF16A34Au, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "cosmic", name = "Cosmic", category = "Creative & Artistic", description = "Bundled Open Design package for Cosmic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF070711u, surface = 0xFF111126u, surfaceWarm = 0xFF1E1540u, foreground = 0xFFF8F7FFu, foregroundSecondary = 0xFFD6CCFFu, muted = 0xFF9D8AD4u, border = 0xFF34265Eu,
        accent = 0xFFC084FCu, accentOn = 0xFF13051Fu, success = 0xFF39FF88u, warning = 0xFFFFF34Du, danger = 0xFFFF4D8Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "creative", name = "Creative", category = "Creative & Artistic", description = "Bundled Open Design package for Creative, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF8D7u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFEF9Fu, foreground = 0xFF1D1836u, foregroundSecondary = 0xFF4C426Cu, muted = 0xFF796F91u, border = 0xFFEADFBAu,
        accent = 0xFFFF6B00u, accentOn = 0xFFFFFFFFu, success = 0xFF2E9D57u, warning = 0xFFFFB020u, danger = 0xFFE5484Du,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "cursor", name = "Cursor", category = "Developer Tools", description = "Bundled Open Design package for Cursor, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF2F1EDu, surface = 0xFFE6E5E0u, surfaceWarm = 0xFFEBEAE5u, foreground = 0xFF26251Eu, foregroundSecondary = 0xE626251Eu, muted = 0x8C26251Eu, border = 0x1A26251Eu,
        accent = 0xFFF54E00u, accentOn = 0xFFFFFFFFu, success = 0xFF1F8A65u, warning = 0xFFEAB308u, danger = 0xFFCF2D56u,
        fontDisplay = "CursorGothic", fontBody = "jjannon", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 10.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 37,
    ),
    AnduraDesignSystem(
        id = "dashboard", name = "Dashboard", category = "Professional & Corporate", description = "Bundled Open Design package for Dashboard, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFF4F7FBu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFEEF6FFu, foreground = 0xFF111827u, foregroundSecondary = 0xFF334155u, muted = 0xFF64748Bu, border = 0xFFD8E2EEu,
        accent = 0xFF0EA5E9u, accentOn = 0xFF04131Du, success = 0xFF10B981u, warning = 0xFFF59E0Bu, danger = 0xFFEF4444u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 15.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 18.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 120, motionBaseMs = 200, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "default", name = "Neutral Modern", category = "Starter", description = "Bundled Open Design package for Neutral Modern, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFAFAFAu, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFFFFFu, foreground = 0xFF111111u, foregroundSecondary = 0xFF111111u, muted = 0xFF6B6B6Bu, border = 0xFFE5E5E5u,
        accent = 0xFF2F6FEBu, accentOn = 0xFFFFFFFFu, success = 0xFF17A34Au, warning = 0xFFEAB308u, danger = 0xFFDC2626u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 8.0f, radiusMd = 12.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"), sourceClassCount = 25,
    ),
    AnduraDesignSystem(
        id = "discord", name = "Discord", category = "Productivity & SaaS", description = "Bundled Open Design package for Discord, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF313338u, surface = 0xFF2B2D31u, surfaceWarm = 0xFF1E1F22u, foreground = 0xFFDBDEE1u, foregroundSecondary = 0xFFF2F3F5u, muted = 0xFF949BA4u, border = 0x0FFFFFFFu,
        accent = 0xFF5865F2u, accentOn = 0xFFFFFFFFu, success = 0xFF23A55Au, warning = 0xFFF0B232u, danger = 0xFFF23F43u,
        fontDisplay = "gg sans", fontBody = "gg sans", textBase = 16.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 16.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 80, motionBaseMs = 200, containerMax = 1200.0f, componentGroups = listOf("buttons", "inputs", "cards", "links", "typography", "layout"), sourceClassCount = 17,
    ),
    AnduraDesignSystem(
        id = "dithered", name = "Dithered", category = "Retro & Nostalgic", description = "Bundled Open Design package for Dithered, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF4CFu, surface = 0xFFFFFAF0u, surfaceWarm = 0xFFFFDCA8u, foreground = 0xFF2A1810u, foregroundSecondary = 0xFF593625u, muted = 0xFF8A6652u, border = 0xFFD9AA7Au,
        accent = 0xFFD24B1Fu, accentOn = 0xFFFFFFFFu, success = 0xFF3D8F4Fu, warning = 0xFFF2A93Bu, danger = 0xFFB83A2Fu,
        fontDisplay = "Courier New", fontBody = "Inter", textBase = 14.0f, radiusSm = 4.0f, radiusMd = 8.0f, radiusLg = 12.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 100, motionBaseMs = 180, containerMax = 1280.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "doodle", name = "Doodle", category = "Creative & Artistic", description = "Bundled Open Design package for Doodle, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = false,
        background = 0xFFFFF8D7u, surface = 0xFFFFFFFFu, surfaceWarm = 0xFFFFEF9Fu, foreground = 0xFF1D1836u, foregroundSecondary = 0xFF4C426Cu, muted = 0xFF796F91u, border = 0xFFEADFBAu,
        accent = 0xFFFF6B00u, accentOn = 0xFFFFFFFFu, success = 0xFF2E9D57u, warning = 0xFFFFB020u, danger = 0xFFE5484Du,
        fontDisplay = "Comic Sans MS", fontBody = "Comic Sans MS", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
    AnduraDesignSystem(
        id = "dramatic", name = "Dramatic", category = "Bold & Expressive", description = "Bundled Open Design package for Dramatic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", nativeDark = true,
        background = 0xFF090B12u, surface = 0xFF121722u, surfaceWarm = 0xFF1B2233u, foreground = 0xFFF8FAFCu, foregroundSecondary = 0xFFCBD5E1u, muted = 0xFF94A3B8u, border = 0xFF2A3447u,
        accent = 0xFF60A5FAu, accentOn = 0xFF06101Du, success = 0xFF22C55Eu, warning = 0xFFFBBF24u, danger = 0xFFFB7185u,
        fontDisplay = "Inter", fontBody = "Inter", textBase = 16.0f, radiusSm = 10.0f, radiusMd = 16.0f, radiusLg = 24.0f, radiusPill = 9999.0f,
        space1 = 4.0f, space2 = 8.0f, space3 = 12.0f, space4 = 16.0f, space6 = 24.0f, space8 = 32.0f,
        motionFastMs = 150, motionBaseMs = 240, containerMax = 1180.0f, componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"), sourceClassCount = 26,
    ),
)
