// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val antDesignSystem = AnduraDesignSystem(
    id = "ant",
    name = "Ant",
    category = "Professional & Corporate",
    description = "Bundled Open Design package for Ant, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF7F8FAu,
    surfaceWarm = 0xFFFFF1F0u,
    foreground = 0xFF1F1F1Fu,
    foregroundSecondary = 0xFF4B5563u,
    muted = 0xFF697386u,
    border = 0xFFD9DCE3u,
    accent = 0xFFD32029u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF22A06Bu,
    warning = 0xFFFAAD14u,
    danger = 0xFFCF1322u,
    fontDisplay = "Ant Sans",
    fontBody = "Ant Sans",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 10.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 140,
    motionBaseMs = 220,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
