// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val appleDesignSystem = AnduraDesignSystem(
    id = "apple",
    name = "Apple",
    category = "Media & Consumer",
    description = "Bundled Open Design package for Apple, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF5F5F7u,
    surfaceWarm = 0xFFFBFBFDu,
    foreground = 0xFF1D1D1Fu,
    foregroundSecondary = 0xFF424245u,
    muted = 0xFF6E6E73u,
    border = 0xFFD2D2D7u,
    accent = 0xFF0071E3u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "SF Pro Display",
    fontBody = "SF Pro Text",
    textBase = 17.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 18.0f,
    radiusPill = 980.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 220,
    containerMax = 1024.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 35,
)
