// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val applicationDesignSystem = AnduraDesignSystem(
    id = "application",
    name = "Application",
    category = "Professional & Corporate",
    description = "Bundled Open Design package for Application, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF6F7F9u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEEF4FFu,
    foreground = 0xFF172033u,
    foregroundSecondary = 0xFF3B4658u,
    muted = 0xFF6B7689u,
    border = 0xFFD8DEE8u,
    accent = 0xFF2563EBu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFF59E0Bu,
    danger = 0xFFDC2626u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 18.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 140,
    motionBaseMs = 220,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
