// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val arcDesignSystem = AnduraDesignSystem(
    id = "arc",
    name = "Arc Browser",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Arc Browser, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFDF3ECu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFF4EAu,
    foreground = 0xFF1A1A1Fu,
    foregroundSecondary = 0xFF54545Au,
    muted = 0xFF8C8C93u,
    border = 0xFFECE5DBu,
    accent = 0xFFFF5F5Fu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF48BB78u,
    warning = 0xFFF6AD55u,
    danger = 0xFFF56565u,
    fontDisplay = "Argent CF",
    fontBody = "Inter",
    textBase = 15.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 200,
    motionBaseMs = 320,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 27,
)
