// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val bentoDesignSystem = AnduraDesignSystem(
    id = "bento",
    name = "Bento",
    category = "Layout & Structure",
    description = "Bundled Open Design package for Bento, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF5F8FFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEAF1FFu,
    foreground = 0xFF101828u,
    foregroundSecondary = 0xFF344054u,
    muted = 0xFF667085u,
    border = 0xFFD7E0EFu,
    accent = 0xFF2563EBu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFF59E0Bu,
    danger = 0xFFEF4444u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
