// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val binanceDesignSystem = AnduraDesignSystem(
    id = "binance",
    name = "Binance.US",
    category = "Fintech & Crypto",
    description = "Bundled Open Design package for Binance.US, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFF5F5F5u,
    foreground = 0xFF1E2026u,
    foregroundSecondary = 0xFF32313Au,
    muted = 0xFF848E9Cu,
    border = 0xFFE6E8EAu,
    accent = 0xFFF0B90Bu,
    accentOn = 0xFF1E2026u,
    success = 0xFF0ECB81u,
    warning = 0xFFEAB308u,
    danger = 0xFFF6465Du,
    fontDisplay = "BinancePlex",
    fontBody = "BinancePlex",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 46,
)
