// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val bmwDesignSystem = AnduraDesignSystem(
    id = "bmw",
    name = "BMW",
    category = "Automotive",
    description = "Bundled Open Design package for BMW, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF5F5F5u,
    surfaceWarm = 0xFFF5F5F5u,
    foreground = 0xFF262626u,
    foregroundSecondary = 0xFF262626u,
    muted = 0xFF757575u,
    border = 0xFFE0E0E0u,
    accent = 0xFF1C69D4u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "BMWTypeNextLatin Light",
    fontBody = "BMWTypeNextLatin",
    textBase = 16.0f,
    radiusSm = 0.0f,
    radiusMd = 0.0f,
    radiusLg = 0.0f,
    radiusPill = 0.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1440.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"),
    sourceClassCount = 28,
)
