// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val bmwMDesignSystem = AnduraDesignSystem(
    id = "bmw-m",
    name = "BMW M",
    category = "Automotive",
    description = "Bundled Open Design package for BMW M, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF7F8FAu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEEF3F8u,
    foreground = 0xFF111827u,
    foregroundSecondary = 0xFF334155u,
    muted = 0xFF64748Bu,
    border = 0xFFD7DEE8u,
    accent = 0xFF0066B1u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFF59E0Bu,
    danger = 0xFFE4002Bu,
    fontDisplay = "BMWTypeNext",
    fontBody = "BMWTypeNext",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 14.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 130,
    motionBaseMs = 220,
    containerMax = 1220.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
