// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val brutalismDesignSystem = AnduraDesignSystem(
    id = "brutalism",
    name = "Brutalism",
    category = "Bold & Expressive",
    description = "Bundled Open Design package for Brutalism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF5F1E8u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFEF5Au,
    foreground = 0xFF000000u,
    foregroundSecondary = 0xFF222222u,
    muted = 0xFF555555u,
    border = 0xFF000000u,
    accent = 0xFFFFEF5Au,
    accentOn = 0xFF000000u,
    success = 0xFF00B050u,
    warning = 0xFFFF8C00u,
    danger = 0xFFFF2B2Bu,
    fontDisplay = "Arial Black",
    fontBody = "Arial",
    textBase = 17.0f,
    radiusSm = 0.0f,
    radiusMd = 0.0f,
    radiusLg = 0.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 90,
    motionBaseMs = 140,
    containerMax = 1160.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
