// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val bugattiDesignSystem = AnduraDesignSystem(
    id = "bugatti",
    name = "Bugatti",
    category = "Automotive",
    description = "Bundled Open Design package for Bugatti, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF07111Fu,
    surface = 0xFF101D2Fu,
    surfaceWarm = 0xFF16283Fu,
    foreground = 0xFFF7FBFFu,
    foregroundSecondary = 0xFFD6E0EEu,
    muted = 0xFF8FA1B7u,
    border = 0xFF2C405Cu,
    accent = 0xFF1B4D8Fu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF2FBF71u,
    warning = 0xFFD9B45Fu,
    danger = 0xFFC1121Fu,
    fontDisplay = "Bugatti Display",
    fontBody = "Avenir Next",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 14.0f,
    radiusLg = 22.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 170,
    motionBaseMs = 280,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
