// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val canvaDesignSystem = AnduraDesignSystem(
    id = "canva",
    name = "Canva",
    category = "Design & Creative",
    description = "Bundled Open Design package for Canva, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF4F5F7u,
    surfaceWarm = 0xFFF4F5F7u,
    foreground = 0xFF0E1318u,
    foregroundSecondary = 0xFF3C4043u,
    muted = 0xFF5F6368u,
    border = 0xFFE1E3E6u,
    accent = 0xFF7D2AE8u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF00B894u,
    warning = 0xFFFFB020u,
    danger = 0xFFFF5757u,
    fontDisplay = "Canva Sans",
    fontBody = "Canva Sans",
    textBase = 14.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 180,
    motionBaseMs = 280,
    containerMax = 1320.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 32,
)
