// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val ciscoDesignSystem = AnduraDesignSystem(
    id = "cisco",
    name = "Cisco",
    category = "Backend & Data",
    description = "Bundled Open Design package for Cisco, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF0F1720u,
    surface = 0xFF1B2530u,
    surfaceWarm = 0xFF243447u,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFE8EBF1u,
    muted = 0xFF9E9EA2u,
    border = 0xFF58585Bu,
    accent = 0xFF049FD9u,
    accentOn = 0xFF001923u,
    success = 0xFF6CC04Au,
    warning = 0xFFFFCC00u,
    danger = 0xFFCF2030u,
    fontDisplay = "CiscoSansTT",
    fontBody = "CiscoSansTT",
    textBase = 16.0f,
    radiusSm = 12.0f,
    radiusMd = 20.0f,
    radiusLg = 28.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 160,
    motionBaseMs = 240,
    containerMax = 1240.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
