// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val claudeDesignSystem = AnduraDesignSystem(
    id = "claude",
    name = "Claude (Anthropic)",
    category = "AI & LLM",
    description = "Bundled Open Design package for Claude (Anthropic), derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF5F4EDu,
    surface = 0xFFFAF9F5u,
    surfaceWarm = 0xFFE8E6DCu,
    foreground = 0xFF141413u,
    foregroundSecondary = 0xFF3D3D3Au,
    muted = 0xFF5E5D59u,
    border = 0xFFF0EEE6u,
    accent = 0xFFC96442u,
    accentOn = 0xFFFAF9F5u,
    success = 0xFF17A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFB53333u,
    fontDisplay = "Anthropic Serif",
    fontBody = "Anthropic Sans",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 25,
)
