// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val clickhouseDesignSystem = AnduraDesignSystem(
    id = "clickhouse",
    name = "ClickHouse",
    category = "Backend & Data",
    description = "Bundled Open Design package for ClickHouse, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF000000u,
    surface = 0xFF141414u,
    surfaceWarm = 0xFF141414u,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFA0A0A0u,
    muted = 0xFFA0A0A0u,
    border = 0xCC414141u,
    accent = 0xFFFAFF69u,
    accentOn = 0xFF151515u,
    success = 0xFF166534u,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 38,
)
