// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val cohereDesignSystem = AnduraDesignSystem(
    id = "cohere",
    name = "Cohere",
    category = "AI & LLM",
    description = "Bundled Open Design package for Cohere, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFAFAFAu,
    surfaceWarm = 0xFFFAFAFAu,
    foreground = 0xFF000000u,
    foregroundSecondary = 0xFF212121u,
    muted = 0xFF93939Fu,
    border = 0xFFD9D9DDu,
    accent = 0xFF1863DCu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFEF4444u,
    fontDisplay = "CohereText",
    fontBody = "Unica77 Cohere Web",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 22.0f,
    radiusLg = 22.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1440.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 25,
)
