// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val coinbaseDesignSystem = AnduraDesignSystem(
    id = "coinbase",
    name = "Coinbase",
    category = "Fintech & Crypto",
    description = "Bundled Open Design package for Coinbase, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFEEF0F3u,
    surfaceWarm = 0xFFEEF0F3u,
    foreground = 0xFF0A0B0Du,
    foregroundSecondary = 0xFF0A0B0Du,
    muted = 0xFF5B616Eu,
    border = 0x335B616Eu,
    accent = 0xFF0052FFu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "CoinbaseDisplay",
    fontBody = "CoinbaseText",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 16.0f,
    radiusLg = 32.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 40,
)
