// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val colorfulDesignSystem = AnduraDesignSystem(
    id = "colorful",
    name = "Colorful",
    category = "Bold & Expressive",
    description = "Bundled Open Design package for Colorful, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFF8D7u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFEF9Fu,
    foreground = 0xFF1D1836u,
    foregroundSecondary = 0xFF4C426Cu,
    muted = 0xFF796F91u,
    border = 0xFFEADFBAu,
    accent = 0xFFFF6B00u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF2E9D57u,
    warning = 0xFFFFB020u,
    danger = 0xFFE5484Du,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
