// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val composioDesignSystem = AnduraDesignSystem(
    id = "composio",
    name = "Composio",
    category = "Backend & Data",
    description = "Bundled Open Design package for Composio, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF090B14u,
    surface = 0xFF121626u,
    surfaceWarm = 0xFF1B2140u,
    foreground = 0xFFF8FAFCu,
    foregroundSecondary = 0xFFCBD5E1u,
    muted = 0xFF94A3B8u,
    border = 0xFF27324Au,
    accent = 0xFF6D5DFCu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF22C55Eu,
    warning = 0xFFFBBF24u,
    danger = 0xFFFB7185u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 15.0f,
    radiusSm = 10.0f,
    radiusMd = 14.0f,
    radiusLg = 22.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 140,
    motionBaseMs = 220,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
