// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val cursorDesignSystem = AnduraDesignSystem(
    id = "cursor",
    name = "Cursor",
    category = "Developer Tools",
    description = "Bundled Open Design package for Cursor, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF2F1EDu,
    surface = 0xFFE6E5E0u,
    surfaceWarm = 0xFFEBEAE5u,
    foreground = 0xFF26251Eu,
    foregroundSecondary = 0xE626251Eu,
    muted = 0x8C26251Eu,
    border = 0x1A26251Eu,
    accent = 0xFFF54E00u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF1F8A65u,
    warning = 0xFFEAB308u,
    danger = 0xFFCF2D56u,
    fontDisplay = "CursorGothic",
    fontBody = "jjannon",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 10.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 37,
)
