// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val dashboardDesignSystem = AnduraDesignSystem(
    id = "dashboard",
    name = "Dashboard",
    category = "Professional & Corporate",
    description = "Bundled Open Design package for Dashboard, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF4F7FBu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEEF6FFu,
    foreground = 0xFF111827u,
    foregroundSecondary = 0xFF334155u,
    muted = 0xFF64748Bu,
    border = 0xFFD8E2EEu,
    accent = 0xFF0EA5E9u,
    accentOn = 0xFF04131Du,
    success = 0xFF10B981u,
    warning = 0xFFF59E0Bu,
    danger = 0xFFEF4444u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 15.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 18.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
