// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val defaultDesignSystem = AnduraDesignSystem(
    id = "default",
    name = "Neutral Modern",
    category = "Starter",
    description = "Bundled Open Design package for Neutral Modern, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFAFAFAu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFFFFFu,
    foreground = 0xFF111111u,
    foregroundSecondary = 0xFF111111u,
    muted = 0xFF6B6B6Bu,
    border = 0xFFE5E5E5u,
    accent = 0xFF2F6FEBu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF17A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 25,
)
