// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val discordDesignSystem = AnduraDesignSystem(
    id = "discord",
    name = "Discord",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Discord, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF313338u,
    surface = 0xFF2B2D31u,
    surfaceWarm = 0xFF1E1F22u,
    foreground = 0xFFDBDEE1u,
    foregroundSecondary = 0xFFF2F3F5u,
    muted = 0xFF949BA4u,
    border = 0x0FFFFFFFu,
    accent = 0xFF5865F2u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF23A55Au,
    warning = 0xFFF0B232u,
    danger = 0xFFF23F43u,
    fontDisplay = "gg sans",
    fontBody = "gg sans",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 80,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "links", "typography", "layout"),
    sourceClassCount = 17,
)
