// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val duolingoDesignSystem = AnduraDesignSystem(
    id = "duolingo",
    name = "Duolingo",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Duolingo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF7F7F7u,
    surfaceWarm = 0xFFF7F7F7u,
    foreground = 0xFF3C3C3Cu,
    foregroundSecondary = 0xFF3C3C3Cu,
    muted = 0xFF777777u,
    border = 0xFFE5E5E5u,
    accent = 0xFF58CC02u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF58CC02u,
    warning = 0xFFFFC800u,
    danger = 0xFFFF4B4Bu,
    fontDisplay = "Feather Bold",
    fontBody = "Mona Sans",
    textBase = 15.0f,
    radiusSm = 12.0f,
    radiusMd = 16.0f,
    radiusLg = 20.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 180,
    motionBaseMs = 320,
    containerMax = 1080.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 36,
)
