// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val editorialDesignSystem = AnduraDesignSystem(
    id = "editorial",
    name = "Editorial",
    category = "Creative & Artistic",
    description = "Bundled Open Design package for Editorial, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFBF7F0u,
    surface = 0xFFFFFDF8u,
    surfaceWarm = 0xFFF1E6D6u,
    foreground = 0xFF1F1A16u,
    foregroundSecondary = 0xFF4B4038u,
    muted = 0xFF7D7168u,
    border = 0xFFDED3C5u,
    accent = 0xFF9A5A2Fu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF4F8A4Fu,
    warning = 0xFFC9822Fu,
    danger = 0xFFB33A3Au,
    fontDisplay = "Georgia",
    fontBody = "Source Serif Pro",
    textBase = 18.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 180,
    motionBaseMs = 280,
    containerMax = 1120.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
