// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val elegantDesignSystem = AnduraDesignSystem(
    id = "elegant",
    name = "Elegant",
    category = "Professional & Corporate",
    description = "Bundled Open Design package for Elegant, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFBF6EEu,
    surface = 0xFFFFFDF8u,
    surfaceWarm = 0xFFF1E3CFu,
    foreground = 0xFF201914u,
    foregroundSecondary = 0xFF4C4037u,
    muted = 0xFF7A6D63u,
    border = 0xFFDED2C3u,
    accent = 0xFF9B5B32u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF4F8A4Fu,
    warning = 0xFFC9822Fu,
    danger = 0xFFB33A3Au,
    fontDisplay = "Georgia",
    fontBody = "Inter",
    textBase = 17.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
