// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val elevenlabsDesignSystem = AnduraDesignSystem(
    id = "elevenlabs",
    name = "ElevenLabs",
    category = "AI & LLM",
    description = "Bundled Open Design package for ElevenLabs, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF5F5F5u,
    surfaceWarm = 0xFFF5F2EFu,
    foreground = 0xFF000000u,
    foregroundSecondary = 0xFF4E4E4Eu,
    muted = 0xFF777169u,
    border = 0xFFE5E5E5u,
    accent = 0xFF000000u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Waldenburg",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 24,
)
