// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val enterpriseDesignSystem = AnduraDesignSystem(
    id = "enterprise",
    name = "Enterprise",
    category = "Professional & Corporate",
    description = "Bundled Open Design package for Enterprise, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF8FAFCu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEEF2F7u,
    foreground = 0xFF0F172Au,
    foregroundSecondary = 0xFF334155u,
    muted = 0xFF64748Bu,
    border = 0xFFD8DEE8u,
    accent = 0xFF1D4ED8u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF15803Du,
    warning = 0xFFB45309u,
    danger = 0xFFB91C1Cu,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 10.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 230,
    containerMax = 1240.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
