// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val expoDesignSystem = AnduraDesignSystem(
    id = "expo",
    name = "Expo",
    category = "Developer Tools",
    description = "Bundled Open Design package for Expo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF6F7F9u,
    surfaceWarm = 0xFFEEF2FFu,
    foreground = 0xFF0B0D12u,
    foregroundSecondary = 0xFF353945u,
    muted = 0xFF6B7280u,
    border = 0xFFDFE3EAu,
    accent = 0xFF000020u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF00A36Cu,
    warning = 0xFFF59E0Bu,
    danger = 0xFFE5484Du,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 14.0f,
    radiusLg = 22.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 140,
    motionBaseMs = 220,
    containerMax = 1160.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
