// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val expressiveDesignSystem = AnduraDesignSystem(
    id = "expressive",
    name = "Expressive",
    category = "Bold & Expressive",
    description = "Bundled Open Design package for Expressive, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFBF8FFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEFE8FFu,
    foreground = 0xFF1F1730u,
    foregroundSecondary = 0xFF4D425Fu,
    muted = 0xFF776B88u,
    border = 0xFFDED4EEu,
    accent = 0xFF7C3AEDu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFF59E0Bu,
    danger = 0xFFEF4444u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
