// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val fantasyDesignSystem = AnduraDesignSystem(
    id = "fantasy",
    name = "Fantasy",
    category = "Creative & Artistic",
    description = "Bundled Open Design package for Fantasy, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF070711u,
    surface = 0xFF111126u,
    surfaceWarm = 0xFF1E1540u,
    foreground = 0xFFF8F7FFu,
    foregroundSecondary = 0xFFD6CCFFu,
    muted = 0xFF9D8AD4u,
    border = 0xFF34265Eu,
    accent = 0xFFC084FCu,
    accentOn = 0xFF13051Fu,
    success = 0xFF39FF88u,
    warning = 0xFFFFF34Du,
    danger = 0xFFFF4D8Du,
    fontDisplay = "Georgia",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
