// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val ferrariDesignSystem = AnduraDesignSystem(
    id = "ferrari",
    name = "Ferrari",
    category = "Automotive",
    description = "Bundled Open Design package for Ferrari, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF0B0B0Bu,
    surface = 0xFF171717u,
    surfaceWarm = 0xFF23130Fu,
    foreground = 0xFFFFFAF0u,
    foregroundSecondary = 0xFFE8DCC8u,
    muted = 0xFFA89F91u,
    border = 0xFF342A24u,
    accent = 0xFFDC0000u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF0F9D58u,
    warning = 0xFFFFD200u,
    danger = 0xFFFF3B30u,
    fontDisplay = "Ferrari Sans",
    fontBody = "Ferrari Sans",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 14.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 130,
    motionBaseMs = 220,
    containerMax = 1240.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
