// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val framerDesignSystem = AnduraDesignSystem(
    id = "framer",
    name = "Framer",
    category = "Design & Creative",
    description = "Bundled Open Design package for Framer, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF000000u,
    surface = 0xFF090909u,
    surfaceWarm = 0xFF090909u,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFA6A6A6u,
    muted = 0x99FFFFFFu,
    border = 0x260099FFu,
    accent = 0xFF0099FFu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "GT Walsheim Framer Medium",
    fontBody = "Inter Variable",
    textBase = 15.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 20.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 32,
)
