// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val githubDesignSystem = AnduraDesignSystem(
    id = "github",
    name = "GitHub",
    category = "Developer Tools",
    description = "Bundled Open Design package for GitHub, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF6F8FAu,
    surfaceWarm = 0xFFF6F8FAu,
    foreground = 0xFF1F2328u,
    foregroundSecondary = 0xFF1F2328u,
    muted = 0xFF656D76u,
    border = 0xFFD0D7DEu,
    accent = 0xFF0969DAu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF1A7F37u,
    warning = 0xFF9A6700u,
    danger = 0xFFCF222Eu,
    fontDisplay = "-apple-system",
    fontBody = "-apple-system",
    textBase = 14.0f,
    radiusSm = 6.0f,
    radiusMd = 6.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 80,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "badges", "links", "icons", "typography", "layout"),
    sourceClassCount = 21,
)
