// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val glassmorphismDesignSystem = AnduraDesignSystem(
    id = "glassmorphism",
    name = "Glassmorphism",
    category = "Morphism & Effects",
    description = "Bundled Open Design package for Glassmorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFEEF6FFu,
    surface = 0xBDFFFFFFu,
    surfaceWarm = 0xB8EEF6FFu,
    foreground = 0xFF102033u,
    foregroundSecondary = 0xFF34465Fu,
    muted = 0xFF60708Au,
    border = 0xA3FFFFFFu,
    accent = 0xFF4F8CFFu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF22C55Eu,
    warning = 0xFFF59E0Bu,
    danger = 0xFFEF4444u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 16.0f,
    radiusMd = 24.0f,
    radiusLg = 36.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 180,
    motionBaseMs = 280,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
