// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val gradientDesignSystem = AnduraDesignSystem(
    id = "gradient",
    name = "Gradient",
    category = "Morphism & Effects",
    description = "Bundled Open Design package for Gradient, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF7F3FFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEFE7FFu,
    foreground = 0xFF191225u,
    foregroundSecondary = 0xFF443856u,
    muted = 0xFF746985u,
    border = 0xFFDDD2F2u,
    accent = 0xFF7C3AEDu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF10B981u,
    warning = 0xFFF59E0Bu,
    danger = 0xFFEF4444u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 12.0f,
    radiusMd = 20.0f,
    radiusLg = 32.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 160,
    motionBaseMs = 260,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
