// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val hashicorpDesignSystem = AnduraDesignSystem(
    id = "hashicorp",
    name = "HashiCorp",
    category = "Backend & Data",
    description = "Bundled Open Design package for HashiCorp, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF15181Eu,
    surface = 0xFF0D0E12u,
    surfaceWarm = 0xFF0D0E12u,
    foreground = 0xFFEFEFF1u,
    foregroundSecondary = 0xFFD5D7DBu,
    muted = 0xFFB2B6BDu,
    border = 0x66B2B6BDu,
    accent = 0xFF1060FFu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFBB5A00u,
    danger = 0xFFDC2626u,
    fontDisplay = "HashiCorp Sans",
    fontBody = "Poppins",
    textBase = 16.0f,
    radiusSm = 5.0f,
    radiusMd = 8.0f,
    radiusLg = 8.0f,
    radiusPill = 5.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1150.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 27,
)
