// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val hudDesignSystem = AnduraDesignSystem(
    id = "hud",
    name = "HUD Design System",
    category = "Themed & Unique",
    description = "Bundled Open Design package for HUD Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF090B12u,
    surface = 0xFF121722u,
    surfaceWarm = 0xFF1B2233u,
    foreground = 0xFFF8FAFCu,
    foregroundSecondary = 0xFFCBD5E1u,
    muted = 0xFF94A3B8u,
    border = 0xFF2A3447u,
    accent = 0xFF60A5FAu,
    accentOn = 0xFF06101Du,
    success = 0xFF22C55Eu,
    warning = 0xFFFBBF24u,
    danger = 0xFFFB7185u,
    fontDisplay = "IBM Plex Mono",
    fontBody = "IBM Plex Mono",
    textBase = 14.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 100,
    motionBaseMs = 180,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
