// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val huggingfaceDesignSystem = AnduraDesignSystem(
    id = "huggingface",
    name = "Hugging Face",
    category = "AI & LLM",
    description = "Bundled Open Design package for Hugging Face, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFAFAFAu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFF4CCu,
    foreground = 0xFF0D1117u,
    foregroundSecondary = 0xFF374151u,
    muted = 0xFF6B7280u,
    border = 0xFFE5E7EBu,
    accent = 0xFFFFD21Eu,
    accentOn = 0xFF0D1117u,
    success = 0xFF16A34Au,
    warning = 0xFFF59E0Bu,
    danger = 0xFFDC2626u,
    fontDisplay = "IBM Plex Mono",
    fontBody = "Source Sans Pro",
    textBase = 15.0f,
    radiusSm = 4.0f,
    radiusMd = 6.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 26,
)
