// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val ibmDesignSystem = AnduraDesignSystem(
    id = "ibm",
    name = "IBM",
    category = "Media & Consumer",
    description = "Bundled Open Design package for IBM, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF4F4F4u,
    surfaceWarm = 0xFFEDF5FFu,
    foreground = 0xFF161616u,
    foregroundSecondary = 0xFF525252u,
    muted = 0xFF6F6F6Fu,
    border = 0xFFC6C6C6u,
    accent = 0xFF0F62FEu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF24A148u,
    warning = 0xFFF1C21Bu,
    danger = 0xFFDA1E28u,
    fontDisplay = "IBM Plex Sans",
    fontBody = "IBM Plex Sans",
    textBase = 16.0f,
    radiusSm = 0.0f,
    radiusMd = 0.0f,
    radiusLg = 0.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 110,
    motionBaseMs = 180,
    containerMax = 1312.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
