// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val intercomDesignSystem = AnduraDesignSystem(
    id = "intercom",
    name = "Intercom",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Intercom, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFAF9F6u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFAF9F6u,
    foreground = 0xFF111111u,
    foregroundSecondary = 0xFF111111u,
    muted = 0xFF7B7B78u,
    border = 0xFFDEDBD6u,
    accent = 0xFFFF5600u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF00DA00u,
    warning = 0xFFEAB308u,
    danger = 0xFFC41C1Cu,
    fontDisplay = "Saans",
    fontBody = "Saans",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 6.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 37,
)
