// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val kamiDesignSystem = AnduraDesignSystem(
    id = "kami",
    name = "kami (紙 / 纸)",
    category = "Editorial & Print",
    description = "Bundled Open Design package for kami (紙 / 纸), derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF5F4EDu,
    surface = 0xFFFAF9F5u,
    surfaceWarm = 0xFFE8E6DCu,
    foreground = 0xFF141413u,
    foregroundSecondary = 0xFF3D3D3Au,
    muted = 0xFF504E49u,
    border = 0xFFE8E6DCu,
    accent = 0xFF1B365Du,
    accentOn = 0xFFFAF9F5u,
    success = 0xFF4A6B3Au,
    warning = 0xFF8A6B1Fu,
    danger = 0xFF8A3A30u,
    fontDisplay = "Charter",
    fontBody = "Charter",
    textBase = 14.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1120.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
