// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val krakenDesignSystem = AnduraDesignSystem(
    id = "kraken",
    name = "Kraken",
    category = "Fintech & Crypto",
    description = "Bundled Open Design package for Kraken, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF0B1020u,
    surface = 0xFF121A33u,
    surfaceWarm = 0xFF1B2450u,
    foreground = 0xFFF8FAFCu,
    foregroundSecondary = 0xFFCBD5E1u,
    muted = 0xFF8B95AAu,
    border = 0xFF26314Fu,
    accent = 0xFF7132F5u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF00C853u,
    warning = 0xFFFFB020u,
    danger = 0xFFFF4D6Du,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 15.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 18.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
