// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val lamborghiniDesignSystem = AnduraDesignSystem(
    id = "lamborghini",
    name = "Lamborghini",
    category = "Automotive",
    description = "Bundled Open Design package for Lamborghini, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF050505u,
    surface = 0xFF141414u,
    surfaceWarm = 0xFF211B0Bu,
    foreground = 0xFFF8F4E6u,
    foregroundSecondary = 0xFFD8CEB0u,
    muted = 0xFF9B927Du,
    border = 0xFF3A321Du,
    accent = 0xFFD4AF37u,
    accentOn = 0xFF050505u,
    success = 0xFF39A852u,
    warning = 0xFFF7C948u,
    danger = 0xFFE63946u,
    fontDisplay = "Lamborghini",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 2.0f,
    radiusMd = 6.0f,
    radiusLg = 10.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 210,
    containerMax = 1240.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
