// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val levelsDesignSystem = AnduraDesignSystem(
    id = "levels",
    name = "Levels",
    category = "Layout & Structure",
    description = "Bundled Open Design package for Levels, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFBF7EFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEEF7EDu,
    foreground = 0xFF1F2A24u,
    foregroundSecondary = 0xFF435147u,
    muted = 0xFF788276u,
    border = 0xFFDBE3D7u,
    accent = 0xFF2F8F46u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFD97706u,
    danger = 0xFFDC2626u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 12.0f,
    radiusMd = 18.0f,
    radiusLg = 28.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 160,
    motionBaseMs = 240,
    containerMax = 1160.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
