// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val linearAppDesignSystem = AnduraDesignSystem(
    id = "linear-app",
    name = "Linear",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Linear, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF08090Au,
    surface = 0xFF191A1Bu,
    surfaceWarm = 0xFF191A1Bu,
    foreground = 0xFFF7F8F8u,
    foregroundSecondary = 0xFFD0D6E0u,
    muted = 0xFF8A8F98u,
    border = 0x14FFFFFFu,
    accent = 0xFF5E6AD2u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF27A644u,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Inter Variable",
    fontBody = "Inter Variable",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"),
    sourceClassCount = 15,
)
