// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val lingoDesignSystem = AnduraDesignSystem(
    id = "lingo",
    name = "Lingo",
    category = "Creative & Artistic",
    description = "Bundled Open Design package for Lingo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFBF9FFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFF1ECFFu,
    foreground = 0xFF1D1B2Au,
    foregroundSecondary = 0xFF4F4863u,
    muted = 0xFF786F8Fu,
    border = 0xFFDED7F0u,
    accent = 0xFF6D4AFFu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF22A06Bu,
    warning = 0xFFE6A700u,
    danger = 0xFFE5484Du,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 230,
    containerMax = 1160.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
