// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val loomDesignSystem = AnduraDesignSystem(
    id = "loom",
    name = "Loom Design System",
    category = "Themed & Unique",
    description = "Bundled Open Design package for Loom Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF7F7F8u,
    surfaceWarm = 0xFFF7F7F8u,
    foreground = 0xFF1F1F23u,
    foregroundSecondary = 0xFF1F1F23u,
    muted = 0xFF6B6D76u,
    border = 0xFFE4E4E7u,
    accent = 0xFF625DF5u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFD64770u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 14.0f,
    radiusSm = 4.0f,
    radiusMd = 6.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 100,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 31,
)
