// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val lovableDesignSystem = AnduraDesignSystem(
    id = "lovable",
    name = "Lovable",
    category = "Developer Tools",
    description = "Bundled Open Design package for Lovable, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF7F4EDu,
    surface = 0xFFF7F4EDu,
    surfaceWarm = 0xFFF7F4EDu,
    foreground = 0xFF1C1C1Cu,
    foregroundSecondary = 0xD41C1C1Cu,
    muted = 0xFF5F5F5Du,
    border = 0xFFECEAE4u,
    accent = 0xFFFF4D8Du,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Camera Plain Variable",
    fontBody = "Camera Plain Variable",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 12.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 24,
)
