// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val luxuryDesignSystem = AnduraDesignSystem(
    id = "luxury",
    name = "Luxury",
    category = "Professional & Corporate",
    description = "Bundled Open Design package for Luxury, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF080706u,
    surface = 0xFF151310u,
    surfaceWarm = 0xFF241E14u,
    foreground = 0xFFFFF8EAu,
    foregroundSecondary = 0xFFD8CDB7u,
    muted = 0xFF9F927Cu,
    border = 0xFF3A3020u,
    accent = 0xFFC6A15Bu,
    accentOn = 0xFF080706u,
    success = 0xFF5FA36Au,
    warning = 0xFFD8A94Fu,
    danger = 0xFFD85A52u,
    fontDisplay = "Didot",
    fontBody = "Avenir Next",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 14.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 180,
    motionBaseMs = 300,
    containerMax = 1160.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
