// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val mastercardDesignSystem = AnduraDesignSystem(
    id = "mastercard",
    name = "Mastercard",
    category = "Fintech & Crypto",
    description = "Bundled Open Design package for Mastercard, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF3F0EEu,
    surface = 0xFFFCFBFAu,
    surfaceWarm = 0xFFF7E8DEu,
    foreground = 0xFF141413u,
    foregroundSecondary = 0xFF262627u,
    muted = 0xFF696969u,
    border = 0xFFD1CDC7u,
    accent = 0xFFCF4500u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF2E7D32u,
    warning = 0xFFF79E1Bu,
    danger = 0xFFEB001Bu,
    fontDisplay = "MarkForMC",
    fontBody = "MarkForMC",
    textBase = 16.0f,
    radiusSm = 20.0f,
    radiusMd = 40.0f,
    radiusLg = 64.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 180,
    motionBaseMs = 260,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
