// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val materialDesignSystem = AnduraDesignSystem(
    id = "material",
    name = "Material",
    category = "Professional & Corporate",
    description = "Bundled Open Design package for Material, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF8FAFDu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFE8F0FEu,
    foreground = 0xFF202124u,
    foregroundSecondary = 0xFF3C4043u,
    muted = 0xFF5F6368u,
    border = 0xFFDADCE0u,
    accent = 0xFF1A73E8u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF188038u,
    warning = 0xFFF9AB00u,
    danger = 0xFFD93025u,
    fontDisplay = "Google Sans",
    fontBody = "Roboto",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 12.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 250,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
