// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val metaDesignSystem = AnduraDesignSystem(
    id = "meta",
    name = "Meta (Store)",
    category = "E-Commerce & Retail",
    description = "Bundled Open Design package for Meta (Store), derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF7F8FAu,
    surfaceWarm = 0xFFF2F0E6u,
    foreground = 0xFF1C2B33u,
    foregroundSecondary = 0xFF5D6C7Bu,
    muted = 0xFF65676Bu,
    border = 0xFFCED0D4u,
    accent = 0xFF0064E0u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF31A24Cu,
    warning = 0xFFF7B928u,
    danger = 0xFFE41E3Fu,
    fontDisplay = "Optimistic VF",
    fontBody = "Optimistic VF",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 20.0f,
    radiusLg = 24.0f,
    radiusPill = 100.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1440.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 31,
)
