// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val minimaxDesignSystem = AnduraDesignSystem(
    id = "minimax",
    name = "MiniMax",
    category = "AI & LLM",
    description = "Bundled Open Design package for MiniMax, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFAFAFAu,
    surfaceWarm = 0xFFF0F0F0u,
    foreground = 0xFF222222u,
    foregroundSecondary = 0xFF18181Bu,
    muted = 0xFF45515Eu,
    border = 0xFFE5E7EBu,
    accent = 0xFF1456F0u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Outfit",
    fontBody = "DM Sans",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 13.0f,
    radiusLg = 20.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 33,
)
