// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val minimalDesignSystem = AnduraDesignSystem(
    id = "minimal",
    name = "Minimal",
    category = "Modern & Minimal",
    description = "Bundled Open Design package for Minimal, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFAFAFAu,
    surfaceWarm = 0xFFF5F5F5u,
    foreground = 0xFF111111u,
    foregroundSecondary = 0xFF3A3A3Au,
    muted = 0xFF777777u,
    border = 0xFFE2E2E2u,
    accent = 0xFF111111u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF168A46u,
    warning = 0xFFB7791Fu,
    danger = 0xFFC53030u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 2.0f,
    radiusMd = 4.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 140,
    motionBaseMs = 220,
    containerMax = 1120.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
