// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val mintlifyDesignSystem = AnduraDesignSystem(
    id = "mintlify",
    name = "Mintlify",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Mintlify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFAFAFAu,
    foreground = 0xFF0D0D0Du,
    foregroundSecondary = 0xFF333333u,
    muted = 0xFF666666u,
    border = 0x0D000000u,
    accent = 0xFF18E299u,
    accentOn = 0xFF0D0D0Du,
    success = 0xFF16A34Au,
    warning = 0xFFC37D0Du,
    danger = 0xFFD45656u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 34,
)
