// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val miroDesignSystem = AnduraDesignSystem(
    id = "miro",
    name = "Miro",
    category = "Design & Creative",
    description = "Bundled Open Design package for Miro, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFF7C2u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFF3A3u,
    foreground = 0xFF050038u,
    foregroundSecondary = 0xFF322B6Bu,
    muted = 0xFF605A8Au,
    border = 0xFFDED9FFu,
    accent = 0xFFFFD02Fu,
    accentOn = 0xFF050038u,
    success = 0xFF1A7F37u,
    warning = 0xFFFF9F1Cu,
    danger = 0xFFD92D20u,
    fontDisplay = "Formular",
    fontBody = "Formular",
    textBase = 16.0f,
    radiusSm = 10.0f,
    radiusMd = 18.0f,
    radiusLg = 28.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 230,
    containerMax = 1220.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
