// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val mistralAiDesignSystem = AnduraDesignSystem(
    id = "mistral-ai",
    name = "Mistral AI",
    category = "AI & LLM",
    description = "Bundled Open Design package for Mistral AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFAEBu,
    surface = 0xFFFFF0C2u,
    surfaceWarm = 0xFFFFF0C2u,
    foreground = 0xFF1F1F1Fu,
    foregroundSecondary = 0xFF1F1F1Fu,
    muted = 0xFF3D3D3Du,
    border = 0xFFF0E8C8u,
    accent = 0xFFFA520Fu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF17A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Arial",
    fontBody = "Arial",
    textBase = 16.0f,
    radiusSm = 2.0f,
    radiusMd = 2.0f,
    radiusLg = 4.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 25,
)
