// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val modernDesignSystem = AnduraDesignSystem(
    id = "modern",
    name = "Modern",
    category = "Modern & Minimal",
    description = "Bundled Open Design package for Modern, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF7F8FCu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEEF1FFu,
    foreground = 0xFF111827u,
    foregroundSecondary = 0xFF374151u,
    muted = 0xFF6B7280u,
    border = 0xFFDFE3EDu,
    accent = 0xFF4F46E5u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF10B981u,
    warning = 0xFFF59E0Bu,
    danger = 0xFFEF4444u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
