// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val mongodbDesignSystem = AnduraDesignSystem(
    id = "mongodb",
    name = "MongoDB",
    category = "Backend & Data",
    description = "Bundled Open Design package for MongoDB, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF001E2Bu,
    surface = 0xFF1C2D38u,
    surfaceWarm = 0xFF1C2D38u,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFE8EDEBu,
    muted = 0xFFB8C4C2u,
    border = 0xFF3D4F58u,
    accent = 0xFF00ED64u,
    accentOn = 0xFF001E2Bu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "MongoDB Value Serif",
    fontBody = "Euclid Circular A",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 26,
)
