// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val monoDesignSystem = AnduraDesignSystem(
    id = "mono",
    name = "Mono",
    category = "Modern & Minimal",
    description = "Bundled Open Design package for Mono, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF7F7F7u,
    surfaceWarm = 0xFFEEEEEEu,
    foreground = 0xFF111111u,
    foregroundSecondary = 0xFF3A3A3Au,
    muted = 0xFF707070u,
    border = 0xFFD9D9D9u,
    accent = 0xFF111111u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF168A46u,
    warning = 0xFFB7791Fu,
    danger = 0xFFC53030u,
    fontDisplay = "IBM Plex Mono",
    fontBody = "IBM Plex Mono",
    textBase = 14.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 100,
    motionBaseMs = 180,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
