// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val nikeDesignSystem = AnduraDesignSystem(
    id = "nike",
    name = "Nike",
    category = "E-Commerce & Retail",
    description = "Bundled Open Design package for Nike, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF5F5F5u,
    surfaceWarm = 0xFFFAFAFAu,
    foreground = 0xFF111111u,
    foregroundSecondary = 0xFF111111u,
    muted = 0xFF707072u,
    border = 0xFFCACACBu,
    accent = 0xFF111111u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF007D48u,
    warning = 0xFFFCA600u,
    danger = 0xFFD30005u,
    fontDisplay = "Nike Futura ND",
    fontBody = "Helvetica Now Text Medium",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 20.0f,
    radiusLg = 24.0f,
    radiusPill = 30.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1440.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 29,
)
