// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val notionDesignSystem = AnduraDesignSystem(
    id = "notion",
    name = "Notion",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Notion, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF6F5F4u,
    surfaceWarm = 0xFFF6F5F4u,
    foreground = 0xF2000000u,
    foregroundSecondary = 0xFF31302Eu,
    muted = 0xFF615D59u,
    border = 0x1A000000u,
    accent = 0xFF0075DEu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF1AAE39u,
    warning = 0xFFDD5B00u,
    danger = 0xFFDC2626u,
    fontDisplay = "NotionInter",
    fontBody = "NotionInter",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"),
    sourceClassCount = 22,
)
