// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val nvidiaDesignSystem = AnduraDesignSystem(
    id = "nvidia",
    name = "NVIDIA",
    category = "Media & Consumer",
    description = "Bundled Open Design package for NVIDIA, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF000000u,
    surface = 0xFF1A1A1Au,
    surfaceWarm = 0xFF1A1A1Au,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFA7A7A7u,
    muted = 0xFF757575u,
    border = 0xFF5E5E5Eu,
    accent = 0xFF76B900u,
    accentOn = 0xFF000000u,
    success = 0xFF3F8500u,
    warning = 0xFFEF9100u,
    danger = 0xFFE52020u,
    fontDisplay = "NVIDIA-EMEA",
    fontBody = "NVIDIA-EMEA",
    textBase = 16.0f,
    radiusSm = 2.0f,
    radiusMd = 2.0f,
    radiusLg = 4.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"),
    sourceClassCount = 31,
)
