// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val ollamaDesignSystem = AnduraDesignSystem(
    id = "ollama",
    name = "Ollama",
    category = "AI & LLM",
    description = "Bundled Open Design package for Ollama, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFAFAFAu,
    surfaceWarm = 0xFFFAFAFAu,
    foreground = 0xFF000000u,
    foregroundSecondary = 0xFF262626u,
    muted = 0xFF737373u,
    border = 0xFFE5E5E5u,
    accent = 0xFF000000u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "SF Pro Rounded",
    fontBody = "ui-sans-serif",
    textBase = 16.0f,
    radiusSm = 9999.0f,
    radiusMd = 12.0f,
    radiusLg = 9999.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 100,
    motionBaseMs = 140,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"),
    sourceClassCount = 34,
)
