// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val opencodeAiDesignSystem = AnduraDesignSystem(
    id = "opencode-ai",
    name = "OpenCode",
    category = "AI & LLM",
    description = "Bundled Open Design package for OpenCode, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF201D1Du,
    surface = 0xFF302C2Cu,
    surfaceWarm = 0xFF302C2Cu,
    foreground = 0xFFFDFCFCu,
    foregroundSecondary = 0xFFC8C6C4u,
    muted = 0xFF9A9898u,
    border = 0xFF464343u,
    accent = 0xFF007AFFu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF30D158u,
    warning = 0xFFFF9F0Au,
    danger = 0xFFFF3B30u,
    fontDisplay = "Berkeley Mono",
    fontBody = "Berkeley Mono",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 6.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 100,
    motionBaseMs = 150,
    containerMax = 880.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 26,
)
