// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val openaiDesignSystem = AnduraDesignSystem(
    id = "openai",
    name = "OpenAI",
    category = "AI & LLM",
    description = "Bundled Open Design package for OpenAI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF5F5F5u,
    surfaceWarm = 0xFFFAFAFAu,
    foreground = 0xFF0D0D0Du,
    foregroundSecondary = 0xFF1A1A1Au,
    muted = 0xFF6E6E6Eu,
    border = 0xFFE5E5E5u,
    accent = 0xFF10A37Fu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF10A37Fu,
    warning = 0xFFF5A623u,
    danger = 0xFFEF4146u,
    fontDisplay = "Signifier",
    fontBody = "Söhne",
    textBase = 16.0f,
    radiusSm = 12.0f,
    radiusMd = 16.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 220,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"),
    sourceClassCount = 18,
)
