// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val pacmanDesignSystem = AnduraDesignSystem(
    id = "pacman",
    name = "Pacman",
    category = "Themed & Unique",
    description = "Bundled Open Design package for Pacman, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF050505u,
    surface = 0xFF101014u,
    surfaceWarm = 0xFF1F1B08u,
    foreground = 0xFFFFF7D6u,
    foregroundSecondary = 0xFFF6E79Cu,
    muted = 0xFFB9A85Du,
    border = 0xFF2338FFu,
    accent = 0xFFFFCC00u,
    accentOn = 0xFF050505u,
    success = 0xFF00FF66u,
    warning = 0xFFFF9900u,
    danger = 0xFFFF3B3Bu,
    fontDisplay = "Press Start 2P",
    fontBody = "Inter",
    textBase = 14.0f,
    radiusSm = 10.0f,
    radiusMd = 18.0f,
    radiusLg = 9999.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 90,
    motionBaseMs = 160,
    containerMax = 1080.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
