// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val paperDesignSystem = AnduraDesignSystem(
    id = "paper",
    name = "Paper",
    category = "Retro & Nostalgic",
    description = "Bundled Open Design package for Paper, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFAF3DFu,
    surface = 0xFFFFFAF0u,
    surfaceWarm = 0xFFEFE0BDu,
    foreground = 0xFF211B12u,
    foregroundSecondary = 0xFF504737u,
    muted = 0xFF7C7160u,
    border = 0xFFDDD0B4u,
    accent = 0xFF8F5D24u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF5B8D42u,
    warning = 0xFFC27B22u,
    danger = 0xFFA64036u,
    fontDisplay = "Georgia",
    fontBody = "Inter",
    textBase = 17.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
