// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val perplexityDesignSystem = AnduraDesignSystem(
    id = "perplexity",
    name = "Perplexity AI",
    category = "AI & LLM",
    description = "Bundled Open Design package for Perplexity AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF0F0F10u,
    surface = 0xFF19191Au,
    surfaceWarm = 0xFF19191Au,
    foreground = 0xFFF0F0F0u,
    foregroundSecondary = 0xFFF0F0F0u,
    muted = 0xFF9B9B9Bu,
    border = 0xFF2E2E30u,
    accent = 0xFFA855F7u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF22C55Eu,
    warning = 0xFFF59E0Bu,
    danger = 0xFFEF4444u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 15.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 200,
    containerMax = 1100.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "links", "icons", "typography", "layout"),
    sourceClassCount = 23,
)
