// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val pinterestDesignSystem = AnduraDesignSystem(
    id = "pinterest",
    name = "Pinterest",
    category = "Media & Consumer",
    description = "Bundled Open Design package for Pinterest, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF6F6F3u,
    surfaceWarm = 0xFFE5E5E0u,
    foreground = 0xFF211922u,
    foregroundSecondary = 0xFF000000u,
    muted = 0xFF62625Bu,
    border = 0xFFC8C8C1u,
    accent = 0xFFE60023u,
    accentOn = 0xFF000000u,
    success = 0xFF103C25u,
    warning = 0xFFC47700u,
    danger = 0xFF9E0A0Au,
    fontDisplay = "Pin Sans",
    fontBody = "Pin Sans",
    textBase = 16.0f,
    radiusSm = 12.0f,
    radiusMd = 16.0f,
    radiusLg = 28.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 43,
)
