// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val playstationDesignSystem = AnduraDesignSystem(
    id = "playstation",
    name = "PlayStation",
    category = "Media & Consumer",
    description = "Bundled Open Design package for PlayStation, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF000000u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFF5F7FAu,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFFFFFFFu,
    muted = 0xFFCCCCCCu,
    border = 0xFFCCCCCCu,
    accent = 0xFF0070CCu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFC81B3Au,
    fontDisplay = "SST",
    fontBody = "SST",
    textBase = 18.0f,
    radiusSm = 6.0f,
    radiusMd = 12.0f,
    radiusLg = 24.0f,
    radiusPill = 999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 180,
    motionBaseMs = 200,
    containerMax = 1600.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 28,
)
