// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val posthogDesignSystem = AnduraDesignSystem(
    id = "posthog",
    name = "PostHog",
    category = "Backend & Data",
    description = "Bundled Open Design package for PostHog, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFDFDF8u,
    surface = 0xFFEEEFE9u,
    surfaceWarm = 0xFFE5E7E0u,
    foreground = 0xFF4D4F46u,
    foregroundSecondary = 0xFF23251Du,
    muted = 0xFF65675Eu,
    border = 0xFFBFC1B7u,
    accent = 0xFFF54E00u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFF7A501u,
    danger = 0xFFDC2626u,
    fontDisplay = "IBM Plex Sans Variable",
    fontBody = "IBM Plex Sans Variable",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 6.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 42,
)
