// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val premiumDesignSystem = AnduraDesignSystem(
    id = "premium",
    name = "Premium",
    category = "Professional & Corporate",
    description = "Bundled Open Design package for Premium, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFAF8F4u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFF0E7D8u,
    foreground = 0xFF1C1B19u,
    foregroundSecondary = 0xFF4B4740u,
    muted = 0xFF746D63u,
    border = 0xFFDED6C9u,
    accent = 0xFFA06A3Bu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF3F8F5Fu,
    warning = 0xFFC4872Cu,
    danger = 0xFFB84A4Au,
    fontDisplay = "Canela",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 28.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 170,
    motionBaseMs = 280,
    containerMax = 1160.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
