// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val publicationDesignSystem = AnduraDesignSystem(
    id = "publication",
    name = "Publication",
    category = "Creative & Artistic",
    description = "Bundled Open Design package for Publication, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF6F6F6u,
    surfaceWarm = 0xFFFFF2F0u,
    foreground = 0xFF0B0B0Bu,
    foregroundSecondary = 0xFF333333u,
    muted = 0xFF666666u,
    border = 0xFFD6D6D6u,
    accent = 0xFFC1121Fu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF0F8A3Bu,
    warning = 0xFFD99A00u,
    danger = 0xFFB00020u,
    fontDisplay = "Franklin Gothic",
    fontBody = "Georgia",
    textBase = 17.0f,
    radiusSm = 0.0f,
    radiusMd = 0.0f,
    radiusLg = 0.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 200,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
