// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val raycastDesignSystem = AnduraDesignSystem(
    id = "raycast",
    name = "Raycast",
    category = "Developer Tools",
    description = "Bundled Open Design package for Raycast, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF07080Au,
    surface = 0xFF101111u,
    surfaceWarm = 0xFF101111u,
    foreground = 0xFFF9F9F9u,
    foregroundSecondary = 0xFFCECECEu,
    muted = 0xFF9C9C9Du,
    border = 0x0FFFFFFFu,
    accent = 0xFFFF6363u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 12.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "typography", "layout"),
    sourceClassCount = 23,
)
