// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val renaultDesignSystem = AnduraDesignSystem(
    id = "renault",
    name = "Renault",
    category = "Automotive",
    description = "Bundled Open Design package for Renault, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF7F4EFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFF4BFu,
    foreground = 0xFF111111u,
    foregroundSecondary = 0xFF3F3F3Fu,
    muted = 0xFF6F6B63u,
    border = 0xFFDFD8CAu,
    accent = 0xFFFFCC33u,
    accentOn = 0xFF111111u,
    success = 0xFF198754u,
    warning = 0xFFF59E0Bu,
    danger = 0xFFD92D20u,
    fontDisplay = "Renault Group",
    fontBody = "Renault Group",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 14.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 140,
    motionBaseMs = 230,
    containerMax = 1220.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
