// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val replicateDesignSystem = AnduraDesignSystem(
    id = "replicate",
    name = "Replicate",
    category = "AI & LLM",
    description = "Bundled Open Design package for Replicate, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF8F8F8u,
    surfaceWarm = 0xFFF8F8F8u,
    foreground = 0xFF202020u,
    foregroundSecondary = 0xFF4E4E4Eu,
    muted = 0xFF646464u,
    border = 0xFF202020u,
    accent = 0xFFEA2804u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF2B9A66u,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "rb-freigeist-neue",
    fontBody = "basier-square",
    textBase = 16.0f,
    radiusSm = 9999.0f,
    radiusMd = 9999.0f,
    radiusLg = 9999.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 25,
)
