// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val resendDesignSystem = AnduraDesignSystem(
    id = "resend",
    name = "Resend",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Resend, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF000000u,
    surface = 0xFF000000u,
    surfaceWarm = 0xFF000000u,
    foreground = 0xFFF0F0F0u,
    foregroundSecondary = 0xFFA1A4A5u,
    muted = 0xFF5C5C5Cu,
    border = 0x30D6EBFDu,
    accent = 0xFFFF801Fu,
    accentOn = 0xFF000000u,
    success = 0xFF11FF99u,
    warning = 0xFFFFC53Du,
    danger = 0xFFFF2047u,
    fontDisplay = "ABC Favorit",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 39,
)
