// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val retroDesignSystem = AnduraDesignSystem(
    id = "retro",
    name = "Retro",
    category = "Retro & Nostalgic",
    description = "Bundled Open Design package for Retro, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFF4CFu,
    surface = 0xFFFFFAF0u,
    surfaceWarm = 0xFFFFDCA8u,
    foreground = 0xFF2A1810u,
    foregroundSecondary = 0xFF593625u,
    muted = 0xFF8A6652u,
    border = 0xFFD9AA7Au,
    accent = 0xFFD24B1Fu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF3D8F4Fu,
    warning = 0xFFF2A93Bu,
    danger = 0xFFB83A2Fu,
    fontDisplay = "Courier New",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
