// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val revolutDesignSystem = AnduraDesignSystem(
    id = "revolut",
    name = "Revolut",
    category = "Fintech & Crypto",
    description = "Bundled Open Design package for Revolut, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF7F8FBu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEEF4FFu,
    foreground = 0xFF111827u,
    foregroundSecondary = 0xFF334155u,
    muted = 0xFF64748Bu,
    border = 0xFFDBE3EFu,
    accent = 0xFF0666EBu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFF59E0Bu,
    danger = 0xFFEF4444u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 12.0f,
    radiusMd = 20.0f,
    radiusLg = 30.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
