// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val runwaymlDesignSystem = AnduraDesignSystem(
    id = "runwayml",
    name = "Runway",
    category = "AI & LLM",
    description = "Bundled Open Design package for Runway, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF000000u,
    surface = 0xFF1A1A1Au,
    surfaceWarm = 0xFF030303u,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFE9ECF2u,
    muted = 0xFF767D88u,
    border = 0xFF27272Au,
    accent = 0xFFFFFFFFu,
    accentOn = 0xFF000000u,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "abcNormal",
    fontBody = "abcNormal",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 220,
    containerMax = 1600.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 35,
)
