// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val sanityDesignSystem = AnduraDesignSystem(
    id = "sanity",
    name = "Sanity",
    category = "Backend & Data",
    description = "Bundled Open Design package for Sanity, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF8F8F7u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFF1EFu,
    foreground = 0xFF171717u,
    foregroundSecondary = 0xFF3F3F46u,
    muted = 0xFF71717Au,
    border = 0xFFE4E4E7u,
    accent = 0xFFF03E2Fu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFF59E0Bu,
    danger = 0xFFDC2626u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 10.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 140,
    motionBaseMs = 210,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
