// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val sentryDesignSystem = AnduraDesignSystem(
    id = "sentry",
    name = "Sentry",
    category = "Backend & Data",
    description = "Bundled Open Design package for Sentry, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF1F1633u,
    surface = 0xFF150F23u,
    surfaceWarm = 0xFF150F23u,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFE5E7EBu,
    muted = 0xFF9D96B3u,
    border = 0xFF362D59u,
    accent = 0xFF6A5FC1u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Dammit Sans",
    fontBody = "Rubik",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1152.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 27,
)
