// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val shadcnDesignSystem = AnduraDesignSystem(
    id = "shadcn",
    name = "Shadcn",
    category = "Modern & Minimal",
    description = "Bundled Open Design package for Shadcn, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFFFFFu,
    foreground = 0xFF111827u,
    foregroundSecondary = 0xFF111827u,
    muted = 0xFF64748Bu,
    border = 0xFFE5E7EBu,
    accent = 0xFF000000u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFD97706u,
    danger = 0xFFDC2626u,
    fontDisplay = "Geist",
    fontBody = "Geist",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 32,
)
