// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val shopifyDesignSystem = AnduraDesignSystem(
    id = "shopify",
    name = "Shopify",
    category = "E-Commerce & Retail",
    description = "Bundled Open Design package for Shopify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF000000u,
    surface = 0xFF02090Au,
    surfaceWarm = 0xFF061A1Cu,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFFFFFFFu,
    muted = 0xFFA1A1AAu,
    border = 0xFF1E2C31u,
    accent = 0xFF36F4A4u,
    accentOn = 0xFF000000u,
    success = 0xFF36F4A4u,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "NeueHaasGrotesk",
    fontBody = "Inter Variable",
    textBase = 18.0f,
    radiusSm = 9999.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 28.0f,
    space8 = 36.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "links", "icons", "typography", "layout"),
    sourceClassCount = 15,
)
