// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val skeumorphismDesignSystem = AnduraDesignSystem(
    id = "skeumorphism",
    name = "Skeumorphism",
    category = "Morphism & Effects",
    description = "Bundled Open Design package for Skeumorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF7EEE6u,
    surface = 0xFFFFF8F1u,
    surfaceWarm = 0xFFEAD6C7u,
    foreground = 0xFF2B211Cu,
    foregroundSecondary = 0xFF5A4B43u,
    muted = 0xFF8A7A70u,
    border = 0xFFDAC8B9u,
    accent = 0xFFB46A46u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF4D8F5Au,
    warning = 0xFFC88735u,
    danger = 0xFFB84C4Cu,
    fontDisplay = "Georgia",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 14.0f,
    radiusMd = 22.0f,
    radiusLg = 34.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
