// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val slackDesignSystem = AnduraDesignSystem(
    id = "slack",
    name = "Slack",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Slack, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF8F8F8u,
    surfaceWarm = 0xFFF8F8F8u,
    foreground = 0xFF1D1C1Du,
    foregroundSecondary = 0xFF1D1C1Du,
    muted = 0xFF616061u,
    border = 0xFFDDDDDDu,
    accent = 0xFF4A154Bu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF2EB67Du,
    warning = 0xFFECB22Eu,
    danger = 0xFFE01E5Au,
    fontDisplay = "Larsseit",
    fontBody = "Poppins",
    textBase = 15.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "links", "typography", "layout"),
    sourceClassCount = 19,
)
