// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val spacexDesignSystem = AnduraDesignSystem(
    id = "spacex",
    name = "SpaceX",
    category = "Media & Consumer",
    description = "Bundled Open Design package for SpaceX, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF000000u,
    surface = 0xFF000000u,
    surfaceWarm = 0xFF000000u,
    foreground = 0xFFF0F0FAu,
    foregroundSecondary = 0xFFF0F0FAu,
    muted = 0xB2F0F0FAu,
    border = 0x59F0F0FAu,
    accent = 0xFFF0F0FAu,
    accentOn = 0xFF000000u,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "D-DIN-Bold",
    fontBody = "D-DIN",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 4.0f,
    radiusLg = 4.0f,
    radiusPill = 32.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1440.0f,
    componentGroups = listOf("buttons", "inputs", "links", "icons", "typography", "layout"),
    sourceClassCount = 22,
)
