// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val spotifyDesignSystem = AnduraDesignSystem(
    id = "spotify",
    name = "Spotify",
    category = "Media & Consumer",
    description = "Bundled Open Design package for Spotify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF121212u,
    surface = 0xFF181818u,
    surfaceWarm = 0xFF1F1F1Fu,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFFDFDFDu,
    muted = 0xFFB3B3B3u,
    border = 0xFF4D4D4Du,
    accent = 0xFF1ED760u,
    accentOn = 0xFF000000u,
    success = 0xFF1ED760u,
    warning = 0xFFFFA42Bu,
    danger = 0xFFF3727Fu,
    fontDisplay = "SpotifyMixUITitle",
    fontBody = "SpotifyMixUI",
    textBase = 16.0f,
    radiusSm = 9999.0f,
    radiusMd = 6.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "cards", "links", "icons", "typography", "layout"),
    sourceClassCount = 20,
)
