// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val starbucksDesignSystem = AnduraDesignSystem(
    id = "starbucks",
    name = "Starbucks",
    category = "E-Commerce & Retail",
    description = "Bundled Open Design package for Starbucks, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF2F0EBu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEDEBE9u,
    foreground = 0xDE000000u,
    foregroundSecondary = 0xFF33433Du,
    muted = 0x94000000u,
    border = 0xFFD6DBDEu,
    accent = 0xFF00754Au,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFFBBC05u,
    danger = 0xFFC82014u,
    fontDisplay = "SoDoSans",
    fontBody = "SoDoSans",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 12.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1440.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 30,
)
