// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val stripeDesignSystem = AnduraDesignSystem(
    id = "stripe",
    name = "Stripe",
    category = "Fintech & Crypto",
    description = "Bundled Open Design package for Stripe, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFF6F9FCu,
    foreground = 0xFF061B31u,
    foregroundSecondary = 0xFF273951u,
    muted = 0xFF64748Du,
    border = 0xFFE5EDF5u,
    accent = 0xFF533AFDu,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF15BE53u,
    warning = 0xFF9B6829u,
    danger = 0xFFEA2261u,
    fontDisplay = "sohne-var",
    fontBody = "sohne-var",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 6.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1080.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 45,
)
