// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val supabaseDesignSystem = AnduraDesignSystem(
    id = "supabase",
    name = "Supabase",
    category = "Backend & Data",
    description = "Bundled Open Design package for Supabase, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF171717u,
    surface = 0xFF1C1C1Cu,
    surfaceWarm = 0xFF1C1C1Cu,
    foreground = 0xFFFAFAFAu,
    foregroundSecondary = 0xFFB4B4B4u,
    muted = 0xFF898989u,
    border = 0xFF2E2E2Eu,
    accent = 0xFF3ECF8Eu,
    accentOn = 0xFF0F0F0Fu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Circular",
    fontBody = "Circular",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 8.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 30,
)
