// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val superhumanDesignSystem = AnduraDesignSystem(
    id = "superhuman",
    name = "Superhuman",
    category = "Developer Tools",
    description = "Bundled Open Design package for Superhuman, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFE9E5DDu,
    foreground = 0xFF292827u,
    foregroundSecondary = 0xFF292827u,
    muted = 0xFF6F6C69u,
    border = 0xFFDCD7D3u,
    accent = 0xFFCBB7FBu,
    accentOn = 0xFF292827u,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Super Sans VF",
    fontBody = "Super Sans VF",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 8.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 31,
)
