// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val teslaDesignSystem = AnduraDesignSystem(
    id = "tesla",
    name = "Tesla",
    category = "Automotive",
    description = "Bundled Open Design package for Tesla, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF4F4F4u,
    surfaceWarm = 0xFFF4F4F4u,
    foreground = 0xFF171A20u,
    foregroundSecondary = 0xFF393C41u,
    muted = 0xFF5C5E62u,
    border = 0xFFD0D1D2u,
    accent = 0xFF3E6AE1u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Universal Sans Display",
    fontBody = "Universal Sans Text",
    textBase = 14.0f,
    radiusSm = 4.0f,
    radiusMd = 12.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 250,
    motionBaseMs = 330,
    containerMax = 1383.0f,
    componentGroups = listOf("buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 37,
)
