// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val tetrisDesignSystem = AnduraDesignSystem(
    id = "tetris",
    name = "Tetris",
    category = "Themed & Unique",
    description = "Bundled Open Design package for Tetris, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF050816u,
    surface = 0xFF10162Au,
    surfaceWarm = 0xFF17203Au,
    foreground = 0xFFF8FAFCu,
    foregroundSecondary = 0xFFCBD5E1u,
    muted = 0xFF94A3B8u,
    border = 0xFF26324Fu,
    accent = 0xFF00F0F0u,
    accentOn = 0xFF061018u,
    success = 0xFF00F000u,
    warning = 0xFFF0F000u,
    danger = 0xFFF00000u,
    fontDisplay = "Press Start 2P",
    fontBody = "Inter",
    textBase = 14.0f,
    radiusSm = 0.0f,
    radiusMd = 0.0f,
    radiusLg = 4.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 80,
    motionBaseMs = 140,
    containerMax = 1100.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
