// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val thevergeDesignSystem = AnduraDesignSystem(
    id = "theverge",
    name = "The Verge",
    category = "Media & Consumer",
    description = "Bundled Open Design package for The Verge, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF050505u,
    surface = 0xFF111111u,
    surfaceWarm = 0xFF211022u,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xFFE5E7EBu,
    muted = 0xFF9CA3AFu,
    border = 0xFF2B2B2Bu,
    accent = 0xFFFF00A8u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF22C55Eu,
    warning = 0xFFFACC15u,
    danger = 0xFFEF4444u,
    fontDisplay = "PolySans",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 200,
    containerMax = 1240.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
