// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val tomModernDesignSystem = AnduraDesignSystem(
    id = "tom-modern",
    name = "Tom Modern Design",
    category = "Starter",
    description = "Editorial-technical design system. Neutral canvas, single vermillion accent, sharp corners, Geist typography, hard shadows, structured composition.",
    nativeDark = false,
    background = 0xFFFAFAFAu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFFFFFu,
    foreground = 0xFF27272Au,
    foregroundSecondary = 0xFF52525Bu,
    muted = 0xFF71717Au,
    border = 0xFF969696u,
    accent = 0xFFFF5A00u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Geist Sans",
    fontBody = "Geist Sans",
    textBase = 15.0f,
    radiusSm = 0.0f,
    radiusMd = 0.0f,
    radiusLg = 0.0f,
    radiusPill = 0.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1240.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 0,
)
