// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val tradingTerminalDesignSystem = AnduraDesignSystem(
    id = "trading-terminal",
    name = "Trading Terminal Design System",
    category = "Themed & Unique",
    description = "Bundled Open Design package for Trading Terminal Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF070B12u,
    surface = 0xFF101826u,
    surfaceWarm = 0xFF162238u,
    foreground = 0xFFF8FAFCu,
    foregroundSecondary = 0xFFCBD5E1u,
    muted = 0xFF8492A6u,
    border = 0xFF263246u,
    accent = 0xFF38BDF8u,
    accentOn = 0xFF03111Au,
    success = 0xFF22C55Eu,
    warning = 0xFFF59E0Bu,
    danger = 0xFFEF4444u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 14.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 90,
    motionBaseMs = 160,
    containerMax = 1320.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
