// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val uberDesignSystem = AnduraDesignSystem(
    id = "uber",
    name = "Uber",
    category = "Media & Consumer",
    description = "Bundled Open Design package for Uber, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFF8F8F8u,
    foreground = 0xFF000000u,
    foregroundSecondary = 0xFF000000u,
    muted = 0xFF4B4B4Bu,
    border = 0xFF000000u,
    accent = 0xFF000000u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "UberMove",
    fontBody = "UberMoveText",
    textBase = 16.0f,
    radiusSm = 999.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1136.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"),
    sourceClassCount = 19,
)
