// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val urduDesignSystem = AnduraDesignSystem(
    id = "urdu",
    name = "Urdu Modern (Indus Script System)",
    category = "Editorial / Personal / Publication",
    description = "Bundled Open Design package for Urdu Modern (Indus Script System), derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF3FAF4u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFE5F5E7u,
    foreground = 0xFF15261Au,
    foregroundSecondary = 0xFF38513Eu,
    muted = 0xFF6B7D70u,
    border = 0xFFD4E3D7u,
    accent = 0xFF1F8F46u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFD97706u,
    danger = 0xFFDC2626u,
    fontDisplay = "Georgia",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 10.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
