// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val vercelDesignSystem = AnduraDesignSystem(
    id = "vercel",
    name = "Vercel",
    category = "Developer Tools",
    description = "Bundled Open Design package for Vercel, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFFFFFu,
    foreground = 0xFF171717u,
    foregroundSecondary = 0xFF4D4D4Du,
    muted = 0xFF666666u,
    border = 0x14000000u,
    accent = 0xFF0070F3u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Geist",
    fontBody = "Geist",
    textBase = 16.0f,
    radiusSm = 6.0f,
    radiusMd = 8.0f,
    radiusLg = 12.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 38,
)
