// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val vodafoneDesignSystem = AnduraDesignSystem(
    id = "vodafone",
    name = "Vodafone",
    category = "Media & Consumer",
    description = "Bundled Open Design package for Vodafone, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF4F4F4u,
    surfaceWarm = 0xFFFFF1F1u,
    foreground = 0xFF1F1F1Fu,
    foregroundSecondary = 0xFF4A4D4Eu,
    muted = 0xFF6F7375u,
    border = 0xFFD8D8D8u,
    accent = 0xFFE60000u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF008A00u,
    warning = 0xFFF5B400u,
    danger = 0xFFBD0000u,
    fontDisplay = "Vodafone",
    fontBody = "Vodafone",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 16.0f,
    radiusLg = 24.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 220,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
