// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val voltagentDesignSystem = AnduraDesignSystem(
    id = "voltagent",
    name = "VoltAgent",
    category = "AI & LLM",
    description = "Bundled Open Design package for VoltAgent, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF07110Cu,
    surface = 0xFF101C16u,
    surfaceWarm = 0xFF14281Eu,
    foreground = 0xFFF4FFF8u,
    foregroundSecondary = 0xFFC8DFD0u,
    muted = 0xFF8BA493u,
    border = 0xFF254132u,
    accent = 0xFF7CFF6Bu,
    accentOn = 0xFF07110Cu,
    success = 0xFF52E875u,
    warning = 0xFFFACC15u,
    danger = 0xFFFB7185u,
    fontDisplay = "Inter",
    fontBody = "Inter",
    textBase = 15.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 18.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 210,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
