// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val warpDesignSystem = AnduraDesignSystem(
    id = "warp",
    name = "Warp",
    category = "Developer Tools",
    description = "Bundled Open Design package for Warp, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF161412u,
    surface = 0xFF1F1D1Bu,
    surfaceWarm = 0xFF1F1D1Bu,
    foreground = 0xFFFAF9F6u,
    foregroundSecondary = 0xFFAFAEACu,
    muted = 0xFF868584u,
    border = 0x59E2E2E2u,
    accent = 0xFF353534u,
    accentOn = 0xFFAFAEACu,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "Matter Regular",
    fontBody = "Matter Regular",
    textBase = 18.0f,
    radiusSm = 6.0f,
    radiusMd = 12.0f,
    radiusLg = 14.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1500.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 28,
)
