// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val webexDesignSystem = AnduraDesignSystem(
    id = "webex",
    name = "Webex",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Webex, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF6F8FBu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFEEF8F6u,
    foreground = 0xFF0F172Au,
    foregroundSecondary = 0xFF334155u,
    muted = 0xFF64748Bu,
    border = 0xFFDBE4EEu,
    accent = 0xFF00A3A6u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF22C55Eu,
    warning = 0xFFF59E0Bu,
    danger = 0xFFE11D48u,
    fontDisplay = "CiscoSansTT",
    fontBody = "CiscoSansTT",
    textBase = 16.0f,
    radiusSm = 12.0f,
    radiusMd = 18.0f,
    radiusLg = 28.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 160,
    motionBaseMs = 240,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
