// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val webflowDesignSystem = AnduraDesignSystem(
    id = "webflow",
    name = "Webflow",
    category = "Design & Creative",
    description = "Bundled Open Design package for Webflow, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFFFFFu,
    foreground = 0xFF080808u,
    foregroundSecondary = 0xFF363636u,
    muted = 0xFF5A5A5Au,
    border = 0xFFD8D8D8u,
    accent = 0xFF146EF5u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF00D722u,
    warning = 0xFFFFAE13u,
    danger = 0xFFEE1D36u,
    fontDisplay = "WF Visual Sans Variable",
    fontBody = "WF Visual Sans Variable",
    textBase = 16.0f,
    radiusSm = 4.0f,
    radiusMd = 4.0f,
    radiusLg = 8.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 28,
)
