// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val wechatDesignSystem = AnduraDesignSystem(
    id = "wechat",
    name = "WeChat Design System",
    category = "Social & Messaging",
    description = "Bundled Open Design package for WeChat Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFEDEDEDu,
    surface = 0xFFF7F7F7u,
    surfaceWarm = 0xFFF7F7F7u,
    foreground = 0xFF1A1A1Au,
    foregroundSecondary = 0xFF1A1A1Au,
    muted = 0xFF888888u,
    border = 0xFFE0E0E0u,
    accent = 0xFF07C160u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF07C160u,
    warning = 0xFFFAB702u,
    danger = 0xFFFA5151u,
    fontDisplay = "-apple-system",
    fontBody = "-apple-system",
    textBase = 15.0f,
    radiusSm = 4.0f,
    radiusMd = 8.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 100,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 34,
)
