// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val wiredDesignSystem = AnduraDesignSystem(
    id = "wired",
    name = "WIRED",
    category = "Media & Consumer",
    description = "Bundled Open Design package for WIRED, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFF2F2F2u,
    surfaceWarm = 0xFFFFF0F0u,
    foreground = 0xFF000000u,
    foregroundSecondary = 0xFF333333u,
    muted = 0xFF666666u,
    border = 0xFFD0D0D0u,
    accent = 0xFFE10600u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF0F8A3Bu,
    warning = 0xFFF5A400u,
    danger = 0xFFC40000u,
    fontDisplay = "Druk Wide",
    fontBody = "Exchange",
    textBase = 17.0f,
    radiusSm = 0.0f,
    radiusMd = 0.0f,
    radiusLg = 0.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 120,
    motionBaseMs = 200,
    containerMax = 1180.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
