// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val wiseDesignSystem = AnduraDesignSystem(
    id = "wise",
    name = "Wise",
    category = "Fintech & Crypto",
    description = "Bundled Open Design package for Wise, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFFFFFu,
    surface = 0xFFE8EBE6u,
    surfaceWarm = 0xFFE8EBE6u,
    foreground = 0xFF0E0F0Cu,
    foregroundSecondary = 0xFF0E0F0Cu,
    muted = 0xFF868685u,
    border = 0x1F0E0F0Cu,
    accent = 0xFF9FE870u,
    accentOn = 0xFF163300u,
    success = 0xFF054D28u,
    warning = 0xFFFFD11Au,
    danger = 0xFFD03238u,
    fontDisplay = "Wise Sans",
    fontBody = "Inter",
    textBase = 18.0f,
    radiusSm = 16.0f,
    radiusMd = 30.0f,
    radiusLg = 40.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1280.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 28,
)
