// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val xAiDesignSystem = AnduraDesignSystem(
    id = "x-ai",
    name = "xAI",
    category = "AI & LLM",
    description = "Bundled Open Design package for xAI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = true,
    background = 0xFF1F2228u,
    surface = 0x08FFFFFFu,
    surfaceWarm = 0x0DFFFFFFu,
    foreground = 0xFFFFFFFFu,
    foregroundSecondary = 0xB2FFFFFFu,
    muted = 0x80FFFFFFu,
    border = 0x1AFFFFFFu,
    accent = 0xFFFFFFFFu,
    accentOn = 0xFF1F2228u,
    success = 0xFF16A34Au,
    warning = 0xFFEAB308u,
    danger = 0xFFDC2626u,
    fontDisplay = "GeistMono",
    fontBody = "universalSans",
    textBase = 16.0f,
    radiusSm = 0.0f,
    radiusMd = 0.0f,
    radiusLg = 4.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 23,
)
