// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val xiaohongshuDesignSystem = AnduraDesignSystem(
    id = "xiaohongshu",
    name = "Xiaohongshu",
    category = "Media & Consumer",
    description = "Bundled Open Design package for Xiaohongshu, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFF5F5F5u,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFAFAFAu,
    foreground = 0xCC000000u,
    foregroundSecondary = 0x9E000000u,
    muted = 0x73000000u,
    border = 0x14000000u,
    accent = 0xFFFF2442u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF02B940u,
    warning = 0xFFFF7D03u,
    danger = 0xFFFF2442u,
    fontDisplay = "PingFang SC",
    fontBody = "PingFang SC",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 16.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 150,
    motionBaseMs = 200,
    containerMax = 1200.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"),
    sourceClassCount = 49,
)
