// GENERATED FILE - DO NOT EDIT.
package com.andura.ui.designsystems

internal val zapierDesignSystem = AnduraDesignSystem(
    id = "zapier",
    name = "Zapier",
    category = "Productivity & SaaS",
    description = "Bundled Open Design package for Zapier, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
    nativeDark = false,
    background = 0xFFFFF7EDu,
    surface = 0xFFFFFFFFu,
    surfaceWarm = 0xFFFFEDD5u,
    foreground = 0xFF2D2A26u,
    foregroundSecondary = 0xFF574F45u,
    muted = 0xFF7C6F64u,
    border = 0xFFEADFD3u,
    accent = 0xFFFF4F00u,
    accentOn = 0xFFFFFFFFu,
    success = 0xFF15803Du,
    warning = 0xFFD97706u,
    danger = 0xFFDC2626u,
    fontDisplay = "Degular",
    fontBody = "Inter",
    textBase = 16.0f,
    radiusSm = 8.0f,
    radiusMd = 12.0f,
    radiusLg = 20.0f,
    radiusPill = 9999.0f,
    space1 = 4.0f,
    space2 = 8.0f,
    space3 = 12.0f,
    space4 = 16.0f,
    space6 = 24.0f,
    space8 = 32.0f,
    motionFastMs = 140,
    motionBaseMs = 220,
    containerMax = 1160.0f,
    componentGroups = listOf("buttons", "inputs", "cards", "badges", "links", "typography", "layout"),
    sourceClassCount = 26,
)
