// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const agenticDesignSystem = {
  id: "agentic",
  name: "Agentic",
  category: "Themed & Unique",
  description: "Bundled Open Design package for Agentic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#0b1020",
  surface: "#131b2f",
  surfaceWarm: "#182343",
  foreground: "#f8fafc",
  foregroundSecondary: "#cbd5e1",
  muted: "#8ea0b8",
  border: "#293653",
  accent: "#60a5fa",
  accentOn: "#06111f",
  success: "#22c55e",
  warning: "#fbbf24",
  danger: "#fb7185",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 15.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 20.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 130,
  motionBaseMs: 220,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
