// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const airbnbDesignSystem = {
  id: "airbnb",
  name: "Airbnb",
  category: "E-Commerce & Retail",
  description: "Bundled Open Design package for Airbnb, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#f7f7f7",
  foreground: "#222222",
  foregroundSecondary: "#3f3f3f",
  muted: "#6a6a6a",
  border: "#dddddd",
  accent: "#ff385c",
  accentOn: "#ffffff",
  success: "#008a05",
  warning: "#c47700",
  danger: "#c13515",
  fontDisplay: "Airbnb Cereal VF",
  fontBody: "Airbnb Cereal VF",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 14.0,
  radiusLg: 20.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 67,
} as const satisfies AnduraDesignSystem;
