// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const airtableDesignSystem = {
  id: "airtable",
  name: "Airtable",
  category: "Design & Creative",
  description: "Bundled Open Design package for Airtable, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#ffffff",
  foreground: "#181d26",
  foregroundSecondary: "#333333",
  muted: "#040e20b0",
  border: "#e0e2e6",
  accent: "#1b61c9",
  accentOn: "#ffffff",
  success: "#006400",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Haas Groot Disp",
  fontBody: "Haas",
  textBase: 16.0,
  radiusSm: 12.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 35,
} as const satisfies AnduraDesignSystem;
