// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const antDesignSystem = {
  id: "ant",
  name: "Ant",
  category: "Professional & Corporate",
  description: "Bundled Open Design package for Ant, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f7f8fa",
  surfaceWarm: "#fff1f0",
  foreground: "#1f1f1f",
  foregroundSecondary: "#4b5563",
  muted: "#697386",
  border: "#d9dce3",
  accent: "#d32029",
  accentOn: "#ffffff",
  success: "#22a06b",
  warning: "#faad14",
  danger: "#cf1322",
  fontDisplay: "Ant Sans",
  fontBody: "Ant Sans",
  textBase: 16.0,
  radiusSm: 6.0,
  radiusMd: 10.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 140,
  motionBaseMs: 220,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
