// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const appleDesignSystem = {
  id: "apple",
  name: "Apple",
  category: "Media & Consumer",
  description: "Bundled Open Design package for Apple, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f5f5f7",
  surfaceWarm: "#fbfbfd",
  foreground: "#1d1d1f",
  foregroundSecondary: "#424245",
  muted: "#6e6e73",
  border: "#d2d2d7",
  accent: "#0071e3",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "SF Pro Display",
  fontBody: "SF Pro Text",
  textBase: 17.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 18.0,
  radiusPill: 980.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 220,
  containerMax: 1024.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 35,
} as const satisfies AnduraDesignSystem;
