// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const applicationDesignSystem = {
  id: "application",
  name: "Application",
  category: "Professional & Corporate",
  description: "Bundled Open Design package for Application, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f6f7f9",
  surface: "#ffffff",
  surfaceWarm: "#eef4ff",
  foreground: "#172033",
  foregroundSecondary: "#3b4658",
  muted: "#6b7689",
  border: "#d8dee8",
  accent: "#2563eb",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#f59e0b",
  danger: "#dc2626",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 18.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 140,
  motionBaseMs: 220,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
