// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const arcDesignSystem = {
  id: "arc",
  name: "Arc Browser",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Arc Browser, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fdf3ec",
  surface: "#ffffff",
  surfaceWarm: "#fff4ea",
  foreground: "#1a1a1f",
  foregroundSecondary: "#54545a",
  muted: "#8c8c93",
  border: "#ece5db",
  accent: "#ff5f5f",
  accentOn: "#ffffff",
  success: "#48bb78",
  warning: "#f6ad55",
  danger: "#f56565",
  fontDisplay: "Argent CF",
  fontBody: "Inter",
  textBase: 15.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 200,
  motionBaseMs: 320,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 27,
} as const satisfies AnduraDesignSystem;
