// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const binanceDesignSystem = {
  id: "binance",
  name: "Binance.US",
  category: "Fintech & Crypto",
  description: "Bundled Open Design package for Binance.US, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#f5f5f5",
  foreground: "#1e2026",
  foregroundSecondary: "#32313a",
  muted: "#848e9c",
  border: "#e6e8ea",
  accent: "#f0b90b",
  accentOn: "#1e2026",
  success: "#0ecb81",
  warning: "#eab308",
  danger: "#f6465d",
  fontDisplay: "BinancePlex",
  fontBody: "BinancePlex",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 46,
} as const satisfies AnduraDesignSystem;
