// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const bmwMDesignSystem = {
  id: "bmw-m",
  name: "BMW M",
  category: "Automotive",
  description: "Bundled Open Design package for BMW M, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f7f8fa",
  surface: "#ffffff",
  surfaceWarm: "#eef3f8",
  foreground: "#111827",
  foregroundSecondary: "#334155",
  muted: "#64748b",
  border: "#d7dee8",
  accent: "#0066b1",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#f59e0b",
  danger: "#e4002b",
  fontDisplay: "BMWTypeNext",
  fontBody: "BMWTypeNext",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 14.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 130,
  motionBaseMs: 220,
  containerMax: 1220.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
