// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const bmwDesignSystem = {
  id: "bmw",
  name: "BMW",
  category: "Automotive",
  description: "Bundled Open Design package for BMW, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f5f5f5",
  surfaceWarm: "#f5f5f5",
  foreground: "#262626",
  foregroundSecondary: "#262626",
  muted: "#757575",
  border: "#e0e0e0",
  accent: "#1c69d4",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "BMWTypeNextLatin Light",
  fontBody: "BMWTypeNextLatin",
  textBase: 16.0,
  radiusSm: 0.0,
  radiusMd: 0.0,
  radiusLg: 0.0,
  radiusPill: 0.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1440.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"],
  sourceClassCount: 28,
} as const satisfies AnduraDesignSystem;
