// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const boldDesignSystem = {
  id: "bold",
  name: "Bold",
  category: "Bold & Expressive",
  description: "Bundled Open Design package for Bold, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f7f7f7",
  surfaceWarm: "#eeeeee",
  foreground: "#111111",
  foregroundSecondary: "#3a3a3a",
  muted: "#707070",
  border: "#d9d9d9",
  accent: "#111111",
  accentOn: "#ffffff",
  success: "#168a46",
  warning: "#b7791f",
  danger: "#c53030",
  fontDisplay: "Arial Black",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
