// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const brutalismDesignSystem = {
  id: "brutalism",
  name: "Brutalism",
  category: "Bold & Expressive",
  description: "Bundled Open Design package for Brutalism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f5f1e8",
  surface: "#ffffff",
  surfaceWarm: "#ffef5a",
  foreground: "#000000",
  foregroundSecondary: "#222222",
  muted: "#555555",
  border: "#000000",
  accent: "#ffef5a",
  accentOn: "#000000",
  success: "#00b050",
  warning: "#ff8c00",
  danger: "#ff2b2b",
  fontDisplay: "Arial Black",
  fontBody: "Arial",
  textBase: 17.0,
  radiusSm: 0.0,
  radiusMd: 0.0,
  radiusLg: 0.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 90,
  motionBaseMs: 140,
  containerMax: 1160.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
