// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const bugattiDesignSystem = {
  id: "bugatti",
  name: "Bugatti",
  category: "Automotive",
  description: "Bundled Open Design package for Bugatti, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#07111f",
  surface: "#101d2f",
  surfaceWarm: "#16283f",
  foreground: "#f7fbff",
  foregroundSecondary: "#d6e0ee",
  muted: "#8fa1b7",
  border: "#2c405c",
  accent: "#1b4d8f",
  accentOn: "#ffffff",
  success: "#2fbf71",
  warning: "#d9b45f",
  danger: "#c1121f",
  fontDisplay: "Bugatti Display",
  fontBody: "Avenir Next",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 14.0,
  radiusLg: 22.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 170,
  motionBaseMs: 280,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
