// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const calDesignSystem = {
  id: "cal",
  name: "Cal.com",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Cal.com, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#ffffff",
  foreground: "#242424",
  foregroundSecondary: "#111111",
  muted: "#898989",
  border: "#222a3514",
  accent: "#0099ff",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Cal Sans",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
