// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const canvaDesignSystem = {
  id: "canva",
  name: "Canva",
  category: "Design & Creative",
  description: "Bundled Open Design package for Canva, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f4f5f7",
  surfaceWarm: "#f4f5f7",
  foreground: "#0e1318",
  foregroundSecondary: "#3c4043",
  muted: "#5f6368",
  border: "#e1e3e6",
  accent: "#7d2ae8",
  accentOn: "#ffffff",
  success: "#00b894",
  warning: "#ffb020",
  danger: "#ff5757",
  fontDisplay: "Canva Sans",
  fontBody: "Canva Sans",
  textBase: 14.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 180,
  motionBaseMs: 280,
  containerMax: 1320.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 32,
} as const satisfies AnduraDesignSystem;
