// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const designSystemsChunk07 = [
  {
    id: "spacious", name: "Spacious", category: "Layout & Structure",
    description: "Bundled Open Design package for Spacious, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#faf3df", surface: "#fffaf0", surfaceWarm: "#efe0bd",
    foreground: "#211b12", foregroundSecondary: "#504737", muted: "#7c7160", border: "#ddd0b4",
    accent: "#8f5d24", accentOn: "#ffffff", success: "#5b8d42", warning: "#c27b22", danger: "#a64036",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 17.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "spotify", name: "Spotify", category: "Media & Consumer",
    description: "Bundled Open Design package for Spotify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#121212", surface: "#181818", surfaceWarm: "#1f1f1f",
    foreground: "#ffffff", foregroundSecondary: "#fdfdfd", muted: "#b3b3b3", border: "#4d4d4d",
    accent: "#1ed760", accentOn: "#000000", success: "#1ed760", warning: "#ffa42b", danger: "#f3727f",
    fontDisplay: "SpotifyMixUITitle", fontBody: "SpotifyMixUI", textBase: 16.0,
    radiusSm: 9999.0, radiusMd: 6.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "cards", "links", "icons", "typography", "layout"], sourceClassCount: 20,
  },
  {
    id: "starbucks", name: "Starbucks", category: "E-Commerce & Retail",
    description: "Bundled Open Design package for Starbucks, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f2f0eb", surface: "#ffffff", surfaceWarm: "#edebe9",
    foreground: "#000000de", foregroundSecondary: "#33433d", muted: "#00000094", border: "#d6dbde",
    accent: "#00754a", accentOn: "#ffffff", success: "#16a34a", warning: "#fbbc05", danger: "#c82014",
    fontDisplay: "SoDoSans", fontBody: "SoDoSans", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 12.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1440.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 30,
  },
  {
    id: "storytelling", name: "Storytelling", category: "Creative & Artistic",
    description: "Bundled Open Design package for Storytelling, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf6ee", surface: "#fffdf8", surfaceWarm: "#f1e3cf",
    foreground: "#201914", foregroundSecondary: "#4c4037", muted: "#7a6d63", border: "#ded2c3",
    accent: "#9b5b32", accentOn: "#ffffff", success: "#4f8a4f", warning: "#c9822f", danger: "#b33a3a",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 17.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "stripe", name: "Stripe", category: "Fintech & Crypto",
    description: "Bundled Open Design package for Stripe, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#f6f9fc",
    foreground: "#061b31", foregroundSecondary: "#273951", muted: "#64748d", border: "#e5edf5",
    accent: "#533afd", accentOn: "#ffffff", success: "#15be53", warning: "#9b6829", danger: "#ea2261",
    fontDisplay: "sohne-var", fontBody: "sohne-var", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 6.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1080.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 45,
  },
  {
    id: "supabase", name: "Supabase", category: "Backend & Data",
    description: "Bundled Open Design package for Supabase, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#171717", surface: "#1c1c1c", surfaceWarm: "#1c1c1c",
    foreground: "#fafafa", foregroundSecondary: "#b4b4b4", muted: "#898989", border: "#2e2e2e",
    accent: "#3ecf8e", accentOn: "#0f0f0f", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Circular", fontBody: "Circular", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 8.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 30,
  },
  {
    id: "superhuman", name: "Superhuman", category: "Developer Tools",
    description: "Bundled Open Design package for Superhuman, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#e9e5dd",
    foreground: "#292827", foregroundSecondary: "#292827", muted: "#6f6c69", border: "#dcd7d3",
    accent: "#cbb7fb", accentOn: "#292827", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Super Sans VF", fontBody: "Super Sans VF", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 8.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 31,
  },
  {
    id: "tesla", name: "Tesla", category: "Automotive",
    description: "Bundled Open Design package for Tesla, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f4f4f4", surfaceWarm: "#f4f4f4",
    foreground: "#171a20", foregroundSecondary: "#393c41", muted: "#5c5e62", border: "#d0d1d2",
    accent: "#3e6ae1", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Universal Sans Display", fontBody: "Universal Sans Text", textBase: 14.0,
    radiusSm: 4.0, radiusMd: 12.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 250, motionBaseMs: 330, containerMax: 1383.0,
    componentGroups: ["buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 37,
  },
  {
    id: "tetris", name: "Tetris", category: "Themed & Unique",
    description: "Bundled Open Design package for Tetris, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#050816", surface: "#10162a", surfaceWarm: "#17203a",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#94a3b8", border: "#26324f",
    accent: "#00f0f0", accentOn: "#061018", success: "#00f000", warning: "#f0f000", danger: "#f00000",
    fontDisplay: "Press Start 2P", fontBody: "Inter", textBase: 14.0,
    radiusSm: 0.0, radiusMd: 0.0, radiusLg: 4.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 80, motionBaseMs: 140, containerMax: 1100.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "theverge", name: "The Verge", category: "Media & Consumer",
    description: "Bundled Open Design package for The Verge, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#050505", surface: "#111111", surfaceWarm: "#211022",
    foreground: "#ffffff", foregroundSecondary: "#e5e7eb", muted: "#9ca3af", border: "#2b2b2b",
    accent: "#ff00a8", accentOn: "#ffffff", success: "#22c55e", warning: "#facc15", danger: "#ef4444",
    fontDisplay: "PolySans", fontBody: "Inter", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 200, containerMax: 1240.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "together-ai", name: "Together AI", category: "AI & LLM",
    description: "Bundled Open Design package for Together AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#ffffff",
    foreground: "#000000", foregroundSecondary: "#00000099", muted: "#666666", border: "#ebebeb",
    accent: "#010120", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "The Future", fontBody: "The Future", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"], sourceClassCount: 25,
  },
  {
    id: "tom-modern", name: "Tom Modern Design", category: "Starter",
    description: "Editorial-technical design system. Neutral canvas, single vermillion accent, sharp corners, Geist typography, hard shadows, structured composition.", brightness: "light",
    background: "#fafafa", surface: "#ffffff", surfaceWarm: "#ffffff",
    foreground: "#27272a", foregroundSecondary: "#52525b", muted: "#71717a", border: "#969696",
    accent: "#ff5a00", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Geist Sans", fontBody: "Geist Sans", textBase: 15.0,
    radiusSm: 0.0, radiusMd: 0.0, radiusLg: 0.0, radiusPill: 0.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1240.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 0,
  },
  {
    id: "totality-festival", name: "Totality Festival", category: "Themed & Unique",
    description: "Bundled Open Design package for Totality Festival, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#070711", surface: "#111126", surfaceWarm: "#1e1540",
    foreground: "#f8f7ff", foregroundSecondary: "#d6ccff", muted: "#9d8ad4", border: "#34265e",
    accent: "#c084fc", accentOn: "#13051f", success: "#39ff88", warning: "#fff34d", danger: "#ff4d8d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "trading-terminal", name: "Trading Terminal Design System", category: "Themed & Unique",
    description: "Bundled Open Design package for Trading Terminal Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#070b12", surface: "#101826", surfaceWarm: "#162238",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#8492a6", border: "#263246",
    accent: "#38bdf8", accentOn: "#03111a", success: "#22c55e", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 14.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 90, motionBaseMs: 160, containerMax: 1320.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "uber", name: "Uber", category: "Media & Consumer",
    description: "Bundled Open Design package for Uber, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#f8f8f8",
    foreground: "#000000", foregroundSecondary: "#000000", muted: "#4b4b4b", border: "#000000",
    accent: "#000000", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "UberMove", fontBody: "UberMoveText", textBase: 16.0,
    radiusSm: 999.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1136.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"], sourceClassCount: 19,
  },
  {
    id: "urdu", name: "Urdu Modern (Indus Script System)", category: "Editorial / Personal / Publication",
    description: "Bundled Open Design package for Urdu Modern (Indus Script System), derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f3faf4", surface: "#ffffff", surfaceWarm: "#e5f5e7",
    foreground: "#15261a", foregroundSecondary: "#38513e", muted: "#6b7d70", border: "#d4e3d7",
    accent: "#1f8f46", accentOn: "#ffffff", success: "#16a34a", warning: "#d97706", danger: "#dc2626",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "vercel", name: "Vercel", category: "Developer Tools",
    description: "Bundled Open Design package for Vercel, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#ffffff",
    foreground: "#171717", foregroundSecondary: "#4d4d4d", muted: "#666666", border: "#00000014",
    accent: "#0070f3", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Geist", fontBody: "Geist", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 38,
  },
  {
    id: "vibrant", name: "Vibrant", category: "Bold & Expressive",
    description: "Bundled Open Design package for Vibrant, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff8d7", surface: "#ffffff", surfaceWarm: "#ffef9f",
    foreground: "#1d1836", foregroundSecondary: "#4c426c", muted: "#796f91", border: "#eadfba",
    accent: "#ff6b00", accentOn: "#ffffff", success: "#2e9d57", warning: "#ffb020", danger: "#e5484d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "vintage", name: "Vintage", category: "Retro & Nostalgic",
    description: "Bundled Open Design package for Vintage, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#faf3df", surface: "#fffaf0", surfaceWarm: "#efe0bd",
    foreground: "#211b12", foregroundSecondary: "#504737", muted: "#7c7160", border: "#ddd0b4",
    accent: "#8f5d24", accentOn: "#ffffff", success: "#5b8d42", warning: "#c27b22", danger: "#a64036",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 17.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "vodafone", name: "Vodafone", category: "Media & Consumer",
    description: "Bundled Open Design package for Vodafone, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f4f4f4", surfaceWarm: "#fff1f1",
    foreground: "#1f1f1f", foregroundSecondary: "#4a4d4e", muted: "#6f7375", border: "#d8d8d8",
    accent: "#e60000", accentOn: "#ffffff", success: "#008a00", warning: "#f5b400", danger: "#bd0000",
    fontDisplay: "Vodafone", fontBody: "Vodafone", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 220, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
] as const satisfies readonly AnduraDesignSystem[];
