// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const designSystemsChunk01 = [
  {
    id: "agentic", name: "Agentic", category: "Themed & Unique",
    description: "Bundled Open Design package for Agentic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#0b1020", surface: "#131b2f", surfaceWarm: "#182343",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#8ea0b8", border: "#293653",
    accent: "#60a5fa", accentOn: "#06111f", success: "#22c55e", warning: "#fbbf24", danger: "#fb7185",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 15.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 20.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 130, motionBaseMs: 220, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "airbnb", name: "Airbnb", category: "E-Commerce & Retail",
    description: "Bundled Open Design package for Airbnb, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#f7f7f7",
    foreground: "#222222", foregroundSecondary: "#3f3f3f", muted: "#6a6a6a", border: "#dddddd",
    accent: "#ff385c", accentOn: "#ffffff", success: "#008a05", warning: "#c47700", danger: "#c13515",
    fontDisplay: "Airbnb Cereal VF", fontBody: "Airbnb Cereal VF", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 14.0, radiusLg: 20.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 67,
  },
  {
    id: "airtable", name: "Airtable", category: "Design & Creative",
    description: "Bundled Open Design package for Airtable, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#ffffff",
    foreground: "#181d26", foregroundSecondary: "#333333", muted: "#040e20b0", border: "#e0e2e6",
    accent: "#1b61c9", accentOn: "#ffffff", success: "#006400", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Haas Groot Disp", fontBody: "Haas", textBase: 16.0,
    radiusSm: 12.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 35,
  },
  {
    id: "ant", name: "Ant", category: "Professional & Corporate",
    description: "Bundled Open Design package for Ant, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f7f8fa", surfaceWarm: "#fff1f0",
    foreground: "#1f1f1f", foregroundSecondary: "#4b5563", muted: "#697386", border: "#d9dce3",
    accent: "#d32029", accentOn: "#ffffff", success: "#22a06b", warning: "#faad14", danger: "#cf1322",
    fontDisplay: "Ant Sans", fontBody: "Ant Sans", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 10.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 140, motionBaseMs: 220, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "apple", name: "Apple", category: "Media & Consumer",
    description: "Bundled Open Design package for Apple, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f5f5f7", surfaceWarm: "#fbfbfd",
    foreground: "#1d1d1f", foregroundSecondary: "#424245", muted: "#6e6e73", border: "#d2d2d7",
    accent: "#0071e3", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "SF Pro Display", fontBody: "SF Pro Text", textBase: 17.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 18.0, radiusPill: 980.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 220, containerMax: 1024.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 35,
  },
  {
    id: "application", name: "Application", category: "Professional & Corporate",
    description: "Bundled Open Design package for Application, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f6f7f9", surface: "#ffffff", surfaceWarm: "#eef4ff",
    foreground: "#172033", foregroundSecondary: "#3b4658", muted: "#6b7689", border: "#d8dee8",
    accent: "#2563eb", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#dc2626",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 18.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 140, motionBaseMs: 220, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "arc", name: "Arc Browser", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Arc Browser, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fdf3ec", surface: "#ffffff", surfaceWarm: "#fff4ea",
    foreground: "#1a1a1f", foregroundSecondary: "#54545a", muted: "#8c8c93", border: "#ece5db",
    accent: "#ff5f5f", accentOn: "#ffffff", success: "#48bb78", warning: "#f6ad55", danger: "#f56565",
    fontDisplay: "Argent CF", fontBody: "Inter", textBase: 15.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 200, motionBaseMs: 320, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 27,
  },
  {
    id: "artistic", name: "Artistic", category: "Creative & Artistic",
    description: "Bundled Open Design package for Artistic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf6ee", surface: "#fffdf8", surfaceWarm: "#f1e3cf",
    foreground: "#201914", foregroundSecondary: "#4c4037", muted: "#7a6d63", border: "#ded2c3",
    accent: "#9b5b32", accentOn: "#ffffff", success: "#4f8a4f", warning: "#c9822f", danger: "#b33a3a",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 17.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "atelier-zero", name: "Atelier Zero", category: "Editorial · Studio",
    description: "Bundled Open Design package for Atelier Zero, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f7f7f7", surfaceWarm: "#eeeeee",
    foreground: "#111111", foregroundSecondary: "#3a3a3a", muted: "#707070", border: "#d9d9d9",
    accent: "#111111", accentOn: "#ffffff", success: "#168a46", warning: "#b7791f", danger: "#c53030",
    fontDisplay: "Helvetica Neue", fontBody: "Helvetica Neue", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "bento", name: "Bento", category: "Layout & Structure",
    description: "Bundled Open Design package for Bento, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f8ff", surface: "#ffffff", surfaceWarm: "#eaf1ff",
    foreground: "#101828", foregroundSecondary: "#344054", muted: "#667085", border: "#d7e0ef",
    accent: "#2563eb", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "binance", name: "Binance.US", category: "Fintech & Crypto",
    description: "Bundled Open Design package for Binance.US, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#f5f5f5",
    foreground: "#1e2026", foregroundSecondary: "#32313a", muted: "#848e9c", border: "#e6e8ea",
    accent: "#f0b90b", accentOn: "#1e2026", success: "#0ecb81", warning: "#eab308", danger: "#f6465d",
    fontDisplay: "BinancePlex", fontBody: "BinancePlex", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 46,
  },
  {
    id: "bmw", name: "BMW", category: "Automotive",
    description: "Bundled Open Design package for BMW, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f5f5f5", surfaceWarm: "#f5f5f5",
    foreground: "#262626", foregroundSecondary: "#262626", muted: "#757575", border: "#e0e0e0",
    accent: "#1c69d4", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "BMWTypeNextLatin Light", fontBody: "BMWTypeNextLatin", textBase: 16.0,
    radiusSm: 0.0, radiusMd: 0.0, radiusLg: 0.0, radiusPill: 0.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1440.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"], sourceClassCount: 28,
  },
  {
    id: "bmw-m", name: "BMW M", category: "Automotive",
    description: "Bundled Open Design package for BMW M, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7f8fa", surface: "#ffffff", surfaceWarm: "#eef3f8",
    foreground: "#111827", foregroundSecondary: "#334155", muted: "#64748b", border: "#d7dee8",
    accent: "#0066b1", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#e4002b",
    fontDisplay: "BMWTypeNext", fontBody: "BMWTypeNext", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 14.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 130, motionBaseMs: 220, containerMax: 1220.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "bold", name: "Bold", category: "Bold & Expressive",
    description: "Bundled Open Design package for Bold, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f7f7f7", surfaceWarm: "#eeeeee",
    foreground: "#111111", foregroundSecondary: "#3a3a3a", muted: "#707070", border: "#d9d9d9",
    accent: "#111111", accentOn: "#ffffff", success: "#168a46", warning: "#b7791f", danger: "#c53030",
    fontDisplay: "Arial Black", fontBody: "Inter", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "brutalism", name: "Brutalism", category: "Bold & Expressive",
    description: "Bundled Open Design package for Brutalism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f1e8", surface: "#ffffff", surfaceWarm: "#ffef5a",
    foreground: "#000000", foregroundSecondary: "#222222", muted: "#555555", border: "#000000",
    accent: "#ffef5a", accentOn: "#000000", success: "#00b050", warning: "#ff8c00", danger: "#ff2b2b",
    fontDisplay: "Arial Black", fontBody: "Arial", textBase: 17.0,
    radiusSm: 0.0, radiusMd: 0.0, radiusLg: 0.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 90, motionBaseMs: 140, containerMax: 1160.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "bugatti", name: "Bugatti", category: "Automotive",
    description: "Bundled Open Design package for Bugatti, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#07111f", surface: "#101d2f", surfaceWarm: "#16283f",
    foreground: "#f7fbff", foregroundSecondary: "#d6e0ee", muted: "#8fa1b7", border: "#2c405c",
    accent: "#1b4d8f", accentOn: "#ffffff", success: "#2fbf71", warning: "#d9b45f", danger: "#c1121f",
    fontDisplay: "Bugatti Display", fontBody: "Avenir Next", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 14.0, radiusLg: 22.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 170, motionBaseMs: 280, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "cafe", name: "Cafe", category: "Creative & Artistic",
    description: "Bundled Open Design package for Cafe, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf6ee", surface: "#fffdf8", surfaceWarm: "#f1e3cf",
    foreground: "#201914", foregroundSecondary: "#4c4037", muted: "#7a6d63", border: "#ded2c3",
    accent: "#9b5b32", accentOn: "#ffffff", success: "#4f8a4f", warning: "#c9822f", danger: "#b33a3a",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 17.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "cal", name: "Cal.com", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Cal.com, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#ffffff",
    foreground: "#242424", foregroundSecondary: "#111111", muted: "#898989", border: "#222a3514",
    accent: "#0099ff", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Cal Sans", fontBody: "Inter", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "canva", name: "Canva", category: "Design & Creative",
    description: "Bundled Open Design package for Canva, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f4f5f7", surfaceWarm: "#f4f5f7",
    foreground: "#0e1318", foregroundSecondary: "#3c4043", muted: "#5f6368", border: "#e1e3e6",
    accent: "#7d2ae8", accentOn: "#ffffff", success: "#00b894", warning: "#ffb020", danger: "#ff5757",
    fontDisplay: "Canva Sans", fontBody: "Canva Sans", textBase: 14.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 180, motionBaseMs: 280, containerMax: 1320.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 32,
  },
  {
    id: "cisco", name: "Cisco", category: "Backend & Data",
    description: "Bundled Open Design package for Cisco, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#0f1720", surface: "#1b2530", surfaceWarm: "#243447",
    foreground: "#ffffff", foregroundSecondary: "#e8ebf1", muted: "#9e9ea2", border: "#58585b",
    accent: "#049fd9", accentOn: "#001923", success: "#6cc04a", warning: "#ffcc00", danger: "#cf2030",
    fontDisplay: "CiscoSansTT", fontBody: "CiscoSansTT", textBase: 16.0,
    radiusSm: 12.0, radiusMd: 20.0, radiusLg: 28.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 160, motionBaseMs: 240, containerMax: 1240.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
] as const satisfies readonly AnduraDesignSystem[];
