// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const designSystemsChunk06 = [
  {
    id: "premium", name: "Premium", category: "Professional & Corporate",
    description: "Bundled Open Design package for Premium, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#faf8f4", surface: "#ffffff", surfaceWarm: "#f0e7d8",
    foreground: "#1c1b19", foregroundSecondary: "#4b4740", muted: "#746d63", border: "#ded6c9",
    accent: "#a06a3b", accentOn: "#ffffff", success: "#3f8f5f", warning: "#c4872c", danger: "#b84a4a",
    fontDisplay: "Canela", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 28.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 170, motionBaseMs: 280, containerMax: 1160.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "professional", name: "Professional", category: "Professional & Corporate",
    description: "Bundled Open Design package for Professional, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f8ff", surface: "#ffffff", surfaceWarm: "#eaf1ff",
    foreground: "#101828", foregroundSecondary: "#344054", muted: "#667085", border: "#d7e0ef",
    accent: "#2563eb", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "publication", name: "Publication", category: "Creative & Artistic",
    description: "Bundled Open Design package for Publication, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f6f6f6", surfaceWarm: "#fff2f0",
    foreground: "#0b0b0b", foregroundSecondary: "#333333", muted: "#666666", border: "#d6d6d6",
    accent: "#c1121f", accentOn: "#ffffff", success: "#0f8a3b", warning: "#d99a00", danger: "#b00020",
    fontDisplay: "Franklin Gothic", fontBody: "Georgia", textBase: 17.0,
    radiusSm: 0.0, radiusMd: 0.0, radiusLg: 0.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 200, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "raycast", name: "Raycast", category: "Developer Tools",
    description: "Bundled Open Design package for Raycast, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#07080a", surface: "#101111", surfaceWarm: "#101111",
    foreground: "#f9f9f9", foregroundSecondary: "#cecece", muted: "#9c9c9d", border: "#ffffff0f",
    accent: "#ff6363", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 12.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "typography", "layout"], sourceClassCount: 23,
  },
  {
    id: "refined", name: "Refined", category: "Modern & Minimal",
    description: "Bundled Open Design package for Refined, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf6ee", surface: "#fffdf8", surfaceWarm: "#f1e3cf",
    foreground: "#201914", foregroundSecondary: "#4c4037", muted: "#7a6d63", border: "#ded2c3",
    accent: "#9b5b32", accentOn: "#ffffff", success: "#4f8a4f", warning: "#c9822f", danger: "#b33a3a",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 17.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "renault", name: "Renault", category: "Automotive",
    description: "Bundled Open Design package for Renault, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7f4ef", surface: "#ffffff", surfaceWarm: "#fff4bf",
    foreground: "#111111", foregroundSecondary: "#3f3f3f", muted: "#6f6b63", border: "#dfd8ca",
    accent: "#ffcc33", accentOn: "#111111", success: "#198754", warning: "#f59e0b", danger: "#d92d20",
    fontDisplay: "Renault Group", fontBody: "Renault Group", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 14.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 140, motionBaseMs: 230, containerMax: 1220.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "replicate", name: "Replicate", category: "AI & LLM",
    description: "Bundled Open Design package for Replicate, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f8f8f8", surfaceWarm: "#f8f8f8",
    foreground: "#202020", foregroundSecondary: "#4e4e4e", muted: "#646464", border: "#202020",
    accent: "#ea2804", accentOn: "#ffffff", success: "#2b9a66", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "rb-freigeist-neue", fontBody: "basier-square", textBase: 16.0,
    radiusSm: 9999.0, radiusMd: 9999.0, radiusLg: 9999.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 25,
  },
  {
    id: "resend", name: "Resend", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Resend, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#000000", surface: "#000000", surfaceWarm: "#000000",
    foreground: "#f0f0f0", foregroundSecondary: "#a1a4a5", muted: "#5c5c5c", border: "#d6ebfd30",
    accent: "#ff801f", accentOn: "#000000", success: "#11ff99", warning: "#ffc53d", danger: "#ff2047",
    fontDisplay: "ABC Favorit", fontBody: "Inter", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 39,
  },
  {
    id: "retro", name: "Retro", category: "Retro & Nostalgic",
    description: "Bundled Open Design package for Retro, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff4cf", surface: "#fffaf0", surfaceWarm: "#ffdca8",
    foreground: "#2a1810", foregroundSecondary: "#593625", muted: "#8a6652", border: "#d9aa7a",
    accent: "#d24b1f", accentOn: "#ffffff", success: "#3d8f4f", warning: "#f2a93b", danger: "#b83a2f",
    fontDisplay: "Courier New", fontBody: "Inter", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "revolut", name: "Revolut", category: "Fintech & Crypto",
    description: "Bundled Open Design package for Revolut, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7f8fb", surface: "#ffffff", surfaceWarm: "#eef4ff",
    foreground: "#111827", foregroundSecondary: "#334155", muted: "#64748b", border: "#dbe3ef",
    accent: "#0666eb", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 12.0, radiusMd: 20.0, radiusLg: 30.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "runwayml", name: "Runway", category: "AI & LLM",
    description: "Bundled Open Design package for Runway, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#000000", surface: "#1a1a1a", surfaceWarm: "#030303",
    foreground: "#ffffff", foregroundSecondary: "#e9ecf2", muted: "#767d88", border: "#27272a",
    accent: "#ffffff", accentOn: "#000000", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "abcNormal", fontBody: "abcNormal", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 220, containerMax: 1600.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 35,
  },
  {
    id: "sanity", name: "Sanity", category: "Backend & Data",
    description: "Bundled Open Design package for Sanity, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f8f8f7", surface: "#ffffff", surfaceWarm: "#fff1ef",
    foreground: "#171717", foregroundSecondary: "#3f3f46", muted: "#71717a", border: "#e4e4e7",
    accent: "#f03e2f", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#dc2626",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 10.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 140, motionBaseMs: 210, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "sentry", name: "Sentry", category: "Backend & Data",
    description: "Bundled Open Design package for Sentry, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#1f1633", surface: "#150f23", surfaceWarm: "#150f23",
    foreground: "#ffffff", foregroundSecondary: "#e5e7eb", muted: "#9d96b3", border: "#362d59",
    accent: "#6a5fc1", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Dammit Sans", fontBody: "Rubik", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1152.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 27,
  },
  {
    id: "shadcn", name: "Shadcn", category: "Modern & Minimal",
    description: "Bundled Open Design package for Shadcn, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#ffffff",
    foreground: "#111827", foregroundSecondary: "#111827", muted: "#64748b", border: "#e5e7eb",
    accent: "#000000", accentOn: "#ffffff", success: "#16a34a", warning: "#d97706", danger: "#dc2626",
    fontDisplay: "Geist", fontBody: "Geist", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 32,
  },
  {
    id: "shopify", name: "Shopify", category: "E-Commerce & Retail",
    description: "Bundled Open Design package for Shopify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#000000", surface: "#02090a", surfaceWarm: "#061a1c",
    foreground: "#ffffff", foregroundSecondary: "#ffffff", muted: "#a1a1aa", border: "#1e2c31",
    accent: "#36f4a4", accentOn: "#000000", success: "#36f4a4", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "NeueHaasGrotesk", fontBody: "Inter Variable", textBase: 18.0,
    radiusSm: 9999.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 28.0, space8: 36.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "links", "icons", "typography", "layout"], sourceClassCount: 15,
  },
  {
    id: "simple", name: "Simple", category: "Modern & Minimal",
    description: "Bundled Open Design package for Simple, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f8ff", surface: "#ffffff", surfaceWarm: "#eaf1ff",
    foreground: "#101828", foregroundSecondary: "#344054", muted: "#667085", border: "#d7e0ef",
    accent: "#2563eb", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "skeumorphism", name: "Skeumorphism", category: "Morphism & Effects",
    description: "Bundled Open Design package for Skeumorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7eee6", surface: "#fff8f1", surfaceWarm: "#ead6c7",
    foreground: "#2b211c", foregroundSecondary: "#5a4b43", muted: "#8a7a70", border: "#dac8b9",
    accent: "#b46a46", accentOn: "#ffffff", success: "#4d8f5a", warning: "#c88735", danger: "#b84c4c",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 16.0,
    radiusSm: 14.0, radiusMd: 22.0, radiusLg: 34.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "slack", name: "Slack", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Slack, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f8f8f8", surfaceWarm: "#f8f8f8",
    foreground: "#1d1c1d", foregroundSecondary: "#1d1c1d", muted: "#616061", border: "#dddddd",
    accent: "#4a154b", accentOn: "#ffffff", success: "#2eb67d", warning: "#ecb22e", danger: "#e01e5a",
    fontDisplay: "Larsseit", fontBody: "Poppins", textBase: 15.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "links", "typography", "layout"], sourceClassCount: 19,
  },
  {
    id: "sleek", name: "Sleek", category: "Modern & Minimal",
    description: "Bundled Open Design package for Sleek, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#090b12", surface: "#121722", surfaceWarm: "#1b2233",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#94a3b8", border: "#2a3447",
    accent: "#60a5fa", accentOn: "#06101d", success: "#22c55e", warning: "#fbbf24", danger: "#fb7185",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "spacex", name: "SpaceX", category: "Media & Consumer",
    description: "Bundled Open Design package for SpaceX, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#000000", surface: "#000000", surfaceWarm: "#000000",
    foreground: "#f0f0fa", foregroundSecondary: "#f0f0fa", muted: "#f0f0fab2", border: "#f0f0fa59",
    accent: "#f0f0fa", accentOn: "#000000", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "D-DIN-Bold", fontBody: "D-DIN", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 4.0, radiusLg: 4.0, radiusPill: 32.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1440.0,
    componentGroups: ["buttons", "inputs", "links", "icons", "typography", "layout"], sourceClassCount: 22,
  },
] as const satisfies readonly AnduraDesignSystem[];
