// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const designSystemsChunk02 = [
  {
    id: "claude", name: "Claude (Anthropic)", category: "AI & LLM",
    description: "Bundled Open Design package for Claude (Anthropic), derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f4ed", surface: "#faf9f5", surfaceWarm: "#e8e6dc",
    foreground: "#141413", foregroundSecondary: "#3d3d3a", muted: "#5e5d59", border: "#f0eee6",
    accent: "#c96442", accentOn: "#faf9f5", success: "#17a34a", warning: "#eab308", danger: "#b53333",
    fontDisplay: "Anthropic Serif", fontBody: "Anthropic Sans", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 25,
  },
  {
    id: "clay", name: "Clay", category: "Design & Creative",
    description: "Bundled Open Design package for Clay, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7eee6", surface: "#fff8f1", surfaceWarm: "#ead6c7",
    foreground: "#2b211c", foregroundSecondary: "#5a4b43", muted: "#8a7a70", border: "#dac8b9",
    accent: "#b46a46", accentOn: "#ffffff", success: "#4d8f5a", warning: "#c88735", danger: "#b84c4c",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 14.0, radiusMd: 22.0, radiusLg: 34.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "claymorphism", name: "Claymorphism", category: "Morphism & Effects",
    description: "Bundled Open Design package for Claymorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7eee6", surface: "#fff8f1", surfaceWarm: "#ead6c7",
    foreground: "#2b211c", foregroundSecondary: "#5a4b43", muted: "#8a7a70", border: "#dac8b9",
    accent: "#b46a46", accentOn: "#ffffff", success: "#4d8f5a", warning: "#c88735", danger: "#b84c4c",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 14.0, radiusMd: 22.0, radiusLg: 34.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "clean", name: "Clean", category: "Modern & Minimal",
    description: "Bundled Open Design package for Clean, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f7f7f7", surfaceWarm: "#eeeeee",
    foreground: "#111111", foregroundSecondary: "#3a3a3a", muted: "#707070", border: "#d9d9d9",
    accent: "#111111", accentOn: "#ffffff", success: "#168a46", warning: "#b7791f", danger: "#c53030",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "clickhouse", name: "ClickHouse", category: "Backend & Data",
    description: "Bundled Open Design package for ClickHouse, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#000000", surface: "#141414", surfaceWarm: "#141414",
    foreground: "#ffffff", foregroundSecondary: "#a0a0a0", muted: "#a0a0a0", border: "#414141cc",
    accent: "#faff69", accentOn: "#151515", success: "#166534", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 38,
  },
  {
    id: "cohere", name: "Cohere", category: "AI & LLM",
    description: "Bundled Open Design package for Cohere, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#fafafa", surfaceWarm: "#fafafa",
    foreground: "#000000", foregroundSecondary: "#212121", muted: "#93939f", border: "#d9d9dd",
    accent: "#1863dc", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#ef4444",
    fontDisplay: "CohereText", fontBody: "Unica77 Cohere Web", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 22.0, radiusLg: 22.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1440.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 25,
  },
  {
    id: "coinbase", name: "Coinbase", category: "Fintech & Crypto",
    description: "Bundled Open Design package for Coinbase, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#eef0f3", surfaceWarm: "#eef0f3",
    foreground: "#0a0b0d", foregroundSecondary: "#0a0b0d", muted: "#5b616e", border: "#5b616e33",
    accent: "#0052ff", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "CoinbaseDisplay", fontBody: "CoinbaseText", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 16.0, radiusLg: 32.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 40,
  },
  {
    id: "colorful", name: "Colorful", category: "Bold & Expressive",
    description: "Bundled Open Design package for Colorful, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff8d7", surface: "#ffffff", surfaceWarm: "#ffef9f",
    foreground: "#1d1836", foregroundSecondary: "#4c426c", muted: "#796f91", border: "#eadfba",
    accent: "#ff6b00", accentOn: "#ffffff", success: "#2e9d57", warning: "#ffb020", danger: "#e5484d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "composio", name: "Composio", category: "Backend & Data",
    description: "Bundled Open Design package for Composio, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#090b14", surface: "#121626", surfaceWarm: "#1b2140",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#94a3b8", border: "#27324a",
    accent: "#6d5dfc", accentOn: "#ffffff", success: "#22c55e", warning: "#fbbf24", danger: "#fb7185",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 15.0,
    radiusSm: 10.0, radiusMd: 14.0, radiusLg: 22.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 140, motionBaseMs: 220, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "contemporary", name: "Contemporary", category: "Modern & Minimal",
    description: "Bundled Open Design package for Contemporary, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f8ff", surface: "#ffffff", surfaceWarm: "#eaf1ff",
    foreground: "#101828", foregroundSecondary: "#344054", muted: "#667085", border: "#d7e0ef",
    accent: "#2563eb", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "corporate", name: "Corporate", category: "Professional & Corporate",
    description: "Bundled Open Design package for Corporate, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f8ff", surface: "#ffffff", surfaceWarm: "#eaf1ff",
    foreground: "#101828", foregroundSecondary: "#344054", muted: "#667085", border: "#d7e0ef",
    accent: "#2563eb", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "cosmic", name: "Cosmic", category: "Creative & Artistic",
    description: "Bundled Open Design package for Cosmic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#070711", surface: "#111126", surfaceWarm: "#1e1540",
    foreground: "#f8f7ff", foregroundSecondary: "#d6ccff", muted: "#9d8ad4", border: "#34265e",
    accent: "#c084fc", accentOn: "#13051f", success: "#39ff88", warning: "#fff34d", danger: "#ff4d8d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "creative", name: "Creative", category: "Creative & Artistic",
    description: "Bundled Open Design package for Creative, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff8d7", surface: "#ffffff", surfaceWarm: "#ffef9f",
    foreground: "#1d1836", foregroundSecondary: "#4c426c", muted: "#796f91", border: "#eadfba",
    accent: "#ff6b00", accentOn: "#ffffff", success: "#2e9d57", warning: "#ffb020", danger: "#e5484d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "cursor", name: "Cursor", category: "Developer Tools",
    description: "Bundled Open Design package for Cursor, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f2f1ed", surface: "#e6e5e0", surfaceWarm: "#ebeae5",
    foreground: "#26251e", foregroundSecondary: "#26251ee6", muted: "#26251e8c", border: "#26251e1a",
    accent: "#f54e00", accentOn: "#ffffff", success: "#1f8a65", warning: "#eab308", danger: "#cf2d56",
    fontDisplay: "CursorGothic", fontBody: "jjannon", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 10.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 37,
  },
  {
    id: "dashboard", name: "Dashboard", category: "Professional & Corporate",
    description: "Bundled Open Design package for Dashboard, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f4f7fb", surface: "#ffffff", surfaceWarm: "#eef6ff",
    foreground: "#111827", foregroundSecondary: "#334155", muted: "#64748b", border: "#d8e2ee",
    accent: "#0ea5e9", accentOn: "#04131d", success: "#10b981", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 15.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 18.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "default", name: "Neutral Modern", category: "Starter",
    description: "Bundled Open Design package for Neutral Modern, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fafafa", surface: "#ffffff", surfaceWarm: "#ffffff",
    foreground: "#111111", foregroundSecondary: "#111111", muted: "#6b6b6b", border: "#e5e5e5",
    accent: "#2f6feb", accentOn: "#ffffff", success: "#17a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 25,
  },
  {
    id: "discord", name: "Discord", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Discord, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#313338", surface: "#2b2d31", surfaceWarm: "#1e1f22",
    foreground: "#dbdee1", foregroundSecondary: "#f2f3f5", muted: "#949ba4", border: "#ffffff0f",
    accent: "#5865f2", accentOn: "#ffffff", success: "#23a55a", warning: "#f0b232", danger: "#f23f43",
    fontDisplay: "gg sans", fontBody: "gg sans", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 80, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "links", "typography", "layout"], sourceClassCount: 17,
  },
  {
    id: "dithered", name: "Dithered", category: "Retro & Nostalgic",
    description: "Bundled Open Design package for Dithered, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff4cf", surface: "#fffaf0", surfaceWarm: "#ffdca8",
    foreground: "#2a1810", foregroundSecondary: "#593625", muted: "#8a6652", border: "#d9aa7a",
    accent: "#d24b1f", accentOn: "#ffffff", success: "#3d8f4f", warning: "#f2a93b", danger: "#b83a2f",
    fontDisplay: "Courier New", fontBody: "Inter", textBase: 14.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 100, motionBaseMs: 180, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "doodle", name: "Doodle", category: "Creative & Artistic",
    description: "Bundled Open Design package for Doodle, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff8d7", surface: "#ffffff", surfaceWarm: "#ffef9f",
    foreground: "#1d1836", foregroundSecondary: "#4c426c", muted: "#796f91", border: "#eadfba",
    accent: "#ff6b00", accentOn: "#ffffff", success: "#2e9d57", warning: "#ffb020", danger: "#e5484d",
    fontDisplay: "Comic Sans MS", fontBody: "Comic Sans MS", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "dramatic", name: "Dramatic", category: "Bold & Expressive",
    description: "Bundled Open Design package for Dramatic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#090b12", surface: "#121722", surfaceWarm: "#1b2233",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#94a3b8", border: "#2a3447",
    accent: "#60a5fa", accentOn: "#06101d", success: "#22c55e", warning: "#fbbf24", danger: "#fb7185",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
] as const satisfies readonly AnduraDesignSystem[];
