// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const designSystemsChunk03 = [
  {
    id: "duolingo", name: "Duolingo", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Duolingo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f7f7f7", surfaceWarm: "#f7f7f7",
    foreground: "#3c3c3c", foregroundSecondary: "#3c3c3c", muted: "#777777", border: "#e5e5e5",
    accent: "#58cc02", accentOn: "#ffffff", success: "#58cc02", warning: "#ffc800", danger: "#ff4b4b",
    fontDisplay: "Feather Bold", fontBody: "Mona Sans", textBase: 15.0,
    radiusSm: 12.0, radiusMd: 16.0, radiusLg: 20.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 180, motionBaseMs: 320, containerMax: 1080.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 36,
  },
  {
    id: "editorial", name: "Editorial", category: "Creative & Artistic",
    description: "Bundled Open Design package for Editorial, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf7f0", surface: "#fffdf8", surfaceWarm: "#f1e6d6",
    foreground: "#1f1a16", foregroundSecondary: "#4b4038", muted: "#7d7168", border: "#ded3c5",
    accent: "#9a5a2f", accentOn: "#ffffff", success: "#4f8a4f", warning: "#c9822f", danger: "#b33a3a",
    fontDisplay: "Georgia", fontBody: "Source Serif Pro", textBase: 18.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 180, motionBaseMs: 280, containerMax: 1120.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "elegant", name: "Elegant", category: "Professional & Corporate",
    description: "Bundled Open Design package for Elegant, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf6ee", surface: "#fffdf8", surfaceWarm: "#f1e3cf",
    foreground: "#201914", foregroundSecondary: "#4c4037", muted: "#7a6d63", border: "#ded2c3",
    accent: "#9b5b32", accentOn: "#ffffff", success: "#4f8a4f", warning: "#c9822f", danger: "#b33a3a",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 17.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "elevenlabs", name: "ElevenLabs", category: "AI & LLM",
    description: "Bundled Open Design package for ElevenLabs, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f5f5f5", surfaceWarm: "#f5f2ef",
    foreground: "#000000", foregroundSecondary: "#4e4e4e", muted: "#777169", border: "#e5e5e5",
    accent: "#000000", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Waldenburg", fontBody: "Inter", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 24,
  },
  {
    id: "energetic", name: "Energetic", category: "Bold & Expressive",
    description: "Bundled Open Design package for Energetic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff8d7", surface: "#ffffff", surfaceWarm: "#ffef9f",
    foreground: "#1d1836", foregroundSecondary: "#4c426c", muted: "#796f91", border: "#eadfba",
    accent: "#ff6b00", accentOn: "#ffffff", success: "#2e9d57", warning: "#ffb020", danger: "#e5484d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "enterprise", name: "Enterprise", category: "Professional & Corporate",
    description: "Bundled Open Design package for Enterprise, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f8fafc", surface: "#ffffff", surfaceWarm: "#eef2f7",
    foreground: "#0f172a", foregroundSecondary: "#334155", muted: "#64748b", border: "#d8dee8",
    accent: "#1d4ed8", accentOn: "#ffffff", success: "#15803d", warning: "#b45309", danger: "#b91c1c",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 10.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 230, containerMax: 1240.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "expo", name: "Expo", category: "Developer Tools",
    description: "Bundled Open Design package for Expo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f6f7f9", surfaceWarm: "#eef2ff",
    foreground: "#0b0d12", foregroundSecondary: "#353945", muted: "#6b7280", border: "#dfe3ea",
    accent: "#000020", accentOn: "#ffffff", success: "#00a36c", warning: "#f59e0b", danger: "#e5484d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 14.0, radiusLg: 22.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 140, motionBaseMs: 220, containerMax: 1160.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "expressive", name: "Expressive", category: "Bold & Expressive",
    description: "Bundled Open Design package for Expressive, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf8ff", surface: "#ffffff", surfaceWarm: "#efe8ff",
    foreground: "#1f1730", foregroundSecondary: "#4d425f", muted: "#776b88", border: "#ded4ee",
    accent: "#7c3aed", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "fantasy", name: "Fantasy", category: "Creative & Artistic",
    description: "Bundled Open Design package for Fantasy, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#070711", surface: "#111126", surfaceWarm: "#1e1540",
    foreground: "#f8f7ff", foregroundSecondary: "#d6ccff", muted: "#9d8ad4", border: "#34265e",
    accent: "#c084fc", accentOn: "#13051f", success: "#39ff88", warning: "#fff34d", danger: "#ff4d8d",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "ferrari", name: "Ferrari", category: "Automotive",
    description: "Bundled Open Design package for Ferrari, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#0b0b0b", surface: "#171717", surfaceWarm: "#23130f",
    foreground: "#fffaf0", foregroundSecondary: "#e8dcc8", muted: "#a89f91", border: "#342a24",
    accent: "#dc0000", accentOn: "#ffffff", success: "#0f9d58", warning: "#ffd200", danger: "#ff3b30",
    fontDisplay: "Ferrari Sans", fontBody: "Ferrari Sans", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 14.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 130, motionBaseMs: 220, containerMax: 1240.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "figma", name: "Figma", category: "Design & Creative",
    description: "Bundled Open Design package for Figma, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#ffffff",
    foreground: "#000000", foregroundSecondary: "#000000", muted: "#0000008c", border: "#0000001f",
    accent: "#000000", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "figmaSans", fontBody: "figmaSans", textBase: 16.0,
    radiusSm: 50.0, radiusMd: 8.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1920.0,
    componentGroups: ["buttons", "inputs", "cards", "links", "icons", "typography", "layout"], sourceClassCount: 17,
  },
  {
    id: "flat", name: "Flat", category: "Modern & Minimal",
    description: "Bundled Open Design package for Flat, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f8ff", surface: "#ffffff", surfaceWarm: "#eaf1ff",
    foreground: "#101828", foregroundSecondary: "#344054", muted: "#667085", border: "#d7e0ef",
    accent: "#2563eb", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "framer", name: "Framer", category: "Design & Creative",
    description: "Bundled Open Design package for Framer, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#000000", surface: "#090909", surfaceWarm: "#090909",
    foreground: "#ffffff", foregroundSecondary: "#a6a6a6", muted: "#ffffff99", border: "#0099ff26",
    accent: "#0099ff", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "GT Walsheim Framer Medium", fontBody: "Inter Variable", textBase: 15.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 20.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 32,
  },
  {
    id: "friendly", name: "Friendly", category: "Creative & Artistic",
    description: "Bundled Open Design package for Friendly, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff8d7", surface: "#ffffff", surfaceWarm: "#ffef9f",
    foreground: "#1d1836", foregroundSecondary: "#4c426c", muted: "#796f91", border: "#eadfba",
    accent: "#ff6b00", accentOn: "#ffffff", success: "#2e9d57", warning: "#ffb020", danger: "#e5484d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "futuristic", name: "Futuristic", category: "Themed & Unique",
    description: "Bundled Open Design package for Futuristic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#090b12", surface: "#121722", surfaceWarm: "#1b2233",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#94a3b8", border: "#2a3447",
    accent: "#60a5fa", accentOn: "#06101d", success: "#22c55e", warning: "#fbbf24", danger: "#fb7185",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "github", name: "GitHub", category: "Developer Tools",
    description: "Bundled Open Design package for GitHub, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f6f8fa", surfaceWarm: "#f6f8fa",
    foreground: "#1f2328", foregroundSecondary: "#1f2328", muted: "#656d76", border: "#d0d7de",
    accent: "#0969da", accentOn: "#ffffff", success: "#1a7f37", warning: "#9a6700", danger: "#cf222e",
    fontDisplay: "-apple-system", fontBody: "-apple-system", textBase: 14.0,
    radiusSm: 6.0, radiusMd: 6.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 80, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "badges", "links", "icons", "typography", "layout"], sourceClassCount: 21,
  },
  {
    id: "glassmorphism", name: "Glassmorphism", category: "Morphism & Effects",
    description: "Bundled Open Design package for Glassmorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#eef6ff", surface: "#ffffffbd", surfaceWarm: "#eef6ffb8",
    foreground: "#102033", foregroundSecondary: "#34465f", muted: "#60708a", border: "#ffffffa3",
    accent: "#4f8cff", accentOn: "#ffffff", success: "#22c55e", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 16.0, radiusMd: 24.0, radiusLg: 36.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 180, motionBaseMs: 280, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "gradient", name: "Gradient", category: "Morphism & Effects",
    description: "Bundled Open Design package for Gradient, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7f3ff", surface: "#ffffff", surfaceWarm: "#efe7ff",
    foreground: "#191225", foregroundSecondary: "#443856", muted: "#746985", border: "#ddd2f2",
    accent: "#7c3aed", accentOn: "#ffffff", success: "#10b981", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 12.0, radiusMd: 20.0, radiusLg: 32.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 160, motionBaseMs: 260, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "hashicorp", name: "HashiCorp", category: "Backend & Data",
    description: "Bundled Open Design package for HashiCorp, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#15181e", surface: "#0d0e12", surfaceWarm: "#0d0e12",
    foreground: "#efeff1", foregroundSecondary: "#d5d7db", muted: "#b2b6bd", border: "#b2b6bd66",
    accent: "#1060ff", accentOn: "#ffffff", success: "#16a34a", warning: "#bb5a00", danger: "#dc2626",
    fontDisplay: "HashiCorp Sans", fontBody: "Poppins", textBase: 16.0,
    radiusSm: 5.0, radiusMd: 8.0, radiusLg: 8.0, radiusPill: 5.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1150.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 27,
  },
  {
    id: "hud", name: "HUD Design System", category: "Themed & Unique",
    description: "Bundled Open Design package for HUD Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#090b12", surface: "#121722", surfaceWarm: "#1b2233",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#94a3b8", border: "#2a3447",
    accent: "#60a5fa", accentOn: "#06101d", success: "#22c55e", warning: "#fbbf24", danger: "#fb7185",
    fontDisplay: "IBM Plex Mono", fontBody: "IBM Plex Mono", textBase: 14.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 100, motionBaseMs: 180, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
] as const satisfies readonly AnduraDesignSystem[];
