// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const designSystemsChunk04 = [
  {
    id: "huggingface", name: "Hugging Face", category: "AI & LLM",
    description: "Bundled Open Design package for Hugging Face, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fafafa", surface: "#ffffff", surfaceWarm: "#fff4cc",
    foreground: "#0d1117", foregroundSecondary: "#374151", muted: "#6b7280", border: "#e5e7eb",
    accent: "#ffd21e", accentOn: "#0d1117", success: "#16a34a", warning: "#f59e0b", danger: "#dc2626",
    fontDisplay: "IBM Plex Mono", fontBody: "Source Sans Pro", textBase: 15.0,
    radiusSm: 4.0, radiusMd: 6.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "ibm", name: "IBM", category: "Media & Consumer",
    description: "Bundled Open Design package for IBM, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f4f4f4", surfaceWarm: "#edf5ff",
    foreground: "#161616", foregroundSecondary: "#525252", muted: "#6f6f6f", border: "#c6c6c6",
    accent: "#0f62fe", accentOn: "#ffffff", success: "#24a148", warning: "#f1c21b", danger: "#da1e28",
    fontDisplay: "IBM Plex Sans", fontBody: "IBM Plex Sans", textBase: 16.0,
    radiusSm: 0.0, radiusMd: 0.0, radiusLg: 0.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 110, motionBaseMs: 180, containerMax: 1312.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "intercom", name: "Intercom", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Intercom, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#faf9f6", surface: "#ffffff", surfaceWarm: "#faf9f6",
    foreground: "#111111", foregroundSecondary: "#111111", muted: "#7b7b78", border: "#dedbd6",
    accent: "#ff5600", accentOn: "#ffffff", success: "#00da00", warning: "#eab308", danger: "#c41c1c",
    fontDisplay: "Saans", fontBody: "Saans", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 6.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 37,
  },
  {
    id: "kami", name: "kami (紙 / 纸)", category: "Editorial & Print",
    description: "Bundled Open Design package for kami (紙 / 纸), derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f4ed", surface: "#faf9f5", surfaceWarm: "#e8e6dc",
    foreground: "#141413", foregroundSecondary: "#3d3d3a", muted: "#504e49", border: "#e8e6dc",
    accent: "#1b365d", accentOn: "#faf9f5", success: "#4a6b3a", warning: "#8a6b1f", danger: "#8a3a30",
    fontDisplay: "Charter", fontBody: "Charter", textBase: 14.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1120.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "kraken", name: "Kraken", category: "Fintech & Crypto",
    description: "Bundled Open Design package for Kraken, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#0b1020", surface: "#121a33", surfaceWarm: "#1b2450",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#8b95aa", border: "#26314f",
    accent: "#7132f5", accentOn: "#ffffff", success: "#00c853", warning: "#ffb020", danger: "#ff4d6d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 15.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 18.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "lamborghini", name: "Lamborghini", category: "Automotive",
    description: "Bundled Open Design package for Lamborghini, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#050505", surface: "#141414", surfaceWarm: "#211b0b",
    foreground: "#f8f4e6", foregroundSecondary: "#d8ceb0", muted: "#9b927d", border: "#3a321d",
    accent: "#d4af37", accentOn: "#050505", success: "#39a852", warning: "#f7c948", danger: "#e63946",
    fontDisplay: "Lamborghini", fontBody: "Inter", textBase: 16.0,
    radiusSm: 2.0, radiusMd: 6.0, radiusLg: 10.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 210, containerMax: 1240.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "levels", name: "Levels", category: "Layout & Structure",
    description: "Bundled Open Design package for Levels, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf7ef", surface: "#ffffff", surfaceWarm: "#eef7ed",
    foreground: "#1f2a24", foregroundSecondary: "#435147", muted: "#788276", border: "#dbe3d7",
    accent: "#2f8f46", accentOn: "#ffffff", success: "#16a34a", warning: "#d97706", danger: "#dc2626",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 12.0, radiusMd: 18.0, radiusLg: 28.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 160, motionBaseMs: 240, containerMax: 1160.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "linear-app", name: "Linear", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Linear, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#08090a", surface: "#191a1b", surfaceWarm: "#191a1b",
    foreground: "#f7f8f8", foregroundSecondary: "#d0d6e0", muted: "#8a8f98", border: "#ffffff14",
    accent: "#5e6ad2", accentOn: "#ffffff", success: "#27a644", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Inter Variable", fontBody: "Inter Variable", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"], sourceClassCount: 15,
  },
  {
    id: "lingo", name: "Lingo", category: "Creative & Artistic",
    description: "Bundled Open Design package for Lingo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf9ff", surface: "#ffffff", surfaceWarm: "#f1ecff",
    foreground: "#1d1b2a", foregroundSecondary: "#4f4863", muted: "#786f8f", border: "#ded7f0",
    accent: "#6d4aff", accentOn: "#ffffff", success: "#22a06b", warning: "#e6a700", danger: "#e5484d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 230, containerMax: 1160.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "loom", name: "Loom Design System", category: "Themed & Unique",
    description: "Bundled Open Design package for Loom Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f7f7f8", surfaceWarm: "#f7f7f8",
    foreground: "#1f1f23", foregroundSecondary: "#1f1f23", muted: "#6b6d76", border: "#e4e4e7",
    accent: "#625df5", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#d64770",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 14.0,
    radiusSm: 4.0, radiusMd: 6.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 100, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 31,
  },
  {
    id: "lovable", name: "Lovable", category: "Developer Tools",
    description: "Bundled Open Design package for Lovable, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7f4ed", surface: "#f7f4ed", surfaceWarm: "#f7f4ed",
    foreground: "#1c1c1c", foregroundSecondary: "#1c1c1cd4", muted: "#5f5f5d", border: "#eceae4",
    accent: "#ff4d8d", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Camera Plain Variable", fontBody: "Camera Plain Variable", textBase: 16.0,
    radiusSm: 6.0, radiusMd: 12.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 24,
  },
  {
    id: "luxury", name: "Luxury", category: "Professional & Corporate",
    description: "Bundled Open Design package for Luxury, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#080706", surface: "#151310", surfaceWarm: "#241e14",
    foreground: "#fff8ea", foregroundSecondary: "#d8cdb7", muted: "#9f927c", border: "#3a3020",
    accent: "#c6a15b", accentOn: "#080706", success: "#5fa36a", warning: "#d8a94f", danger: "#d85a52",
    fontDisplay: "Didot", fontBody: "Avenir Next", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 14.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 180, motionBaseMs: 300, containerMax: 1160.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "mastercard", name: "Mastercard", category: "Fintech & Crypto",
    description: "Bundled Open Design package for Mastercard, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f3f0ee", surface: "#fcfbfa", surfaceWarm: "#f7e8de",
    foreground: "#141413", foregroundSecondary: "#262627", muted: "#696969", border: "#d1cdc7",
    accent: "#cf4500", accentOn: "#ffffff", success: "#2e7d32", warning: "#f79e1b", danger: "#eb001b",
    fontDisplay: "MarkForMC", fontBody: "MarkForMC", textBase: 16.0,
    radiusSm: 20.0, radiusMd: 40.0, radiusLg: 64.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 180, motionBaseMs: 260, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "material", name: "Material", category: "Professional & Corporate",
    description: "Bundled Open Design package for Material, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f8fafd", surface: "#ffffff", surfaceWarm: "#e8f0fe",
    foreground: "#202124", foregroundSecondary: "#3c4043", muted: "#5f6368", border: "#dadce0",
    accent: "#1a73e8", accentOn: "#ffffff", success: "#188038", warning: "#f9ab00", danger: "#d93025",
    fontDisplay: "Google Sans", fontBody: "Roboto", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 12.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 250, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "meta", name: "Meta (Store)", category: "E-Commerce & Retail",
    description: "Bundled Open Design package for Meta (Store), derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f7f8fa", surfaceWarm: "#f2f0e6",
    foreground: "#1c2b33", foregroundSecondary: "#5d6c7b", muted: "#65676b", border: "#ced0d4",
    accent: "#0064e0", accentOn: "#ffffff", success: "#31a24c", warning: "#f7b928", danger: "#e41e3f",
    fontDisplay: "Optimistic VF", fontBody: "Optimistic VF", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 20.0, radiusLg: 24.0, radiusPill: 100.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1440.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 31,
  },
  {
    id: "minimal", name: "Minimal", category: "Modern & Minimal",
    description: "Bundled Open Design package for Minimal, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#fafafa", surfaceWarm: "#f5f5f5",
    foreground: "#111111", foregroundSecondary: "#3a3a3a", muted: "#777777", border: "#e2e2e2",
    accent: "#111111", accentOn: "#ffffff", success: "#168a46", warning: "#b7791f", danger: "#c53030",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 2.0, radiusMd: 4.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 140, motionBaseMs: 220, containerMax: 1120.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "minimax", name: "MiniMax", category: "AI & LLM",
    description: "Bundled Open Design package for MiniMax, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#fafafa", surfaceWarm: "#f0f0f0",
    foreground: "#222222", foregroundSecondary: "#18181b", muted: "#45515e", border: "#e5e7eb",
    accent: "#1456f0", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Outfit", fontBody: "DM Sans", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 13.0, radiusLg: 20.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 33,
  },
  {
    id: "mintlify", name: "Mintlify", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Mintlify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#fafafa",
    foreground: "#0d0d0d", foregroundSecondary: "#333333", muted: "#666666", border: "#0000000d",
    accent: "#18e299", accentOn: "#0d0d0d", success: "#16a34a", warning: "#c37d0d", danger: "#d45656",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 34,
  },
  {
    id: "miro", name: "Miro", category: "Design & Creative",
    description: "Bundled Open Design package for Miro, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff7c2", surface: "#ffffff", surfaceWarm: "#fff3a3",
    foreground: "#050038", foregroundSecondary: "#322b6b", muted: "#605a8a", border: "#ded9ff",
    accent: "#ffd02f", accentOn: "#050038", success: "#1a7f37", warning: "#ff9f1c", danger: "#d92d20",
    fontDisplay: "Formular", fontBody: "Formular", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 18.0, radiusLg: 28.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 230, containerMax: 1220.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "mission-control", name: "Mission Control Design System", category: "Developer Tools",
    description: "Bundled Open Design package for Mission Control Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#090b12", surface: "#121722", surfaceWarm: "#1b2233",
    foreground: "#f8fafc", foregroundSecondary: "#cbd5e1", muted: "#94a3b8", border: "#2a3447",
    accent: "#60a5fa", accentOn: "#06101d", success: "#26de81", warning: "#fbbf24", danger: "#ff4757",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 14.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 100, motionBaseMs: 180, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
] as const satisfies readonly AnduraDesignSystem[];
