// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const designSystemsChunk08 = [
  {
    id: "voltagent", name: "VoltAgent", category: "AI & LLM",
    description: "Bundled Open Design package for VoltAgent, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#07110c", surface: "#101c16", surfaceWarm: "#14281e",
    foreground: "#f4fff8", foregroundSecondary: "#c8dfd0", muted: "#8ba493", border: "#254132",
    accent: "#7cff6b", accentOn: "#07110c", success: "#52e875", warning: "#facc15", danger: "#fb7185",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 15.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 18.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 210, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "warm-editorial", name: "Warm Editorial", category: "Starter",
    description: "Bundled Open Design package for Warm Editorial, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fbf6ee", surface: "#fffdf8", surfaceWarm: "#f1e3cf",
    foreground: "#201914", foregroundSecondary: "#4c4037", muted: "#7a6d63", border: "#ded2c3",
    accent: "#9b5b32", accentOn: "#ffffff", success: "#4f8a4f", warning: "#c9822f", danger: "#b33a3a",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 17.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "warp", name: "Warp", category: "Developer Tools",
    description: "Bundled Open Design package for Warp, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#161412", surface: "#1f1d1b", surfaceWarm: "#1f1d1b",
    foreground: "#faf9f6", foregroundSecondary: "#afaeac", muted: "#868584", border: "#e2e2e259",
    accent: "#353534", accentOn: "#afaeac", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Matter Regular", fontBody: "Matter Regular", textBase: 18.0,
    radiusSm: 6.0, radiusMd: 12.0, radiusLg: 14.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1500.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 28,
  },
  {
    id: "webex", name: "Webex", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Webex, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f6f8fb", surface: "#ffffff", surfaceWarm: "#eef8f6",
    foreground: "#0f172a", foregroundSecondary: "#334155", muted: "#64748b", border: "#dbe4ee",
    accent: "#00a3a6", accentOn: "#ffffff", success: "#22c55e", warning: "#f59e0b", danger: "#e11d48",
    fontDisplay: "CiscoSansTT", fontBody: "CiscoSansTT", textBase: 16.0,
    radiusSm: 12.0, radiusMd: 18.0, radiusLg: 28.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 160, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "webflow", name: "Webflow", category: "Design & Creative",
    description: "Bundled Open Design package for Webflow, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#ffffff", surfaceWarm: "#ffffff",
    foreground: "#080808", foregroundSecondary: "#363636", muted: "#5a5a5a", border: "#d8d8d8",
    accent: "#146ef5", accentOn: "#ffffff", success: "#00d722", warning: "#ffae13", danger: "#ee1d36",
    fontDisplay: "WF Visual Sans Variable", fontBody: "WF Visual Sans Variable", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 4.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 28,
  },
  {
    id: "wechat", name: "WeChat Design System", category: "Social & Messaging",
    description: "Bundled Open Design package for WeChat Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ededed", surface: "#f7f7f7", surfaceWarm: "#f7f7f7",
    foreground: "#1a1a1a", foregroundSecondary: "#1a1a1a", muted: "#888888", border: "#e0e0e0",
    accent: "#07c160", accentOn: "#ffffff", success: "#07c160", warning: "#fab702", danger: "#fa5151",
    fontDisplay: "-apple-system", fontBody: "-apple-system", textBase: 15.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 100, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 34,
  },
  {
    id: "wired", name: "WIRED", category: "Media & Consumer",
    description: "Bundled Open Design package for WIRED, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f2f2f2", surfaceWarm: "#fff0f0",
    foreground: "#000000", foregroundSecondary: "#333333", muted: "#666666", border: "#d0d0d0",
    accent: "#e10600", accentOn: "#ffffff", success: "#0f8a3b", warning: "#f5a400", danger: "#c40000",
    fontDisplay: "Druk Wide", fontBody: "Exchange", textBase: 17.0,
    radiusSm: 0.0, radiusMd: 0.0, radiusLg: 0.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 200, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "wise", name: "Wise", category: "Fintech & Crypto",
    description: "Bundled Open Design package for Wise, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#e8ebe6", surfaceWarm: "#e8ebe6",
    foreground: "#0e0f0c", foregroundSecondary: "#0e0f0c", muted: "#868685", border: "#0e0f0c1f",
    accent: "#9fe870", accentOn: "#163300", success: "#054d28", warning: "#ffd11a", danger: "#d03238",
    fontDisplay: "Wise Sans", fontBody: "Inter", textBase: 18.0,
    radiusSm: 16.0, radiusMd: 30.0, radiusLg: 40.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 28,
  },
  {
    id: "x-ai", name: "xAI", category: "AI & LLM",
    description: "Bundled Open Design package for xAI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#1f2228", surface: "#ffffff08", surfaceWarm: "#ffffff0d",
    foreground: "#ffffff", foregroundSecondary: "#ffffffb2", muted: "#ffffff80", border: "#ffffff1a",
    accent: "#ffffff", accentOn: "#1f2228", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "GeistMono", fontBody: "universalSans", textBase: 16.0,
    radiusSm: 0.0, radiusMd: 0.0, radiusLg: 4.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 23,
  },
  {
    id: "xiaohongshu", name: "Xiaohongshu", category: "Media & Consumer",
    description: "Bundled Open Design package for Xiaohongshu, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f5f5", surface: "#ffffff", surfaceWarm: "#fafafa",
    foreground: "#000000cc", foregroundSecondary: "#0000009e", muted: "#00000073", border: "#00000014",
    accent: "#ff2442", accentOn: "#ffffff", success: "#02b940", warning: "#ff7d03", danger: "#ff2442",
    fontDisplay: "PingFang SC", fontBody: "PingFang SC", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 49,
  },
  {
    id: "zapier", name: "Zapier", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Zapier, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff7ed", surface: "#ffffff", surfaceWarm: "#ffedd5",
    foreground: "#2d2a26", foregroundSecondary: "#574f45", muted: "#7c6f64", border: "#eadfd3",
    accent: "#ff4f00", accentOn: "#ffffff", success: "#15803d", warning: "#d97706", danger: "#dc2626",
    fontDisplay: "Degular", fontBody: "Inter", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 12.0, radiusLg: 20.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 140, motionBaseMs: 220, containerMax: 1160.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
] as const satisfies readonly AnduraDesignSystem[];
