// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const designSystemsChunk05 = [
  {
    id: "mistral-ai", name: "Mistral AI", category: "AI & LLM",
    description: "Bundled Open Design package for Mistral AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fffaeb", surface: "#fff0c2", surfaceWarm: "#fff0c2",
    foreground: "#1f1f1f", foregroundSecondary: "#1f1f1f", muted: "#3d3d3d", border: "#f0e8c8",
    accent: "#fa520f", accentOn: "#ffffff", success: "#17a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "Arial", fontBody: "Arial", textBase: 16.0,
    radiusSm: 2.0, radiusMd: 2.0, radiusLg: 4.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 25,
  },
  {
    id: "modern", name: "Modern", category: "Modern & Minimal",
    description: "Bundled Open Design package for Modern, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7f8fc", surface: "#ffffff", surfaceWarm: "#eef1ff",
    foreground: "#111827", foregroundSecondary: "#374151", muted: "#6b7280", border: "#dfe3ed",
    accent: "#4f46e5", accentOn: "#ffffff", success: "#10b981", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "mongodb", name: "MongoDB", category: "Backend & Data",
    description: "Bundled Open Design package for MongoDB, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#001e2b", surface: "#1c2d38", surfaceWarm: "#1c2d38",
    foreground: "#ffffff", foregroundSecondary: "#e8edeb", muted: "#b8c4c2", border: "#3d4f58",
    accent: "#00ed64", accentOn: "#001e2b", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "MongoDB Value Serif", fontBody: "Euclid Circular A", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "mono", name: "Mono", category: "Modern & Minimal",
    description: "Bundled Open Design package for Mono, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f7f7f7", surfaceWarm: "#eeeeee",
    foreground: "#111111", foregroundSecondary: "#3a3a3a", muted: "#707070", border: "#d9d9d9",
    accent: "#111111", accentOn: "#ffffff", success: "#168a46", warning: "#b7791f", danger: "#c53030",
    fontDisplay: "IBM Plex Mono", fontBody: "IBM Plex Mono", textBase: 14.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 100, motionBaseMs: 180, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "neobrutalism", name: "Neobrutalism", category: "Bold & Expressive",
    description: "Bundled Open Design package for Neobrutalism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fff4cf", surface: "#fffaf0", surfaceWarm: "#ffdca8",
    foreground: "#2a1810", foregroundSecondary: "#593625", muted: "#8a6652", border: "#d9aa7a",
    accent: "#d24b1f", accentOn: "#ffffff", success: "#3d8f4f", warning: "#f2a93b", danger: "#b83a2f",
    fontDisplay: "Arial Black", fontBody: "Inter", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "neon", name: "Neon", category: "Morphism & Effects",
    description: "Bundled Open Design package for Neon, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#070711", surface: "#111126", surfaceWarm: "#1e1540",
    foreground: "#f8f7ff", foregroundSecondary: "#d6ccff", muted: "#9d8ad4", border: "#34265e",
    accent: "#c084fc", accentOn: "#13051f", success: "#39ff88", warning: "#fff34d", danger: "#ff4d8d",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "neumorphism", name: "Neumorphism", category: "Morphism & Effects",
    description: "Bundled Open Design package for Neumorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f7eee6", surface: "#fff8f1", surfaceWarm: "#ead6c7",
    foreground: "#2b211c", foregroundSecondary: "#5a4b43", muted: "#8a7a70", border: "#dac8b9",
    accent: "#b46a46", accentOn: "#ffffff", success: "#4d8f5a", warning: "#c88735", danger: "#b84c4c",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 14.0, radiusMd: 22.0, radiusLg: 34.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "nike", name: "Nike", category: "E-Commerce & Retail",
    description: "Bundled Open Design package for Nike, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f5f5f5", surfaceWarm: "#fafafa",
    foreground: "#111111", foregroundSecondary: "#111111", muted: "#707072", border: "#cacacb",
    accent: "#111111", accentOn: "#ffffff", success: "#007d48", warning: "#fca600", danger: "#d30005",
    fontDisplay: "Nike Futura ND", fontBody: "Helvetica Now Text Medium", textBase: 16.0,
    radiusSm: 8.0, radiusMd: 20.0, radiusLg: 24.0, radiusPill: 30.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1440.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 29,
  },
  {
    id: "notion", name: "Notion", category: "Productivity & SaaS",
    description: "Bundled Open Design package for Notion, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f6f5f4", surfaceWarm: "#f6f5f4",
    foreground: "#000000f2", foregroundSecondary: "#31302e", muted: "#615d59", border: "#0000001a",
    accent: "#0075de", accentOn: "#ffffff", success: "#1aae39", warning: "#dd5b00", danger: "#dc2626",
    fontDisplay: "NotionInter", fontBody: "NotionInter", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"], sourceClassCount: 22,
  },
  {
    id: "nvidia", name: "NVIDIA", category: "Media & Consumer",
    description: "Bundled Open Design package for NVIDIA, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#000000", surface: "#1a1a1a", surfaceWarm: "#1a1a1a",
    foreground: "#ffffff", foregroundSecondary: "#a7a7a7", muted: "#757575", border: "#5e5e5e",
    accent: "#76b900", accentOn: "#000000", success: "#3f8500", warning: "#ef9100", danger: "#e52020",
    fontDisplay: "NVIDIA-EMEA", fontBody: "NVIDIA-EMEA", textBase: 16.0,
    radiusSm: 2.0, radiusMd: 2.0, radiusLg: 4.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"], sourceClassCount: 31,
  },
  {
    id: "ollama", name: "Ollama", category: "AI & LLM",
    description: "Bundled Open Design package for Ollama, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#fafafa", surfaceWarm: "#fafafa",
    foreground: "#000000", foregroundSecondary: "#262626", muted: "#737373", border: "#e5e5e5",
    accent: "#000000", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#dc2626",
    fontDisplay: "SF Pro Rounded", fontBody: "ui-sans-serif", textBase: 16.0,
    radiusSm: 9999.0, radiusMd: 12.0, radiusLg: 9999.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 100, motionBaseMs: 140, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"], sourceClassCount: 34,
  },
  {
    id: "openai", name: "OpenAI", category: "AI & LLM",
    description: "Bundled Open Design package for OpenAI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f5f5f5", surfaceWarm: "#fafafa",
    foreground: "#0d0d0d", foregroundSecondary: "#1a1a1a", muted: "#6e6e6e", border: "#e5e5e5",
    accent: "#10a37f", accentOn: "#ffffff", success: "#10a37f", warning: "#f5a623", danger: "#ef4146",
    fontDisplay: "Signifier", fontBody: "Söhne", textBase: 16.0,
    radiusSm: 12.0, radiusMd: 16.0, radiusLg: 16.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 220, containerMax: 1200.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"], sourceClassCount: 18,
  },
  {
    id: "opencode-ai", name: "OpenCode", category: "AI & LLM",
    description: "Bundled Open Design package for OpenCode, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#201d1d", surface: "#302c2c", surfaceWarm: "#302c2c",
    foreground: "#fdfcfc", foregroundSecondary: "#c8c6c4", muted: "#9a9898", border: "#464343",
    accent: "#007aff", accentOn: "#ffffff", success: "#30d158", warning: "#ff9f0a", danger: "#ff3b30",
    fontDisplay: "Berkeley Mono", fontBody: "Berkeley Mono", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 6.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 100, motionBaseMs: 150, containerMax: 880.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "pacman", name: "Pacman", category: "Themed & Unique",
    description: "Bundled Open Design package for Pacman, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#050505", surface: "#101014", surfaceWarm: "#1f1b08",
    foreground: "#fff7d6", foregroundSecondary: "#f6e79c", muted: "#b9a85d", border: "#2338ff",
    accent: "#ffcc00", accentOn: "#050505", success: "#00ff66", warning: "#ff9900", danger: "#ff3b3b",
    fontDisplay: "Press Start 2P", fontBody: "Inter", textBase: 14.0,
    radiusSm: 10.0, radiusMd: 18.0, radiusLg: 9999.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 90, motionBaseMs: 160, containerMax: 1080.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "paper", name: "Paper", category: "Retro & Nostalgic",
    description: "Bundled Open Design package for Paper, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#faf3df", surface: "#fffaf0", surfaceWarm: "#efe0bd",
    foreground: "#211b12", foregroundSecondary: "#504737", muted: "#7c7160", border: "#ddd0b4",
    accent: "#8f5d24", accentOn: "#ffffff", success: "#5b8d42", warning: "#c27b22", danger: "#a64036",
    fontDisplay: "Georgia", fontBody: "Inter", textBase: 17.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "perplexity", name: "Perplexity AI", category: "AI & LLM",
    description: "Bundled Open Design package for Perplexity AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#0f0f10", surface: "#19191a", surfaceWarm: "#19191a",
    foreground: "#f0f0f0", foregroundSecondary: "#f0f0f0", muted: "#9b9b9b", border: "#2e2e30",
    accent: "#a855f7", accentOn: "#ffffff", success: "#22c55e", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 15.0,
    radiusSm: 4.0, radiusMd: 8.0, radiusLg: 12.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 120, motionBaseMs: 200, containerMax: 1100.0,
    componentGroups: ["buttons", "inputs", "cards", "links", "icons", "typography", "layout"], sourceClassCount: 23,
  },
  {
    id: "perspective", name: "Perspective", category: "Layout & Structure",
    description: "Bundled Open Design package for Perspective, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#f5f8ff", surface: "#ffffff", surfaceWarm: "#eaf1ff",
    foreground: "#101828", foregroundSecondary: "#344054", muted: "#667085", border: "#d7e0ef",
    accent: "#2563eb", accentOn: "#ffffff", success: "#16a34a", warning: "#f59e0b", danger: "#ef4444",
    fontDisplay: "Inter", fontBody: "Inter", textBase: 16.0,
    radiusSm: 10.0, radiusMd: 16.0, radiusLg: 24.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 240, containerMax: 1180.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"], sourceClassCount: 26,
  },
  {
    id: "pinterest", name: "Pinterest", category: "Media & Consumer",
    description: "Bundled Open Design package for Pinterest, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#ffffff", surface: "#f6f6f3", surfaceWarm: "#e5e5e0",
    foreground: "#211922", foregroundSecondary: "#000000", muted: "#62625b", border: "#c8c8c1",
    accent: "#e60023", accentOn: "#000000", success: "#103c25", warning: "#c47700", danger: "#9e0a0a",
    fontDisplay: "Pin Sans", fontBody: "Pin Sans", textBase: 16.0,
    radiusSm: 12.0, radiusMd: 16.0, radiusLg: 28.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 43,
  },
  {
    id: "playstation", name: "PlayStation", category: "Media & Consumer",
    description: "Bundled Open Design package for PlayStation, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "dark",
    background: "#000000", surface: "#ffffff", surfaceWarm: "#f5f7fa",
    foreground: "#ffffff", foregroundSecondary: "#ffffff", muted: "#cccccc", border: "#cccccc",
    accent: "#0070cc", accentOn: "#ffffff", success: "#16a34a", warning: "#eab308", danger: "#c81b3a",
    fontDisplay: "SST", fontBody: "SST", textBase: 18.0,
    radiusSm: 6.0, radiusMd: 12.0, radiusLg: 24.0, radiusPill: 999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 180, motionBaseMs: 200, containerMax: 1600.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 28,
  },
  {
    id: "posthog", name: "PostHog", category: "Backend & Data",
    description: "Bundled Open Design package for PostHog, derived from curated DESIGN.md, tokens.css, and components.html fixtures.", brightness: "light",
    background: "#fdfdf8", surface: "#eeefe9", surfaceWarm: "#e5e7e0",
    foreground: "#4d4f46", foregroundSecondary: "#23251d", muted: "#65675e", border: "#bfc1b7",
    accent: "#f54e00", accentOn: "#ffffff", success: "#16a34a", warning: "#f7a501", danger: "#dc2626",
    fontDisplay: "IBM Plex Sans Variable", fontBody: "IBM Plex Sans Variable", textBase: 16.0,
    radiusSm: 4.0, radiusMd: 6.0, radiusLg: 8.0, radiusPill: 9999.0,
    space1: 4.0, space2: 8.0, space3: 12.0, space4: 16.0, space6: 24.0, space8: 32.0,
    motionFastMs: 150, motionBaseMs: 200, containerMax: 1280.0,
    componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"], sourceClassCount: 42,
  },
] as const satisfies readonly AnduraDesignSystem[];
