// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const ciscoDesignSystem = {
  id: "cisco",
  name: "Cisco",
  category: "Backend & Data",
  description: "Bundled Open Design package for Cisco, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#0f1720",
  surface: "#1b2530",
  surfaceWarm: "#243447",
  foreground: "#ffffff",
  foregroundSecondary: "#e8ebf1",
  muted: "#9e9ea2",
  border: "#58585b",
  accent: "#049fd9",
  accentOn: "#001923",
  success: "#6cc04a",
  warning: "#ffcc00",
  danger: "#cf2030",
  fontDisplay: "CiscoSansTT",
  fontBody: "CiscoSansTT",
  textBase: 16.0,
  radiusSm: 12.0,
  radiusMd: 20.0,
  radiusLg: 28.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 160,
  motionBaseMs: 240,
  containerMax: 1240.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
