// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const claudeDesignSystem = {
  id: "claude",
  name: "Claude (Anthropic)",
  category: "AI & LLM",
  description: "Bundled Open Design package for Claude (Anthropic), derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f5f4ed",
  surface: "#faf9f5",
  surfaceWarm: "#e8e6dc",
  foreground: "#141413",
  foregroundSecondary: "#3d3d3a",
  muted: "#5e5d59",
  border: "#f0eee6",
  accent: "#c96442",
  accentOn: "#faf9f5",
  success: "#17a34a",
  warning: "#eab308",
  danger: "#b53333",
  fontDisplay: "Anthropic Serif",
  fontBody: "Anthropic Sans",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 25,
} as const satisfies AnduraDesignSystem;
