// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const clayDesignSystem = {
  id: "clay",
  name: "Clay",
  category: "Design & Creative",
  description: "Bundled Open Design package for Clay, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f7eee6",
  surface: "#fff8f1",
  surfaceWarm: "#ead6c7",
  foreground: "#2b211c",
  foregroundSecondary: "#5a4b43",
  muted: "#8a7a70",
  border: "#dac8b9",
  accent: "#b46a46",
  accentOn: "#ffffff",
  success: "#4d8f5a",
  warning: "#c88735",
  danger: "#b84c4c",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 14.0,
  radiusMd: 22.0,
  radiusLg: 34.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
