// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const clickhouseDesignSystem = {
  id: "clickhouse",
  name: "ClickHouse",
  category: "Backend & Data",
  description: "Bundled Open Design package for ClickHouse, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#000000",
  surface: "#141414",
  surfaceWarm: "#141414",
  foreground: "#ffffff",
  foregroundSecondary: "#a0a0a0",
  muted: "#a0a0a0",
  border: "#414141cc",
  accent: "#faff69",
  accentOn: "#151515",
  success: "#166534",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 38,
} as const satisfies AnduraDesignSystem;
