// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const cohereDesignSystem = {
  id: "cohere",
  name: "Cohere",
  category: "AI & LLM",
  description: "Bundled Open Design package for Cohere, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#fafafa",
  surfaceWarm: "#fafafa",
  foreground: "#000000",
  foregroundSecondary: "#212121",
  muted: "#93939f",
  border: "#d9d9dd",
  accent: "#1863dc",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#ef4444",
  fontDisplay: "CohereText",
  fontBody: "Unica77 Cohere Web",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 22.0,
  radiusLg: 22.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1440.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 25,
} as const satisfies AnduraDesignSystem;
