// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const coinbaseDesignSystem = {
  id: "coinbase",
  name: "Coinbase",
  category: "Fintech & Crypto",
  description: "Bundled Open Design package for Coinbase, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#eef0f3",
  surfaceWarm: "#eef0f3",
  foreground: "#0a0b0d",
  foregroundSecondary: "#0a0b0d",
  muted: "#5b616e",
  border: "#5b616e33",
  accent: "#0052ff",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "CoinbaseDisplay",
  fontBody: "CoinbaseText",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 16.0,
  radiusLg: 32.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 40,
} as const satisfies AnduraDesignSystem;
