// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const composioDesignSystem = {
  id: "composio",
  name: "Composio",
  category: "Backend & Data",
  description: "Bundled Open Design package for Composio, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#090b14",
  surface: "#121626",
  surfaceWarm: "#1b2140",
  foreground: "#f8fafc",
  foregroundSecondary: "#cbd5e1",
  muted: "#94a3b8",
  border: "#27324a",
  accent: "#6d5dfc",
  accentOn: "#ffffff",
  success: "#22c55e",
  warning: "#fbbf24",
  danger: "#fb7185",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 15.0,
  radiusSm: 10.0,
  radiusMd: 14.0,
  radiusLg: 22.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 140,
  motionBaseMs: 220,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
