// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const contemporaryDesignSystem = {
  id: "contemporary",
  name: "Contemporary",
  category: "Modern & Minimal",
  description: "Bundled Open Design package for Contemporary, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f5f8ff",
  surface: "#ffffff",
  surfaceWarm: "#eaf1ff",
  foreground: "#101828",
  foregroundSecondary: "#344054",
  muted: "#667085",
  border: "#d7e0ef",
  accent: "#2563eb",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#f59e0b",
  danger: "#ef4444",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
