// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const cursorDesignSystem = {
  id: "cursor",
  name: "Cursor",
  category: "Developer Tools",
  description: "Bundled Open Design package for Cursor, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f2f1ed",
  surface: "#e6e5e0",
  surfaceWarm: "#ebeae5",
  foreground: "#26251e",
  foregroundSecondary: "#26251ee6",
  muted: "#26251e8c",
  border: "#26251e1a",
  accent: "#f54e00",
  accentOn: "#ffffff",
  success: "#1f8a65",
  warning: "#eab308",
  danger: "#cf2d56",
  fontDisplay: "CursorGothic",
  fontBody: "jjannon",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 10.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 37,
} as const satisfies AnduraDesignSystem;
