// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const dashboardDesignSystem = {
  id: "dashboard",
  name: "Dashboard",
  category: "Professional & Corporate",
  description: "Bundled Open Design package for Dashboard, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f4f7fb",
  surface: "#ffffff",
  surfaceWarm: "#eef6ff",
  foreground: "#111827",
  foregroundSecondary: "#334155",
  muted: "#64748b",
  border: "#d8e2ee",
  accent: "#0ea5e9",
  accentOn: "#04131d",
  success: "#10b981",
  warning: "#f59e0b",
  danger: "#ef4444",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 15.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 18.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
