// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const defaultDesignSystem = {
  id: "default",
  name: "Neutral Modern",
  category: "Starter",
  description: "Bundled Open Design package for Neutral Modern, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fafafa",
  surface: "#ffffff",
  surfaceWarm: "#ffffff",
  foreground: "#111111",
  foregroundSecondary: "#111111",
  muted: "#6b6b6b",
  border: "#e5e5e5",
  accent: "#2f6feb",
  accentOn: "#ffffff",
  success: "#17a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 25,
} as const satisfies AnduraDesignSystem;
