// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const discordDesignSystem = {
  id: "discord",
  name: "Discord",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Discord, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#313338",
  surface: "#2b2d31",
  surfaceWarm: "#1e1f22",
  foreground: "#dbdee1",
  foregroundSecondary: "#f2f3f5",
  muted: "#949ba4",
  border: "#ffffff0f",
  accent: "#5865f2",
  accentOn: "#ffffff",
  success: "#23a55a",
  warning: "#f0b232",
  danger: "#f23f43",
  fontDisplay: "gg sans",
  fontBody: "gg sans",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 80,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "links", "typography", "layout"],
  sourceClassCount: 17,
} as const satisfies AnduraDesignSystem;
