// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const ditheredDesignSystem = {
  id: "dithered",
  name: "Dithered",
  category: "Retro & Nostalgic",
  description: "Bundled Open Design package for Dithered, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fff4cf",
  surface: "#fffaf0",
  surfaceWarm: "#ffdca8",
  foreground: "#2a1810",
  foregroundSecondary: "#593625",
  muted: "#8a6652",
  border: "#d9aa7a",
  accent: "#d24b1f",
  accentOn: "#ffffff",
  success: "#3d8f4f",
  warning: "#f2a93b",
  danger: "#b83a2f",
  fontDisplay: "Courier New",
  fontBody: "Inter",
  textBase: 14.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 100,
  motionBaseMs: 180,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
