// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const doodleDesignSystem = {
  id: "doodle",
  name: "Doodle",
  category: "Creative & Artistic",
  description: "Bundled Open Design package for Doodle, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fff8d7",
  surface: "#ffffff",
  surfaceWarm: "#ffef9f",
  foreground: "#1d1836",
  foregroundSecondary: "#4c426c",
  muted: "#796f91",
  border: "#eadfba",
  accent: "#ff6b00",
  accentOn: "#ffffff",
  success: "#2e9d57",
  warning: "#ffb020",
  danger: "#e5484d",
  fontDisplay: "Comic Sans MS",
  fontBody: "Comic Sans MS",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
