// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const dramaticDesignSystem = {
  id: "dramatic",
  name: "Dramatic",
  category: "Bold & Expressive",
  description: "Bundled Open Design package for Dramatic, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#090b12",
  surface: "#121722",
  surfaceWarm: "#1b2233",
  foreground: "#f8fafc",
  foregroundSecondary: "#cbd5e1",
  muted: "#94a3b8",
  border: "#2a3447",
  accent: "#60a5fa",
  accentOn: "#06101d",
  success: "#22c55e",
  warning: "#fbbf24",
  danger: "#fb7185",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
