// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const duolingoDesignSystem = {
  id: "duolingo",
  name: "Duolingo",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Duolingo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f7f7f7",
  surfaceWarm: "#f7f7f7",
  foreground: "#3c3c3c",
  foregroundSecondary: "#3c3c3c",
  muted: "#777777",
  border: "#e5e5e5",
  accent: "#58cc02",
  accentOn: "#ffffff",
  success: "#58cc02",
  warning: "#ffc800",
  danger: "#ff4b4b",
  fontDisplay: "Feather Bold",
  fontBody: "Mona Sans",
  textBase: 15.0,
  radiusSm: 12.0,
  radiusMd: 16.0,
  radiusLg: 20.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 180,
  motionBaseMs: 320,
  containerMax: 1080.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 36,
} as const satisfies AnduraDesignSystem;
