// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const editorialDesignSystem = {
  id: "editorial",
  name: "Editorial",
  category: "Creative & Artistic",
  description: "Bundled Open Design package for Editorial, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fbf7f0",
  surface: "#fffdf8",
  surfaceWarm: "#f1e6d6",
  foreground: "#1f1a16",
  foregroundSecondary: "#4b4038",
  muted: "#7d7168",
  border: "#ded3c5",
  accent: "#9a5a2f",
  accentOn: "#ffffff",
  success: "#4f8a4f",
  warning: "#c9822f",
  danger: "#b33a3a",
  fontDisplay: "Georgia",
  fontBody: "Source Serif Pro",
  textBase: 18.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 180,
  motionBaseMs: 280,
  containerMax: 1120.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
