// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const enterpriseDesignSystem = {
  id: "enterprise",
  name: "Enterprise",
  category: "Professional & Corporate",
  description: "Bundled Open Design package for Enterprise, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f8fafc",
  surface: "#ffffff",
  surfaceWarm: "#eef2f7",
  foreground: "#0f172a",
  foregroundSecondary: "#334155",
  muted: "#64748b",
  border: "#d8dee8",
  accent: "#1d4ed8",
  accentOn: "#ffffff",
  success: "#15803d",
  warning: "#b45309",
  danger: "#b91c1c",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 6.0,
  radiusMd: 10.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 230,
  containerMax: 1240.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
