// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const expoDesignSystem = {
  id: "expo",
  name: "Expo",
  category: "Developer Tools",
  description: "Bundled Open Design package for Expo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f6f7f9",
  surfaceWarm: "#eef2ff",
  foreground: "#0b0d12",
  foregroundSecondary: "#353945",
  muted: "#6b7280",
  border: "#dfe3ea",
  accent: "#000020",
  accentOn: "#ffffff",
  success: "#00a36c",
  warning: "#f59e0b",
  danger: "#e5484d",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 14.0,
  radiusLg: 22.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 140,
  motionBaseMs: 220,
  containerMax: 1160.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
