// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const expressiveDesignSystem = {
  id: "expressive",
  name: "Expressive",
  category: "Bold & Expressive",
  description: "Bundled Open Design package for Expressive, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fbf8ff",
  surface: "#ffffff",
  surfaceWarm: "#efe8ff",
  foreground: "#1f1730",
  foregroundSecondary: "#4d425f",
  muted: "#776b88",
  border: "#ded4ee",
  accent: "#7c3aed",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#f59e0b",
  danger: "#ef4444",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
