// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const ferrariDesignSystem = {
  id: "ferrari",
  name: "Ferrari",
  category: "Automotive",
  description: "Bundled Open Design package for Ferrari, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#0b0b0b",
  surface: "#171717",
  surfaceWarm: "#23130f",
  foreground: "#fffaf0",
  foregroundSecondary: "#e8dcc8",
  muted: "#a89f91",
  border: "#342a24",
  accent: "#dc0000",
  accentOn: "#ffffff",
  success: "#0f9d58",
  warning: "#ffd200",
  danger: "#ff3b30",
  fontDisplay: "Ferrari Sans",
  fontBody: "Ferrari Sans",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 14.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 130,
  motionBaseMs: 220,
  containerMax: 1240.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
