// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const figmaDesignSystem = {
  id: "figma",
  name: "Figma",
  category: "Design & Creative",
  description: "Bundled Open Design package for Figma, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#ffffff",
  foreground: "#000000",
  foregroundSecondary: "#000000",
  muted: "#0000008c",
  border: "#0000001f",
  accent: "#000000",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "figmaSans",
  fontBody: "figmaSans",
  textBase: 16.0,
  radiusSm: 50.0,
  radiusMd: 8.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1920.0,
  componentGroups: ["buttons", "inputs", "cards", "links", "icons", "typography", "layout"],
  sourceClassCount: 17,
} as const satisfies AnduraDesignSystem;
