// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const framerDesignSystem = {
  id: "framer",
  name: "Framer",
  category: "Design & Creative",
  description: "Bundled Open Design package for Framer, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#000000",
  surface: "#090909",
  surfaceWarm: "#090909",
  foreground: "#ffffff",
  foregroundSecondary: "#a6a6a6",
  muted: "#ffffff99",
  border: "#0099ff26",
  accent: "#0099ff",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "GT Walsheim Framer Medium",
  fontBody: "Inter Variable",
  textBase: 15.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 20.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 32,
} as const satisfies AnduraDesignSystem;
