// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const githubDesignSystem = {
  id: "github",
  name: "GitHub",
  category: "Developer Tools",
  description: "Bundled Open Design package for GitHub, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f6f8fa",
  surfaceWarm: "#f6f8fa",
  foreground: "#1f2328",
  foregroundSecondary: "#1f2328",
  muted: "#656d76",
  border: "#d0d7de",
  accent: "#0969da",
  accentOn: "#ffffff",
  success: "#1a7f37",
  warning: "#9a6700",
  danger: "#cf222e",
  fontDisplay: "-apple-system",
  fontBody: "-apple-system",
  textBase: 14.0,
  radiusSm: 6.0,
  radiusMd: 6.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 80,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "badges", "links", "icons", "typography", "layout"],
  sourceClassCount: 21,
} as const satisfies AnduraDesignSystem;
