// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const glassmorphismDesignSystem = {
  id: "glassmorphism",
  name: "Glassmorphism",
  category: "Morphism & Effects",
  description: "Bundled Open Design package for Glassmorphism, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#eef6ff",
  surface: "#ffffffbd",
  surfaceWarm: "#eef6ffb8",
  foreground: "#102033",
  foregroundSecondary: "#34465f",
  muted: "#60708a",
  border: "#ffffffa3",
  accent: "#4f8cff",
  accentOn: "#ffffff",
  success: "#22c55e",
  warning: "#f59e0b",
  danger: "#ef4444",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 16.0,
  radiusMd: 24.0,
  radiusLg: 36.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 180,
  motionBaseMs: 280,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
