// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const gradientDesignSystem = {
  id: "gradient",
  name: "Gradient",
  category: "Morphism & Effects",
  description: "Bundled Open Design package for Gradient, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f7f3ff",
  surface: "#ffffff",
  surfaceWarm: "#efe7ff",
  foreground: "#191225",
  foregroundSecondary: "#443856",
  muted: "#746985",
  border: "#ddd2f2",
  accent: "#7c3aed",
  accentOn: "#ffffff",
  success: "#10b981",
  warning: "#f59e0b",
  danger: "#ef4444",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 12.0,
  radiusMd: 20.0,
  radiusLg: 32.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 160,
  motionBaseMs: 260,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
