// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const hashicorpDesignSystem = {
  id: "hashicorp",
  name: "HashiCorp",
  category: "Backend & Data",
  description: "Bundled Open Design package for HashiCorp, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#15181e",
  surface: "#0d0e12",
  surfaceWarm: "#0d0e12",
  foreground: "#efeff1",
  foregroundSecondary: "#d5d7db",
  muted: "#b2b6bd",
  border: "#b2b6bd66",
  accent: "#1060ff",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#bb5a00",
  danger: "#dc2626",
  fontDisplay: "HashiCorp Sans",
  fontBody: "Poppins",
  textBase: 16.0,
  radiusSm: 5.0,
  radiusMd: 8.0,
  radiusLg: 8.0,
  radiusPill: 5.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1150.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 27,
} as const satisfies AnduraDesignSystem;
