// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const huggingfaceDesignSystem = {
  id: "huggingface",
  name: "Hugging Face",
  category: "AI & LLM",
  description: "Bundled Open Design package for Hugging Face, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fafafa",
  surface: "#ffffff",
  surfaceWarm: "#fff4cc",
  foreground: "#0d1117",
  foregroundSecondary: "#374151",
  muted: "#6b7280",
  border: "#e5e7eb",
  accent: "#ffd21e",
  accentOn: "#0d1117",
  success: "#16a34a",
  warning: "#f59e0b",
  danger: "#dc2626",
  fontDisplay: "IBM Plex Mono",
  fontBody: "Source Sans Pro",
  textBase: 15.0,
  radiusSm: 4.0,
  radiusMd: 6.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
