// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const ibmDesignSystem = {
  id: "ibm",
  name: "IBM",
  category: "Media & Consumer",
  description: "Bundled Open Design package for IBM, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f4f4f4",
  surfaceWarm: "#edf5ff",
  foreground: "#161616",
  foregroundSecondary: "#525252",
  muted: "#6f6f6f",
  border: "#c6c6c6",
  accent: "#0f62fe",
  accentOn: "#ffffff",
  success: "#24a148",
  warning: "#f1c21b",
  danger: "#da1e28",
  fontDisplay: "IBM Plex Sans",
  fontBody: "IBM Plex Sans",
  textBase: 16.0,
  radiusSm: 0.0,
  radiusMd: 0.0,
  radiusLg: 0.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 110,
  motionBaseMs: 180,
  containerMax: 1312.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
