// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const intercomDesignSystem = {
  id: "intercom",
  name: "Intercom",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Intercom, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#faf9f6",
  surface: "#ffffff",
  surfaceWarm: "#faf9f6",
  foreground: "#111111",
  foregroundSecondary: "#111111",
  muted: "#7b7b78",
  border: "#dedbd6",
  accent: "#ff5600",
  accentOn: "#ffffff",
  success: "#00da00",
  warning: "#eab308",
  danger: "#c41c1c",
  fontDisplay: "Saans",
  fontBody: "Saans",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 6.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 37,
} as const satisfies AnduraDesignSystem;
