// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const kamiDesignSystem = {
  id: "kami",
  name: "kami (紙 / 纸)",
  category: "Editorial & Print",
  description: "Bundled Open Design package for kami (紙 / 纸), derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f5f4ed",
  surface: "#faf9f5",
  surfaceWarm: "#e8e6dc",
  foreground: "#141413",
  foregroundSecondary: "#3d3d3a",
  muted: "#504e49",
  border: "#e8e6dc",
  accent: "#1b365d",
  accentOn: "#faf9f5",
  success: "#4a6b3a",
  warning: "#8a6b1f",
  danger: "#8a3a30",
  fontDisplay: "Charter",
  fontBody: "Charter",
  textBase: 14.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1120.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
