// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const krakenDesignSystem = {
  id: "kraken",
  name: "Kraken",
  category: "Fintech & Crypto",
  description: "Bundled Open Design package for Kraken, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#0b1020",
  surface: "#121a33",
  surfaceWarm: "#1b2450",
  foreground: "#f8fafc",
  foregroundSecondary: "#cbd5e1",
  muted: "#8b95aa",
  border: "#26314f",
  accent: "#7132f5",
  accentOn: "#ffffff",
  success: "#00c853",
  warning: "#ffb020",
  danger: "#ff4d6d",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 15.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 18.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
