// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const lamborghiniDesignSystem = {
  id: "lamborghini",
  name: "Lamborghini",
  category: "Automotive",
  description: "Bundled Open Design package for Lamborghini, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#050505",
  surface: "#141414",
  surfaceWarm: "#211b0b",
  foreground: "#f8f4e6",
  foregroundSecondary: "#d8ceb0",
  muted: "#9b927d",
  border: "#3a321d",
  accent: "#d4af37",
  accentOn: "#050505",
  success: "#39a852",
  warning: "#f7c948",
  danger: "#e63946",
  fontDisplay: "Lamborghini",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 2.0,
  radiusMd: 6.0,
  radiusLg: 10.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 210,
  containerMax: 1240.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
