// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const levelsDesignSystem = {
  id: "levels",
  name: "Levels",
  category: "Layout & Structure",
  description: "Bundled Open Design package for Levels, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fbf7ef",
  surface: "#ffffff",
  surfaceWarm: "#eef7ed",
  foreground: "#1f2a24",
  foregroundSecondary: "#435147",
  muted: "#788276",
  border: "#dbe3d7",
  accent: "#2f8f46",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#d97706",
  danger: "#dc2626",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 12.0,
  radiusMd: 18.0,
  radiusLg: 28.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 160,
  motionBaseMs: 240,
  containerMax: 1160.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
