// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const linearAppDesignSystem = {
  id: "linear-app",
  name: "Linear",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Linear, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#08090a",
  surface: "#191a1b",
  surfaceWarm: "#191a1b",
  foreground: "#f7f8f8",
  foregroundSecondary: "#d0d6e0",
  muted: "#8a8f98",
  border: "#ffffff14",
  accent: "#5e6ad2",
  accentOn: "#ffffff",
  success: "#27a644",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Inter Variable",
  fontBody: "Inter Variable",
  textBase: 16.0,
  radiusSm: 6.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"],
  sourceClassCount: 15,
} as const satisfies AnduraDesignSystem;
