// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const lingoDesignSystem = {
  id: "lingo",
  name: "Lingo",
  category: "Creative & Artistic",
  description: "Bundled Open Design package for Lingo, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fbf9ff",
  surface: "#ffffff",
  surfaceWarm: "#f1ecff",
  foreground: "#1d1b2a",
  foregroundSecondary: "#4f4863",
  muted: "#786f8f",
  border: "#ded7f0",
  accent: "#6d4aff",
  accentOn: "#ffffff",
  success: "#22a06b",
  warning: "#e6a700",
  danger: "#e5484d",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 230,
  containerMax: 1160.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
