// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const loomDesignSystem = {
  id: "loom",
  name: "Loom Design System",
  category: "Themed & Unique",
  description: "Bundled Open Design package for Loom Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f7f7f8",
  surfaceWarm: "#f7f7f8",
  foreground: "#1f1f23",
  foregroundSecondary: "#1f1f23",
  muted: "#6b6d76",
  border: "#e4e4e7",
  accent: "#625df5",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#d64770",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 14.0,
  radiusSm: 4.0,
  radiusMd: 6.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 100,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 31,
} as const satisfies AnduraDesignSystem;
