// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const lovableDesignSystem = {
  id: "lovable",
  name: "Lovable",
  category: "Developer Tools",
  description: "Bundled Open Design package for Lovable, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f7f4ed",
  surface: "#f7f4ed",
  surfaceWarm: "#f7f4ed",
  foreground: "#1c1c1c",
  foregroundSecondary: "#1c1c1cd4",
  muted: "#5f5f5d",
  border: "#eceae4",
  accent: "#ff4d8d",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Camera Plain Variable",
  fontBody: "Camera Plain Variable",
  textBase: 16.0,
  radiusSm: 6.0,
  radiusMd: 12.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 24,
} as const satisfies AnduraDesignSystem;
