// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const luxuryDesignSystem = {
  id: "luxury",
  name: "Luxury",
  category: "Professional & Corporate",
  description: "Bundled Open Design package for Luxury, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#080706",
  surface: "#151310",
  surfaceWarm: "#241e14",
  foreground: "#fff8ea",
  foregroundSecondary: "#d8cdb7",
  muted: "#9f927c",
  border: "#3a3020",
  accent: "#c6a15b",
  accentOn: "#080706",
  success: "#5fa36a",
  warning: "#d8a94f",
  danger: "#d85a52",
  fontDisplay: "Didot",
  fontBody: "Avenir Next",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 14.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 180,
  motionBaseMs: 300,
  containerMax: 1160.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
