// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const mastercardDesignSystem = {
  id: "mastercard",
  name: "Mastercard",
  category: "Fintech & Crypto",
  description: "Bundled Open Design package for Mastercard, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f3f0ee",
  surface: "#fcfbfa",
  surfaceWarm: "#f7e8de",
  foreground: "#141413",
  foregroundSecondary: "#262627",
  muted: "#696969",
  border: "#d1cdc7",
  accent: "#cf4500",
  accentOn: "#ffffff",
  success: "#2e7d32",
  warning: "#f79e1b",
  danger: "#eb001b",
  fontDisplay: "MarkForMC",
  fontBody: "MarkForMC",
  textBase: 16.0,
  radiusSm: 20.0,
  radiusMd: 40.0,
  radiusLg: 64.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 180,
  motionBaseMs: 260,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
