// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const materialDesignSystem = {
  id: "material",
  name: "Material",
  category: "Professional & Corporate",
  description: "Bundled Open Design package for Material, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f8fafd",
  surface: "#ffffff",
  surfaceWarm: "#e8f0fe",
  foreground: "#202124",
  foregroundSecondary: "#3c4043",
  muted: "#5f6368",
  border: "#dadce0",
  accent: "#1a73e8",
  accentOn: "#ffffff",
  success: "#188038",
  warning: "#f9ab00",
  danger: "#d93025",
  fontDisplay: "Google Sans",
  fontBody: "Roboto",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 12.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 250,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
