// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const metaDesignSystem = {
  id: "meta",
  name: "Meta (Store)",
  category: "E-Commerce & Retail",
  description: "Bundled Open Design package for Meta (Store), derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f7f8fa",
  surfaceWarm: "#f2f0e6",
  foreground: "#1c2b33",
  foregroundSecondary: "#5d6c7b",
  muted: "#65676b",
  border: "#ced0d4",
  accent: "#0064e0",
  accentOn: "#ffffff",
  success: "#31a24c",
  warning: "#f7b928",
  danger: "#e41e3f",
  fontDisplay: "Optimistic VF",
  fontBody: "Optimistic VF",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 20.0,
  radiusLg: 24.0,
  radiusPill: 100.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1440.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 31,
} as const satisfies AnduraDesignSystem;
