// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const minimaxDesignSystem = {
  id: "minimax",
  name: "MiniMax",
  category: "AI & LLM",
  description: "Bundled Open Design package for MiniMax, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#fafafa",
  surfaceWarm: "#f0f0f0",
  foreground: "#222222",
  foregroundSecondary: "#18181b",
  muted: "#45515e",
  border: "#e5e7eb",
  accent: "#1456f0",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Outfit",
  fontBody: "DM Sans",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 13.0,
  radiusLg: 20.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 33,
} as const satisfies AnduraDesignSystem;
