// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const minimalDesignSystem = {
  id: "minimal",
  name: "Minimal",
  category: "Modern & Minimal",
  description: "Bundled Open Design package for Minimal, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#fafafa",
  surfaceWarm: "#f5f5f5",
  foreground: "#111111",
  foregroundSecondary: "#3a3a3a",
  muted: "#777777",
  border: "#e2e2e2",
  accent: "#111111",
  accentOn: "#ffffff",
  success: "#168a46",
  warning: "#b7791f",
  danger: "#c53030",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 2.0,
  radiusMd: 4.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 140,
  motionBaseMs: 220,
  containerMax: 1120.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
