// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const mintlifyDesignSystem = {
  id: "mintlify",
  name: "Mintlify",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Mintlify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#fafafa",
  foreground: "#0d0d0d",
  foregroundSecondary: "#333333",
  muted: "#666666",
  border: "#0000000d",
  accent: "#18e299",
  accentOn: "#0d0d0d",
  success: "#16a34a",
  warning: "#c37d0d",
  danger: "#d45656",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 34,
} as const satisfies AnduraDesignSystem;
