// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const miroDesignSystem = {
  id: "miro",
  name: "Miro",
  category: "Design & Creative",
  description: "Bundled Open Design package for Miro, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fff7c2",
  surface: "#ffffff",
  surfaceWarm: "#fff3a3",
  foreground: "#050038",
  foregroundSecondary: "#322b6b",
  muted: "#605a8a",
  border: "#ded9ff",
  accent: "#ffd02f",
  accentOn: "#050038",
  success: "#1a7f37",
  warning: "#ff9f1c",
  danger: "#d92d20",
  fontDisplay: "Formular",
  fontBody: "Formular",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 18.0,
  radiusLg: 28.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 230,
  containerMax: 1220.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
