// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const mistralAiDesignSystem = {
  id: "mistral-ai",
  name: "Mistral AI",
  category: "AI & LLM",
  description: "Bundled Open Design package for Mistral AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fffaeb",
  surface: "#fff0c2",
  surfaceWarm: "#fff0c2",
  foreground: "#1f1f1f",
  foregroundSecondary: "#1f1f1f",
  muted: "#3d3d3d",
  border: "#f0e8c8",
  accent: "#fa520f",
  accentOn: "#ffffff",
  success: "#17a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Arial",
  fontBody: "Arial",
  textBase: 16.0,
  radiusSm: 2.0,
  radiusMd: 2.0,
  radiusLg: 4.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 25,
} as const satisfies AnduraDesignSystem;
