// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const modernDesignSystem = {
  id: "modern",
  name: "Modern",
  category: "Modern & Minimal",
  description: "Bundled Open Design package for Modern, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f7f8fc",
  surface: "#ffffff",
  surfaceWarm: "#eef1ff",
  foreground: "#111827",
  foregroundSecondary: "#374151",
  muted: "#6b7280",
  border: "#dfe3ed",
  accent: "#4f46e5",
  accentOn: "#ffffff",
  success: "#10b981",
  warning: "#f59e0b",
  danger: "#ef4444",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
