// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const mongodbDesignSystem = {
  id: "mongodb",
  name: "MongoDB",
  category: "Backend & Data",
  description: "Bundled Open Design package for MongoDB, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#001e2b",
  surface: "#1c2d38",
  surfaceWarm: "#1c2d38",
  foreground: "#ffffff",
  foregroundSecondary: "#e8edeb",
  muted: "#b8c4c2",
  border: "#3d4f58",
  accent: "#00ed64",
  accentOn: "#001e2b",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "MongoDB Value Serif",
  fontBody: "Euclid Circular A",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
