// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const nikeDesignSystem = {
  id: "nike",
  name: "Nike",
  category: "E-Commerce & Retail",
  description: "Bundled Open Design package for Nike, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f5f5f5",
  surfaceWarm: "#fafafa",
  foreground: "#111111",
  foregroundSecondary: "#111111",
  muted: "#707072",
  border: "#cacacb",
  accent: "#111111",
  accentOn: "#ffffff",
  success: "#007d48",
  warning: "#fca600",
  danger: "#d30005",
  fontDisplay: "Nike Futura ND",
  fontBody: "Helvetica Now Text Medium",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 20.0,
  radiusLg: 24.0,
  radiusPill: 30.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1440.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 29,
} as const satisfies AnduraDesignSystem;
