// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const notionDesignSystem = {
  id: "notion",
  name: "Notion",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Notion, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f6f5f4",
  surfaceWarm: "#f6f5f4",
  foreground: "#000000f2",
  foregroundSecondary: "#31302e",
  muted: "#615d59",
  border: "#0000001a",
  accent: "#0075de",
  accentOn: "#ffffff",
  success: "#1aae39",
  warning: "#dd5b00",
  danger: "#dc2626",
  fontDisplay: "NotionInter",
  fontBody: "NotionInter",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"],
  sourceClassCount: 22,
} as const satisfies AnduraDesignSystem;
