// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const nvidiaDesignSystem = {
  id: "nvidia",
  name: "NVIDIA",
  category: "Media & Consumer",
  description: "Bundled Open Design package for NVIDIA, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#000000",
  surface: "#1a1a1a",
  surfaceWarm: "#1a1a1a",
  foreground: "#ffffff",
  foregroundSecondary: "#a7a7a7",
  muted: "#757575",
  border: "#5e5e5e",
  accent: "#76b900",
  accentOn: "#000000",
  success: "#3f8500",
  warning: "#ef9100",
  danger: "#e52020",
  fontDisplay: "NVIDIA-EMEA",
  fontBody: "NVIDIA-EMEA",
  textBase: 16.0,
  radiusSm: 2.0,
  radiusMd: 2.0,
  radiusLg: 4.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"],
  sourceClassCount: 31,
} as const satisfies AnduraDesignSystem;
