// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const ollamaDesignSystem = {
  id: "ollama",
  name: "Ollama",
  category: "AI & LLM",
  description: "Bundled Open Design package for Ollama, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#fafafa",
  surfaceWarm: "#fafafa",
  foreground: "#000000",
  foregroundSecondary: "#262626",
  muted: "#737373",
  border: "#e5e5e5",
  accent: "#000000",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "SF Pro Rounded",
  fontBody: "ui-sans-serif",
  textBase: 16.0,
  radiusSm: 9999.0,
  radiusMd: 12.0,
  radiusLg: 9999.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 100,
  motionBaseMs: 140,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"],
  sourceClassCount: 34,
} as const satisfies AnduraDesignSystem;
