// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const opencodeAiDesignSystem = {
  id: "opencode-ai",
  name: "OpenCode",
  category: "AI & LLM",
  description: "Bundled Open Design package for OpenCode, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#201d1d",
  surface: "#302c2c",
  surfaceWarm: "#302c2c",
  foreground: "#fdfcfc",
  foregroundSecondary: "#c8c6c4",
  muted: "#9a9898",
  border: "#464343",
  accent: "#007aff",
  accentOn: "#ffffff",
  success: "#30d158",
  warning: "#ff9f0a",
  danger: "#ff3b30",
  fontDisplay: "Berkeley Mono",
  fontBody: "Berkeley Mono",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 6.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 100,
  motionBaseMs: 150,
  containerMax: 880.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
