// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const openaiDesignSystem = {
  id: "openai",
  name: "OpenAI",
  category: "AI & LLM",
  description: "Bundled Open Design package for OpenAI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f5f5f5",
  surfaceWarm: "#fafafa",
  foreground: "#0d0d0d",
  foregroundSecondary: "#1a1a1a",
  muted: "#6e6e6e",
  border: "#e5e5e5",
  accent: "#10a37f",
  accentOn: "#ffffff",
  success: "#10a37f",
  warning: "#f5a623",
  danger: "#ef4146",
  fontDisplay: "Signifier",
  fontBody: "Söhne",
  textBase: 16.0,
  radiusSm: 12.0,
  radiusMd: 16.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 220,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"],
  sourceClassCount: 18,
} as const satisfies AnduraDesignSystem;
