// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const pacmanDesignSystem = {
  id: "pacman",
  name: "Pacman",
  category: "Themed & Unique",
  description: "Bundled Open Design package for Pacman, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#050505",
  surface: "#101014",
  surfaceWarm: "#1f1b08",
  foreground: "#fff7d6",
  foregroundSecondary: "#f6e79c",
  muted: "#b9a85d",
  border: "#2338ff",
  accent: "#ffcc00",
  accentOn: "#050505",
  success: "#00ff66",
  warning: "#ff9900",
  danger: "#ff3b3b",
  fontDisplay: "Press Start 2P",
  fontBody: "Inter",
  textBase: 14.0,
  radiusSm: 10.0,
  radiusMd: 18.0,
  radiusLg: 9999.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 90,
  motionBaseMs: 160,
  containerMax: 1080.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
