// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const paperDesignSystem = {
  id: "paper",
  name: "Paper",
  category: "Retro & Nostalgic",
  description: "Bundled Open Design package for Paper, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#faf3df",
  surface: "#fffaf0",
  surfaceWarm: "#efe0bd",
  foreground: "#211b12",
  foregroundSecondary: "#504737",
  muted: "#7c7160",
  border: "#ddd0b4",
  accent: "#8f5d24",
  accentOn: "#ffffff",
  success: "#5b8d42",
  warning: "#c27b22",
  danger: "#a64036",
  fontDisplay: "Georgia",
  fontBody: "Inter",
  textBase: 17.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
