// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const perplexityDesignSystem = {
  id: "perplexity",
  name: "Perplexity AI",
  category: "AI & LLM",
  description: "Bundled Open Design package for Perplexity AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#0f0f10",
  surface: "#19191a",
  surfaceWarm: "#19191a",
  foreground: "#f0f0f0",
  foregroundSecondary: "#f0f0f0",
  muted: "#9b9b9b",
  border: "#2e2e30",
  accent: "#a855f7",
  accentOn: "#ffffff",
  success: "#22c55e",
  warning: "#f59e0b",
  danger: "#ef4444",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 15.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 200,
  containerMax: 1100.0,
  componentGroups: ["buttons", "inputs", "cards", "links", "icons", "typography", "layout"],
  sourceClassCount: 23,
} as const satisfies AnduraDesignSystem;
