// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const pinterestDesignSystem = {
  id: "pinterest",
  name: "Pinterest",
  category: "Media & Consumer",
  description: "Bundled Open Design package for Pinterest, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f6f6f3",
  surfaceWarm: "#e5e5e0",
  foreground: "#211922",
  foregroundSecondary: "#000000",
  muted: "#62625b",
  border: "#c8c8c1",
  accent: "#e60023",
  accentOn: "#000000",
  success: "#103c25",
  warning: "#c47700",
  danger: "#9e0a0a",
  fontDisplay: "Pin Sans",
  fontBody: "Pin Sans",
  textBase: 16.0,
  radiusSm: 12.0,
  radiusMd: 16.0,
  radiusLg: 28.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 43,
} as const satisfies AnduraDesignSystem;
