// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const playstationDesignSystem = {
  id: "playstation",
  name: "PlayStation",
  category: "Media & Consumer",
  description: "Bundled Open Design package for PlayStation, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#000000",
  surface: "#ffffff",
  surfaceWarm: "#f5f7fa",
  foreground: "#ffffff",
  foregroundSecondary: "#ffffff",
  muted: "#cccccc",
  border: "#cccccc",
  accent: "#0070cc",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#c81b3a",
  fontDisplay: "SST",
  fontBody: "SST",
  textBase: 18.0,
  radiusSm: 6.0,
  radiusMd: 12.0,
  radiusLg: 24.0,
  radiusPill: 999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 180,
  motionBaseMs: 200,
  containerMax: 1600.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 28,
} as const satisfies AnduraDesignSystem;
