// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const posthogDesignSystem = {
  id: "posthog",
  name: "PostHog",
  category: "Backend & Data",
  description: "Bundled Open Design package for PostHog, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fdfdf8",
  surface: "#eeefe9",
  surfaceWarm: "#e5e7e0",
  foreground: "#4d4f46",
  foregroundSecondary: "#23251d",
  muted: "#65675e",
  border: "#bfc1b7",
  accent: "#f54e00",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#f7a501",
  danger: "#dc2626",
  fontDisplay: "IBM Plex Sans Variable",
  fontBody: "IBM Plex Sans Variable",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 6.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 42,
} as const satisfies AnduraDesignSystem;
