// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const premiumDesignSystem = {
  id: "premium",
  name: "Premium",
  category: "Professional & Corporate",
  description: "Bundled Open Design package for Premium, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#faf8f4",
  surface: "#ffffff",
  surfaceWarm: "#f0e7d8",
  foreground: "#1c1b19",
  foregroundSecondary: "#4b4740",
  muted: "#746d63",
  border: "#ded6c9",
  accent: "#a06a3b",
  accentOn: "#ffffff",
  success: "#3f8f5f",
  warning: "#c4872c",
  danger: "#b84a4a",
  fontDisplay: "Canela",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 28.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 170,
  motionBaseMs: 280,
  containerMax: 1160.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
