// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const publicationDesignSystem = {
  id: "publication",
  name: "Publication",
  category: "Creative & Artistic",
  description: "Bundled Open Design package for Publication, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f6f6f6",
  surfaceWarm: "#fff2f0",
  foreground: "#0b0b0b",
  foregroundSecondary: "#333333",
  muted: "#666666",
  border: "#d6d6d6",
  accent: "#c1121f",
  accentOn: "#ffffff",
  success: "#0f8a3b",
  warning: "#d99a00",
  danger: "#b00020",
  fontDisplay: "Franklin Gothic",
  fontBody: "Georgia",
  textBase: 17.0,
  radiusSm: 0.0,
  radiusMd: 0.0,
  radiusLg: 0.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 200,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
