// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const raycastDesignSystem = {
  id: "raycast",
  name: "Raycast",
  category: "Developer Tools",
  description: "Bundled Open Design package for Raycast, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#07080a",
  surface: "#101111",
  surfaceWarm: "#101111",
  foreground: "#f9f9f9",
  foregroundSecondary: "#cecece",
  muted: "#9c9c9d",
  border: "#ffffff0f",
  accent: "#ff6363",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 6.0,
  radiusMd: 12.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "typography", "layout"],
  sourceClassCount: 23,
} as const satisfies AnduraDesignSystem;
