// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const renaultDesignSystem = {
  id: "renault",
  name: "Renault",
  category: "Automotive",
  description: "Bundled Open Design package for Renault, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f7f4ef",
  surface: "#ffffff",
  surfaceWarm: "#fff4bf",
  foreground: "#111111",
  foregroundSecondary: "#3f3f3f",
  muted: "#6f6b63",
  border: "#dfd8ca",
  accent: "#ffcc33",
  accentOn: "#111111",
  success: "#198754",
  warning: "#f59e0b",
  danger: "#d92d20",
  fontDisplay: "Renault Group",
  fontBody: "Renault Group",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 14.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 140,
  motionBaseMs: 230,
  containerMax: 1220.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
