// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const replicateDesignSystem = {
  id: "replicate",
  name: "Replicate",
  category: "AI & LLM",
  description: "Bundled Open Design package for Replicate, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f8f8f8",
  surfaceWarm: "#f8f8f8",
  foreground: "#202020",
  foregroundSecondary: "#4e4e4e",
  muted: "#646464",
  border: "#202020",
  accent: "#ea2804",
  accentOn: "#ffffff",
  success: "#2b9a66",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "rb-freigeist-neue",
  fontBody: "basier-square",
  textBase: 16.0,
  radiusSm: 9999.0,
  radiusMd: 9999.0,
  radiusLg: 9999.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 25,
} as const satisfies AnduraDesignSystem;
