// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const resendDesignSystem = {
  id: "resend",
  name: "Resend",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Resend, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#000000",
  surface: "#000000",
  surfaceWarm: "#000000",
  foreground: "#f0f0f0",
  foregroundSecondary: "#a1a4a5",
  muted: "#5c5c5c",
  border: "#d6ebfd30",
  accent: "#ff801f",
  accentOn: "#000000",
  success: "#11ff99",
  warning: "#ffc53d",
  danger: "#ff2047",
  fontDisplay: "ABC Favorit",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 39,
} as const satisfies AnduraDesignSystem;
