// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const revolutDesignSystem = {
  id: "revolut",
  name: "Revolut",
  category: "Fintech & Crypto",
  description: "Bundled Open Design package for Revolut, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f7f8fb",
  surface: "#ffffff",
  surfaceWarm: "#eef4ff",
  foreground: "#111827",
  foregroundSecondary: "#334155",
  muted: "#64748b",
  border: "#dbe3ef",
  accent: "#0666eb",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#f59e0b",
  danger: "#ef4444",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 12.0,
  radiusMd: 20.0,
  radiusLg: 30.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
