// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const runwaymlDesignSystem = {
  id: "runwayml",
  name: "Runway",
  category: "AI & LLM",
  description: "Bundled Open Design package for Runway, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#000000",
  surface: "#1a1a1a",
  surfaceWarm: "#030303",
  foreground: "#ffffff",
  foregroundSecondary: "#e9ecf2",
  muted: "#767d88",
  border: "#27272a",
  accent: "#ffffff",
  accentOn: "#000000",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "abcNormal",
  fontBody: "abcNormal",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 220,
  containerMax: 1600.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 35,
} as const satisfies AnduraDesignSystem;
