// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const sanityDesignSystem = {
  id: "sanity",
  name: "Sanity",
  category: "Backend & Data",
  description: "Bundled Open Design package for Sanity, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f8f8f7",
  surface: "#ffffff",
  surfaceWarm: "#fff1ef",
  foreground: "#171717",
  foregroundSecondary: "#3f3f46",
  muted: "#71717a",
  border: "#e4e4e7",
  accent: "#f03e2f",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#f59e0b",
  danger: "#dc2626",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 6.0,
  radiusMd: 10.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 140,
  motionBaseMs: 210,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
