// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const sentryDesignSystem = {
  id: "sentry",
  name: "Sentry",
  category: "Backend & Data",
  description: "Bundled Open Design package for Sentry, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#1f1633",
  surface: "#150f23",
  surfaceWarm: "#150f23",
  foreground: "#ffffff",
  foregroundSecondary: "#e5e7eb",
  muted: "#9d96b3",
  border: "#362d59",
  accent: "#6a5fc1",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Dammit Sans",
  fontBody: "Rubik",
  textBase: 16.0,
  radiusSm: 6.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1152.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 27,
} as const satisfies AnduraDesignSystem;
