// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const shadcnDesignSystem = {
  id: "shadcn",
  name: "Shadcn",
  category: "Modern & Minimal",
  description: "Bundled Open Design package for Shadcn, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#ffffff",
  foreground: "#111827",
  foregroundSecondary: "#111827",
  muted: "#64748b",
  border: "#e5e7eb",
  accent: "#000000",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#d97706",
  danger: "#dc2626",
  fontDisplay: "Geist",
  fontBody: "Geist",
  textBase: 16.0,
  radiusSm: 6.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 32,
} as const satisfies AnduraDesignSystem;
