// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const shopifyDesignSystem = {
  id: "shopify",
  name: "Shopify",
  category: "E-Commerce & Retail",
  description: "Bundled Open Design package for Shopify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#000000",
  surface: "#02090a",
  surfaceWarm: "#061a1c",
  foreground: "#ffffff",
  foregroundSecondary: "#ffffff",
  muted: "#a1a1aa",
  border: "#1e2c31",
  accent: "#36f4a4",
  accentOn: "#000000",
  success: "#36f4a4",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "NeueHaasGrotesk",
  fontBody: "Inter Variable",
  textBase: 18.0,
  radiusSm: 9999.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 28.0,
  space8: 36.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "links", "icons", "typography", "layout"],
  sourceClassCount: 15,
} as const satisfies AnduraDesignSystem;
