// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const slackDesignSystem = {
  id: "slack",
  name: "Slack",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Slack, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f8f8f8",
  surfaceWarm: "#f8f8f8",
  foreground: "#1d1c1d",
  foregroundSecondary: "#1d1c1d",
  muted: "#616061",
  border: "#dddddd",
  accent: "#4a154b",
  accentOn: "#ffffff",
  success: "#2eb67d",
  warning: "#ecb22e",
  danger: "#e01e5a",
  fontDisplay: "Larsseit",
  fontBody: "Poppins",
  textBase: 15.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "links", "typography", "layout"],
  sourceClassCount: 19,
} as const satisfies AnduraDesignSystem;
