// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const spacexDesignSystem = {
  id: "spacex",
  name: "SpaceX",
  category: "Media & Consumer",
  description: "Bundled Open Design package for SpaceX, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#000000",
  surface: "#000000",
  surfaceWarm: "#000000",
  foreground: "#f0f0fa",
  foregroundSecondary: "#f0f0fa",
  muted: "#f0f0fab2",
  border: "#f0f0fa59",
  accent: "#f0f0fa",
  accentOn: "#000000",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "D-DIN-Bold",
  fontBody: "D-DIN",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 4.0,
  radiusLg: 4.0,
  radiusPill: 32.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1440.0,
  componentGroups: ["buttons", "inputs", "links", "icons", "typography", "layout"],
  sourceClassCount: 22,
} as const satisfies AnduraDesignSystem;
