// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const spotifyDesignSystem = {
  id: "spotify",
  name: "Spotify",
  category: "Media & Consumer",
  description: "Bundled Open Design package for Spotify, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#121212",
  surface: "#181818",
  surfaceWarm: "#1f1f1f",
  foreground: "#ffffff",
  foregroundSecondary: "#fdfdfd",
  muted: "#b3b3b3",
  border: "#4d4d4d",
  accent: "#1ed760",
  accentOn: "#000000",
  success: "#1ed760",
  warning: "#ffa42b",
  danger: "#f3727f",
  fontDisplay: "SpotifyMixUITitle",
  fontBody: "SpotifyMixUI",
  textBase: 16.0,
  radiusSm: 9999.0,
  radiusMd: 6.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "cards", "links", "icons", "typography", "layout"],
  sourceClassCount: 20,
} as const satisfies AnduraDesignSystem;
