// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const starbucksDesignSystem = {
  id: "starbucks",
  name: "Starbucks",
  category: "E-Commerce & Retail",
  description: "Bundled Open Design package for Starbucks, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f2f0eb",
  surface: "#ffffff",
  surfaceWarm: "#edebe9",
  foreground: "#000000de",
  foregroundSecondary: "#33433d",
  muted: "#00000094",
  border: "#d6dbde",
  accent: "#00754a",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#fbbc05",
  danger: "#c82014",
  fontDisplay: "SoDoSans",
  fontBody: "SoDoSans",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 12.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1440.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 30,
} as const satisfies AnduraDesignSystem;
