// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const stripeDesignSystem = {
  id: "stripe",
  name: "Stripe",
  category: "Fintech & Crypto",
  description: "Bundled Open Design package for Stripe, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#f6f9fc",
  foreground: "#061b31",
  foregroundSecondary: "#273951",
  muted: "#64748d",
  border: "#e5edf5",
  accent: "#533afd",
  accentOn: "#ffffff",
  success: "#15be53",
  warning: "#9b6829",
  danger: "#ea2261",
  fontDisplay: "sohne-var",
  fontBody: "sohne-var",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 6.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1080.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 45,
} as const satisfies AnduraDesignSystem;
