// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const supabaseDesignSystem = {
  id: "supabase",
  name: "Supabase",
  category: "Backend & Data",
  description: "Bundled Open Design package for Supabase, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#171717",
  surface: "#1c1c1c",
  surfaceWarm: "#1c1c1c",
  foreground: "#fafafa",
  foregroundSecondary: "#b4b4b4",
  muted: "#898989",
  border: "#2e2e2e",
  accent: "#3ecf8e",
  accentOn: "#0f0f0f",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Circular",
  fontBody: "Circular",
  textBase: 16.0,
  radiusSm: 6.0,
  radiusMd: 8.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 30,
} as const satisfies AnduraDesignSystem;
