// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const superhumanDesignSystem = {
  id: "superhuman",
  name: "Superhuman",
  category: "Developer Tools",
  description: "Bundled Open Design package for Superhuman, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#e9e5dd",
  foreground: "#292827",
  foregroundSecondary: "#292827",
  muted: "#6f6c69",
  border: "#dcd7d3",
  accent: "#cbb7fb",
  accentOn: "#292827",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Super Sans VF",
  fontBody: "Super Sans VF",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 8.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 31,
} as const satisfies AnduraDesignSystem;
