// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const teslaDesignSystem = {
  id: "tesla",
  name: "Tesla",
  category: "Automotive",
  description: "Bundled Open Design package for Tesla, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f4f4f4",
  surfaceWarm: "#f4f4f4",
  foreground: "#171a20",
  foregroundSecondary: "#393c41",
  muted: "#5c5e62",
  border: "#d0d1d2",
  accent: "#3e6ae1",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Universal Sans Display",
  fontBody: "Universal Sans Text",
  textBase: 14.0,
  radiusSm: 4.0,
  radiusMd: 12.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 250,
  motionBaseMs: 330,
  containerMax: 1383.0,
  componentGroups: ["buttons", "inputs", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 37,
} as const satisfies AnduraDesignSystem;
