// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const tetrisDesignSystem = {
  id: "tetris",
  name: "Tetris",
  category: "Themed & Unique",
  description: "Bundled Open Design package for Tetris, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#050816",
  surface: "#10162a",
  surfaceWarm: "#17203a",
  foreground: "#f8fafc",
  foregroundSecondary: "#cbd5e1",
  muted: "#94a3b8",
  border: "#26324f",
  accent: "#00f0f0",
  accentOn: "#061018",
  success: "#00f000",
  warning: "#f0f000",
  danger: "#f00000",
  fontDisplay: "Press Start 2P",
  fontBody: "Inter",
  textBase: 14.0,
  radiusSm: 0.0,
  radiusMd: 0.0,
  radiusLg: 4.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 80,
  motionBaseMs: 140,
  containerMax: 1100.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
