// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const thevergeDesignSystem = {
  id: "theverge",
  name: "The Verge",
  category: "Media & Consumer",
  description: "Bundled Open Design package for The Verge, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#050505",
  surface: "#111111",
  surfaceWarm: "#211022",
  foreground: "#ffffff",
  foregroundSecondary: "#e5e7eb",
  muted: "#9ca3af",
  border: "#2b2b2b",
  accent: "#ff00a8",
  accentOn: "#ffffff",
  success: "#22c55e",
  warning: "#facc15",
  danger: "#ef4444",
  fontDisplay: "PolySans",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 200,
  containerMax: 1240.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
