// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const togetherAiDesignSystem = {
  id: "together-ai",
  name: "Together AI",
  category: "AI & LLM",
  description: "Bundled Open Design package for Together AI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#ffffff",
  foreground: "#000000",
  foregroundSecondary: "#00000099",
  muted: "#666666",
  border: "#ebebeb",
  accent: "#010120",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "The Future",
  fontBody: "The Future",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"],
  sourceClassCount: 25,
} as const satisfies AnduraDesignSystem;
