// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const tomModernDesignSystem = {
  id: "tom-modern",
  name: "Tom Modern Design",
  category: "Starter",
  description: "Editorial-technical design system. Neutral canvas, single vermillion accent, sharp corners, Geist typography, hard shadows, structured composition.",
  brightness: "light",
  background: "#fafafa",
  surface: "#ffffff",
  surfaceWarm: "#ffffff",
  foreground: "#27272a",
  foregroundSecondary: "#52525b",
  muted: "#71717a",
  border: "#969696",
  accent: "#ff5a00",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Geist Sans",
  fontBody: "Geist Sans",
  textBase: 15.0,
  radiusSm: 0.0,
  radiusMd: 0.0,
  radiusLg: 0.0,
  radiusPill: 0.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1240.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 0,
} as const satisfies AnduraDesignSystem;
