// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const totalityFestivalDesignSystem = {
  id: "totality-festival",
  name: "Totality Festival",
  category: "Themed & Unique",
  description: "Bundled Open Design package for Totality Festival, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#070711",
  surface: "#111126",
  surfaceWarm: "#1e1540",
  foreground: "#f8f7ff",
  foregroundSecondary: "#d6ccff",
  muted: "#9d8ad4",
  border: "#34265e",
  accent: "#c084fc",
  accentOn: "#13051f",
  success: "#39ff88",
  warning: "#fff34d",
  danger: "#ff4d8d",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
