// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const tradingTerminalDesignSystem = {
  id: "trading-terminal",
  name: "Trading Terminal Design System",
  category: "Themed & Unique",
  description: "Bundled Open Design package for Trading Terminal Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#070b12",
  surface: "#101826",
  surfaceWarm: "#162238",
  foreground: "#f8fafc",
  foregroundSecondary: "#cbd5e1",
  muted: "#8492a6",
  border: "#263246",
  accent: "#38bdf8",
  accentOn: "#03111a",
  success: "#22c55e",
  warning: "#f59e0b",
  danger: "#ef4444",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 14.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 90,
  motionBaseMs: 160,
  containerMax: 1320.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
