// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const uberDesignSystem = {
  id: "uber",
  name: "Uber",
  category: "Media & Consumer",
  description: "Bundled Open Design package for Uber, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#f8f8f8",
  foreground: "#000000",
  foregroundSecondary: "#000000",
  muted: "#4b4b4b",
  border: "#000000",
  accent: "#000000",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "UberMove",
  fontBody: "UberMoveText",
  textBase: 16.0,
  radiusSm: 999.0,
  radiusMd: 8.0,
  radiusLg: 12.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1136.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "icons", "typography", "layout"],
  sourceClassCount: 19,
} as const satisfies AnduraDesignSystem;
