// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const urduDesignSystem = {
  id: "urdu",
  name: "Urdu Modern (Indus Script System)",
  category: "Editorial / Personal / Publication",
  description: "Bundled Open Design package for Urdu Modern (Indus Script System), derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f3faf4",
  surface: "#ffffff",
  surfaceWarm: "#e5f5e7",
  foreground: "#15261a",
  foregroundSecondary: "#38513e",
  muted: "#6b7d70",
  border: "#d4e3d7",
  accent: "#1f8f46",
  accentOn: "#ffffff",
  success: "#16a34a",
  warning: "#d97706",
  danger: "#dc2626",
  fontDisplay: "Georgia",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
