// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const vodafoneDesignSystem = {
  id: "vodafone",
  name: "Vodafone",
  category: "Media & Consumer",
  description: "Bundled Open Design package for Vodafone, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f4f4f4",
  surfaceWarm: "#fff1f1",
  foreground: "#1f1f1f",
  foregroundSecondary: "#4a4d4e",
  muted: "#6f7375",
  border: "#d8d8d8",
  accent: "#e60000",
  accentOn: "#ffffff",
  success: "#008a00",
  warning: "#f5b400",
  danger: "#bd0000",
  fontDisplay: "Vodafone",
  fontBody: "Vodafone",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 220,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
