// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const voltagentDesignSystem = {
  id: "voltagent",
  name: "VoltAgent",
  category: "AI & LLM",
  description: "Bundled Open Design package for VoltAgent, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#07110c",
  surface: "#101c16",
  surfaceWarm: "#14281e",
  foreground: "#f4fff8",
  foregroundSecondary: "#c8dfd0",
  muted: "#8ba493",
  border: "#254132",
  accent: "#7cff6b",
  accentOn: "#07110c",
  success: "#52e875",
  warning: "#facc15",
  danger: "#fb7185",
  fontDisplay: "Inter",
  fontBody: "Inter",
  textBase: 15.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 18.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 210,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
