// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const warmEditorialDesignSystem = {
  id: "warm-editorial",
  name: "Warm Editorial",
  category: "Starter",
  description: "Bundled Open Design package for Warm Editorial, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fbf6ee",
  surface: "#fffdf8",
  surfaceWarm: "#f1e3cf",
  foreground: "#201914",
  foregroundSecondary: "#4c4037",
  muted: "#7a6d63",
  border: "#ded2c3",
  accent: "#9b5b32",
  accentOn: "#ffffff",
  success: "#4f8a4f",
  warning: "#c9822f",
  danger: "#b33a3a",
  fontDisplay: "Georgia",
  fontBody: "Inter",
  textBase: 17.0,
  radiusSm: 10.0,
  radiusMd: 16.0,
  radiusLg: 24.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
