// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const warpDesignSystem = {
  id: "warp",
  name: "Warp",
  category: "Developer Tools",
  description: "Bundled Open Design package for Warp, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#161412",
  surface: "#1f1d1b",
  surfaceWarm: "#1f1d1b",
  foreground: "#faf9f6",
  foregroundSecondary: "#afaeac",
  muted: "#868584",
  border: "#e2e2e259",
  accent: "#353534",
  accentOn: "#afaeac",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "Matter Regular",
  fontBody: "Matter Regular",
  textBase: 18.0,
  radiusSm: 6.0,
  radiusMd: 12.0,
  radiusLg: 14.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1500.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 28,
} as const satisfies AnduraDesignSystem;
