// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const webexDesignSystem = {
  id: "webex",
  name: "Webex",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Webex, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f6f8fb",
  surface: "#ffffff",
  surfaceWarm: "#eef8f6",
  foreground: "#0f172a",
  foregroundSecondary: "#334155",
  muted: "#64748b",
  border: "#dbe4ee",
  accent: "#00a3a6",
  accentOn: "#ffffff",
  success: "#22c55e",
  warning: "#f59e0b",
  danger: "#e11d48",
  fontDisplay: "CiscoSansTT",
  fontBody: "CiscoSansTT",
  textBase: 16.0,
  radiusSm: 12.0,
  radiusMd: 18.0,
  radiusLg: 28.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 160,
  motionBaseMs: 240,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
