// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const webflowDesignSystem = {
  id: "webflow",
  name: "Webflow",
  category: "Design & Creative",
  description: "Bundled Open Design package for Webflow, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceWarm: "#ffffff",
  foreground: "#080808",
  foregroundSecondary: "#363636",
  muted: "#5a5a5a",
  border: "#d8d8d8",
  accent: "#146ef5",
  accentOn: "#ffffff",
  success: "#00d722",
  warning: "#ffae13",
  danger: "#ee1d36",
  fontDisplay: "WF Visual Sans Variable",
  fontBody: "WF Visual Sans Variable",
  textBase: 16.0,
  radiusSm: 4.0,
  radiusMd: 4.0,
  radiusLg: 8.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 28,
} as const satisfies AnduraDesignSystem;
