// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const wechatDesignSystem = {
  id: "wechat",
  name: "WeChat Design System",
  category: "Social & Messaging",
  description: "Bundled Open Design package for WeChat Design System, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ededed",
  surface: "#f7f7f7",
  surfaceWarm: "#f7f7f7",
  foreground: "#1a1a1a",
  foregroundSecondary: "#1a1a1a",
  muted: "#888888",
  border: "#e0e0e0",
  accent: "#07c160",
  accentOn: "#ffffff",
  success: "#07c160",
  warning: "#fab702",
  danger: "#fa5151",
  fontDisplay: "-apple-system",
  fontBody: "-apple-system",
  textBase: 15.0,
  radiusSm: 4.0,
  radiusMd: 8.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 100,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 34,
} as const satisfies AnduraDesignSystem;
