// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const wiredDesignSystem = {
  id: "wired",
  name: "WIRED",
  category: "Media & Consumer",
  description: "Bundled Open Design package for WIRED, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#f2f2f2",
  surfaceWarm: "#fff0f0",
  foreground: "#000000",
  foregroundSecondary: "#333333",
  muted: "#666666",
  border: "#d0d0d0",
  accent: "#e10600",
  accentOn: "#ffffff",
  success: "#0f8a3b",
  warning: "#f5a400",
  danger: "#c40000",
  fontDisplay: "Druk Wide",
  fontBody: "Exchange",
  textBase: 17.0,
  radiusSm: 0.0,
  radiusMd: 0.0,
  radiusLg: 0.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 120,
  motionBaseMs: 200,
  containerMax: 1180.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
