// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const wiseDesignSystem = {
  id: "wise",
  name: "Wise",
  category: "Fintech & Crypto",
  description: "Bundled Open Design package for Wise, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#ffffff",
  surface: "#e8ebe6",
  surfaceWarm: "#e8ebe6",
  foreground: "#0e0f0c",
  foregroundSecondary: "#0e0f0c",
  muted: "#868685",
  border: "#0e0f0c1f",
  accent: "#9fe870",
  accentOn: "#163300",
  success: "#054d28",
  warning: "#ffd11a",
  danger: "#d03238",
  fontDisplay: "Wise Sans",
  fontBody: "Inter",
  textBase: 18.0,
  radiusSm: 16.0,
  radiusMd: 30.0,
  radiusLg: 40.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1280.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 28,
} as const satisfies AnduraDesignSystem;
