// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const xAiDesignSystem = {
  id: "x-ai",
  name: "xAI",
  category: "AI & LLM",
  description: "Bundled Open Design package for xAI, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "dark",
  background: "#1f2228",
  surface: "#ffffff08",
  surfaceWarm: "#ffffff0d",
  foreground: "#ffffff",
  foregroundSecondary: "#ffffffb2",
  muted: "#ffffff80",
  border: "#ffffff1a",
  accent: "#ffffff",
  accentOn: "#1f2228",
  success: "#16a34a",
  warning: "#eab308",
  danger: "#dc2626",
  fontDisplay: "GeistMono",
  fontBody: "universalSans",
  textBase: 16.0,
  radiusSm: 0.0,
  radiusMd: 0.0,
  radiusLg: 4.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 23,
} as const satisfies AnduraDesignSystem;
