// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const xiaohongshuDesignSystem = {
  id: "xiaohongshu",
  name: "Xiaohongshu",
  category: "Media & Consumer",
  description: "Bundled Open Design package for Xiaohongshu, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#f5f5f5",
  surface: "#ffffff",
  surfaceWarm: "#fafafa",
  foreground: "#000000cc",
  foregroundSecondary: "#0000009e",
  muted: "#00000073",
  border: "#00000014",
  accent: "#ff2442",
  accentOn: "#ffffff",
  success: "#02b940",
  warning: "#ff7d03",
  danger: "#ff2442",
  fontDisplay: "PingFang SC",
  fontBody: "PingFang SC",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 16.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 150,
  motionBaseMs: 200,
  containerMax: 1200.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "keyboard", "icons", "typography", "layout"],
  sourceClassCount: 49,
} as const satisfies AnduraDesignSystem;
