// GENERATED FILE - DO NOT EDIT.
import type { AnduraDesignSystem } from './types';

export const zapierDesignSystem = {
  id: "zapier",
  name: "Zapier",
  category: "Productivity & SaaS",
  description: "Bundled Open Design package for Zapier, derived from curated DESIGN.md, tokens.css, and components.html fixtures.",
  brightness: "light",
  background: "#fff7ed",
  surface: "#ffffff",
  surfaceWarm: "#ffedd5",
  foreground: "#2d2a26",
  foregroundSecondary: "#574f45",
  muted: "#7c6f64",
  border: "#eadfd3",
  accent: "#ff4f00",
  accentOn: "#ffffff",
  success: "#15803d",
  warning: "#d97706",
  danger: "#dc2626",
  fontDisplay: "Degular",
  fontBody: "Inter",
  textBase: 16.0,
  radiusSm: 8.0,
  radiusMd: 12.0,
  radiusLg: 20.0,
  radiusPill: 9999.0,
  space1: 4.0,
  space2: 8.0,
  space3: 12.0,
  space4: 16.0,
  space6: 24.0,
  space8: 32.0,
  motionFastMs: 140,
  motionBaseMs: 220,
  containerMax: 1160.0,
  componentGroups: ["buttons", "inputs", "cards", "badges", "links", "typography", "layout"],
  sourceClassCount: 26,
} as const satisfies AnduraDesignSystem;
